# -*- coding: utf-8 -*-
"""hammer

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1f3-C7iDNTW9Gy9yGNrmeltxzC7-_siMR
"""

import numpy as np
import matplotlib.pyplot as plt
from mpl_toolkits.mplot3d import Axes3D

# Parameter für die USK (Faltungskugel)
R = 1  # Radus der Kugel
alpha = 0.5  # Faltungsintensität
p = 2  # Projectionsexponent
n_steps = 10  # Anzahl der Faltungsschritte

# Funktion zur Berechnung der Position auf der USK nach n Faltungsschritten
def usk_position(n, theta, phi, gamma):
    xi = 1 / (1 + alpha * n**p) * gamma  # Gamma-Wert beeinflusst die Faltungstiefe
    r = R * xi
    x = r * np.sin(theta) * np.cos(phi)
    y = r * np.sin(theta) * np.sin(phi)
    z = r * np.cos(theta)
    return x, y, z

# RVT-Boost-Faktor als Funktion des Inklinationswinkels i
def rvt_boost(i_deg):
    i_rad = np.radians(i_deg)
    return 1 + 0.8 * np.sin(i_rad)

# Normalisierte Projektiondivergenz D_norm als Funktion des Inklinationswinkels i
def norm_divergence(i_deg):
    gamma_i = rvt_boost(i_deg)
    gamma_270 = rvt_boost(270)
    gamma_90 = rvt_boost(90)
    return abs(gamma_i - gamma_270) / abs(gamma_90 - gamma_270)

# Erzeuge eine Kugeloberfläche für verschiedene Faltungsschritte
theta = np.linspace(0, np.pi, 50)
phi = np.linspace(0, 2 * np.pi, 50)
theta_grid, phi_grid = np.meshgrid(theta, phi)

# Berechnung der Gamma-Werte und Divergenzen für NGC 891 und M101
inclination_ngc891 = 85
inclination_m101 = 18

gamma_ngc891 = rvt_boost(inclination_ngc891)
gamma_m101 = rvt_boost(inclination_m101)

divergence_ngc891 = norm_divergence(inclination_ngc891)
divergence_m101 = norm_divergence(inclination_m101)

# Erstelle eine 3D-Figur mit drei Subplots
fig = plt.figure(figsize=(18, 12))

# Subplot 1: Faltung für NGC 891
ax1 = fig.add_subplot(131, projection='3d')
for n in range(n_steps + 1):
    x, y, z = usk_position(n, theta_grid, phi_grid, gamma_ngc891)
    ax1.plot_surface(x, y, z, alpha=0.7, color=plt.cm.Blues(divergence_ngc891), rstride=5, cstride=5, label=f'NGC 891')
ax1.set_title('Faltung (NGC 891)')

# Subplot 2: Faltung für M101
ax2 = fig.add_subplot(132, projection='3d')
for n in range(n_steps + 1):
    x, y, z = usk_position(n, theta_grid, phi_grid, gamma_m101)
    ax2.plot_surface(x, y, z, alpha=0.7, color=plt.cm.Oranges(divergence_m101), rstride=5, cstride=5, label=f'M101')
ax2.set_title('Faltung (M101)')

# Subplot 3: Subtraktion der Faltungseffekte von NGC 891 und M101
ax3 = fig.add_subplot(133, projection='3d')
for n in range(n_steps + 1):
    x1, y1, z1 = usk_position(n, theta_grid, phi_grid, gamma_ngc891)
    x2, y2, z2 = usk_position(n, theta_grid, phi_grid, gamma_m101)
    # Subtraktion der Faltungseffekte
    ax3.plot_surface(x1 - x2, y1 - y2, z1 - z2, alpha=0.7, color=plt.cm.Greens(0.5), rstride=5, cstride=5, label=f'Subtraktion')
ax3.set_title('Subtraktion der Faltungseffekte')

# Zeichne die Achsen für die 90°, 270° Projektionen und die 45°-Deklination in allen drei Subplots
max_range = 1.2 * R
for ax in [ax1, ax2, ax3]:
    ax.plot([0, 0], [0, 0], [0, max_range], 'k--', linewidth=2, label='90° (Top)')
    ax.plot([0, 0], [0, 0], [0, -max_range], 'r--', linewidth=2, label='270° (Underside)')

    # Zeichne die 45°-Deklinationsebene
    u = np.linspace(-2 * max_range, 2 * max_range, 2)
    v = np.linspace(-2 * max_range, 2 * max_range, 2)
    x_45 = u
    y_45 = v
    z_45 = np.zeros_like(u)
    ax.plot_surface(np.outer(x_45, np.ones_like(v)), np.outer(y_45, np.ones_like(u)), np.outer(z_45, np.ones_like(u)),
                    alpha=0.2, color='green', label='45° Deklinationsebene')

    # Zeichne die 45°-Deklinationslinie in der xy-Ebene
    ax.plot([0, 2 * max_range * np.cos(np.radians(45))], [0, 2 * max_range * np.sin(np.radians(45))], [0, 0], 'g-', linewidth=2, label='45° (Deklination)')

    ax.set_xlabel('X')
    ax.set_ylabel('Y')
    ax.set_zlabel('Z')
    ax.legend(loc='upper right')

plt.tight_layout()
plt.show()

# Ausgabe der Ergebnisse
print("Gamma-Werte und Divergenzen:")
print(f"NGC 891 (85°): Gamma = {gamma_ngc891:.3f}, Divergenz = {divergence_ngc891:.3f}")
print(f"M101 (18°): Gamma = {gamma_m101:.3f}, Divergenz = {divergence_m101:.3f}")

import numpy as np
import matplotlib.pyplot as plt

# RVT-Boost-Faktor als Funktion des Inklinationswinkels
def rvt_boost(i_deg):
    i_rad = np.radians(i_deg)
    return 1 + 0.8 * np.sin(i_rad)

# Scheinhare Masse und Durchmesser
def apparent_mass_diameter(gamma):
    mass_factor = gamma
    diameter_factor = 1 / gamma
    return mass_factor, diameter_factor

# Projizierte Fläche
def projected_area(gamma):
    return (1 / gamma) ** 2

# Inklinationswinkel
inclinations = np.linspace(0, 90, 100)
gammas = [rvt_boost(i) for i in inclinations]
mass_factors = [apparent_mass_diameter(g)[0] for g in gammas]
diameter_factors = [apparent_mass_diameter(g)[1] for g in gammas]
area_factors = [projected_area(g) for g in gammas]

# Plot
fig, ax = plt.subplots(figsize=(12, 6))
ax.plot(inclinations, mass_factors, label='Scheinhare Masse ($M_{scheinbar}/M_{tatsächlich}$)', color='blue')
ax.plot(inclinations, diameter_factors, label='Scheinbarer Durchmesser ($D_{scheinbar}/D_{tatsächlich}$)', color='orange')
ax.plot(inclinations, area_factors, label='Projizierte Fläche ($A_{proj}/A_{tatsächlich}$)', color='green')

# Markiere NGC 891 und M101
ax.axvline(x=85, color='blue', linestyle='--', alpha=0.5, label='NGC 891 (85°)')
ax.axvline(x=18, color='orange', linestyle='--', alpha=0.5, label='M101 (18°)')
ax.text(85, 1.5, ' NGC 891', color='blue')
ax.text(18, 1.1, ' M101', color='orange')

ax.set_xlabel('Inklinationswinkel (Grad)')
ax.set_ylabel('Faktor (scheinbar/tatsächlich)')
ax.set_title('Flächenverzerrung und Massenprojektion in der RVT')
ax.legend()
ax.grid(True)
plt.show()

import numpy as np
import matplotlib.pyplot as plt

# RVT-Boost-Faktor als Funktion des Inklinationswinkels
def rvt_boost(i_deg):
    i_rad = np.radians(i_deg)
    return 1 + 0.8 * np.sin(i_rad)

# Offizielle Daten
M_scheinbar_ngc891 = 5e11  # M☉
M_scheinbar_m101 = 1e12    # M☉
R_scheinbar_ngc891 = 60000  # Lj
R_scheinbar_m101 = 85000   # Lj

# Inklinationswinkel
i_ngc891 = 85
i_m101 = 18

# RVT-Boost-Faktoren
gamma_ngc891 = rvt_boost(i_ngc891)
gamma_m101 = rvt_boost(i_m101)

# RVT-korrigierte Massen und Radien
M_tatsächlich_ngc891 = M_scheinbar_ngc891 * gamma_ngc891
M_tatsächlich_m101 = M_scheinbar_m101 * gamma_m101
R_tatsächlich_ngc891 = R_scheinbar_ngc891 * gamma_ngc891
R_tatsächlich_m101 = R_scheinbar_m101 * gamma_m101

# Flächenverzerrung
A_scheinbar_ngc891 = np.pi * (R_scheinbar_ngc891 * 9.461e15)**2
A_scheinbar_m101 = np.pi * (R_scheinbar_m101 * 9.461e15)**2
A_tatsächlich_ngc891 = np.pi * (R_tatsächlich_ngc891 * 9.461e15)**2
A_tatsächlich_m101 = np.pi * (R_tatsächlich_m101 * 9.461e15)**2

# Ausgabe der Ergebnisse
print("RVT-korrigierte Massen und Radien:")
print(f"NGC 891: M_tatsächlich = {M_tatsächlich_ngc891:.2e} M☉, R_tatsächlich = {R_tatsächlich_ngc891:.0f} Lj")
print(f"M101:   M_tatsächlich = {M_tatsächlich_m101:.2e} M☉, R_tatsächlich = {R_tatsächlich_m101:.0f} Lj")
print(f"Flächenverzerrung NGC 891: A_scheinbar/A_tatsächlich = {A_scheinbar_ngc891/A_tatsächlich_ngc891:.3f}")
print(f"Flächenverzerrung M101:   A_scheinbar/A_tatsächlich = {A_scheinbar_m101/A_tatsächlich_m101:.3f}")

# Visualisierung der Flächenverzerrung
fig, ax = plt.subplots(figsize=(10, 6))
ax.bar(['NGC 891', 'M101'], [A_scheinbar_ngc891/A_tatsächlich_ngc891, A_scheinbar_m101/A_tatsächlich_m101],
        color=['blue', 'orange'], alpha=0.7)
ax.set_ylabel('Flächenverzerrung ($A_{\text{scheinbar}} / A_{\text{tatsächlich}}$)')
ax.set_title('Flächenverzerrung durch RVT-Projektion')
ax.grid(True)
plt.show()

import numpy as np
import matplotlib.pyplot as plt

# RVT-Boost-Faktor als Funktion des Inklinationswinkels
def rvt_boost(i_deg):
    i_rad = np.radians(i_deg)
    return 1 + 0.8 * np.sin(i_rad)

# Rotationsgeschwindigkeit in Abhängigkeit vom tatsächlichen Radius
def rotation_curve(R_tatsächlich, gamma):
    g_tatsächlich = 1  # Normierte Gravitation
    return np.sqrt(g_tatsächlich * R_tatsächlich)

# Tatsächliche Radien (in Lichtjahren)
R_tatsächlich_ngc891 = 107820  # NGC 891
R_tatsächlich_m101 = 105995    # M101

# Radiusbereich für die Visualisierung
R = np.linspace(1, max(R_tatsächlich_ngc891, R_tatsächlich_m101), 100)

# Rotationsgeschwindigkeiten
v_ngc891 = rotation_curve(R, 1) * np.sqrt(R_tatsächlich_ngc891)
v_m101 = rotation_curve(R, 1) * np.sqrt(R_tatsächlich_m101)

# Klassische Rotationskurve (ohne RVT-Korrektur)
v_classic_ngc891 = rotation_curve(R, 1) * np.sqrt(120000 / 2)
v_classic_m101 = rotation_curve(R, 1) * np.sqrt(170000 / 2)

# Plot
fig, ax = plt.subplots(figsize=(10, 6))
ax.plot(R, v_ngc891, label=f'NGC 891 (RVT-korrigiert, $R_{{tatsächlich}}={R_tatsächlich_ngc891}$ Lj)', color='blue')
ax.plot(R, v_m101, label=f'M101 (RVT-korrigiert, $R_{{tatsächlich}}={R_tatsächlich_m101}$ Lj)', color='orange')
ax.plot(R, v_classic_ngc891, label='NGC 891 (klassisch, $R_{scheinbar}=60.000$ Lj)', linestyle='--', color='lightblue')
ax.plot(R, v_classic_m101, label='M101 (klassisch, $R_{scheinbar}=85.000$ Lj)', linestyle='--', color='bisque')

ax.set_xlabel('Radius $R$ (Lichtjahre)')
ax.set_ylabel('Rotationsgeschwindigkeit $v_{rot}$ (normiert)')
ax.set_title('RVT-korrigierte Rotationskurven für NGC 891 und M101')
ax.legend()
ax.grid(True)
plt.show()

import numpy as np
import matplotlib.pyplot as plt

# RVT-Konstante
C_RVT = 0.8

# RVT-Boost-Faktor als Funktion des Inklinationswinkels
def rvt_boost(i_deg):
    i_rad = np.radians(i_deg)
    return 1 + C_RVT * np.sin(i_rad)

# Inklinationswinkel
i_ngc891 = 85
i_m101 = 18

# RVT-Boost-Faktoren
gamma_ngc891 = rvt_boost(i_ngc891)
gamma_m101 = rvt_boost(i_m101)

# RVT-korrigierte Massen und Radien
M_tatsächlich_ngc891 = 9e11  # M☉
M_tatsächlich_m101 = 1.25e12  # M☉
R_tatsächlich_ngc891 = 107820  # Lj
R_tatsächlich_m101 = 105995   # Lj

# Umrechnung in Meter und kg
M_sun_kg = 1.989e30  # Masse der Sonne in kg
R_tatsächlich_ngc891_m = R_tatsächlich_ngc891 * 9.461e15  # Lj in m
R_tatsächlich_m101_m = R_tatsächlich_m101 * 9.461e15  # Lj in m
M_tatsächlich_ngc891_kg = M_tatsächlich_ngc891 * M_sun_kg
M_tatsächlich_m101_kg = M_tatsächlich_m101 * M_sun_kg

# Radiusbereich für die Simulation
r = np.logspace(np.log10(1e15), np.log10(max(R_tatsächlich_ngc891_m, R_tatsächlich_m101_m)), 1000)

# Rotationsgeschwindigkeit mit RVT-Boost-Faktor
def rotation_velocity(r, M_0, gamma):
    return np.sqrt((G * M_0 * gamma) / r)

# Berechnung der Rotationsgeschwindigkeiten
v_ngc891 = rotation_velocity(r, M_tatsächlich_ngc891_kg, gamma_ngc891)
v_m101 = rotation_velocity(r, M_tatsächlich_m101_kg, gamma_m101)

# Plot der Rotationsgeschwindigkeiten (logarithmisch)
fig, ax = plt.subplots(figsize=(10, 6))
ax.loglog(r / 9.461e15, v_ngc891 / 1000, label=f'NGC 891 ($C_{{RVT}}={C_RVT}$, $\\gamma_{{RVT}}={gamma_ngc891:.3f}$)', color='blue')
ax.loglog(r / 9.461e15, v_m101 / 1000, label=f'M101 ($C_{{RVT}}={C_RVT}$, $\\gamma_{{RVT}}={gamma_m101:.3f}$)', color='orange')
ax.axhline(y=c / 1000, color='red', linestyle='--', label='Lichtgeschwindigkeit $c$')

ax.set_xlabel('Radius $r$ (Lichtjahre)')
ax.set_ylabel('Rotationsgeschwindigkeit $v_{rot}$ (km/s)')
ax.set_title('Logarithmische RVT-korrigierte Rotationskurven mit $C_{RVT}$')
ax.legend()
ax.grid(True, which="both", ls="-")

plt.tight_layout()
plt.show()

import numpy as np
import matplotlib.pyplot as plt

# Konstanten
G = 6.67430e-11  # Gravitationskonstante (m^3 kg^-1 s^-2)
c = 299792458     # Lichtgeschwindigkeit (m/s)
M_sun_kg = 1.989e30  # Masse der Sonne in kg

# RVT-korrigierte Massen und Radien
M_tatsächlich_ngc891 = 9e11  # M☉
M_tatsächlich_m101 = 1.25e12  # M☉
R_tatsächlich_ngc891 = 107820  # Lj
R_tatsächlich_m101 = 105995   # Lj

# Umrechnung in Meter und kg
R_tatsächlich_ngc891_m = R_tatsächlich_ngc891 * 9.461e15  # Lj in m
R_tatsächlich_m101_m = R_tatsächlich_m101 * 9.461e15  # Lj in m
M_tatsächlich_ngc891_kg = M_tatsächlich_ngc891 * M_sun_kg
M_tatsächlich_m101_kg = M_tatsächlich_m101 * M_sun_kg

# Radiusbereich für die Simulation
r = np.linspace(1e15, max(R_tatsächlich_ngc891_m, R_tatsächlich_m101_m), 1000)

# Rotationsgeschwindigkeit OHNE RVT-Boost-Faktor
def rotation_velocity(r, M_0):
    return np.sqrt(G * M_0 / r)

# Berechnung der RVT-korrigierten Rotationsgeschwindigkeiten
v_ngc891 = rotation_velocity(r, M_tatsächlich_ngc891_kg)
v_m101 = rotation_velocity(r, M_tatsächlich_m101_kg)

# Plot der RVT-korrigierten Rotationsgeschwindigkeiten mit logarithmischer y-Achse
fig, ax = plt.subplots(figsize=(10, 6))
ax.semilogy(r / 9.461e15, v_ngc891 / 1000, label=f'NGC 891 (RVT-korrigiert, $M_{{tatsächlich}}={M_tatsächlich_ngc891:.2e}$ $M_{{\\odot}}$)', color='blue')
ax.semilogy(r / 9.461e15, v_m101 / 1000, label=f'M101 (RVT-korrigiert, $M_{{tatsächlich}}={M_tatsächlich_m101:.2e}$ $M_{{\\odot}}$)', color='orange')
ax.axhline(y=c / 1000, color='red', linestyle='--', label='Lichtgeschwindigkeit $c$')

ax.set_xlabel('Radius $r$ (Lichtjahre)')
ax.set_ylabel('Rotationsgeschwindigkeit $v_{rot}$ (km/s)')
ax.set_title('RVT-korrigierte Rotationsgeschwindigkeiten (logarithmische y-Achse)')
ax.legend()
ax.grid(True)

plt.tight_layout()
plt.show()

import numpy as np
import matplotlib.pyplot as plt
from mpl_toolkits.mplot3d import Axes3D

# Konstanten
G = 6.67430e-11  # Gravitationskonstante (m^3 kg^-1 s^-2)
c = 299792458     # Lichtgeschwindigkeit (m/s)
M_sun_kg = 1.989e30  # Masse der Sonne in kg

# RVT-korrigierte Massen und Radien
M_tatsächlich_ngc891 = 9e11  # M☉
M_tatsächlich_m101 = 1.25e12  # M☉
R_tatsächlich_ngc891 = 107820  # Lj
R_tatsächlich_m101 = 105995   # Lj

# Umrechnung in Meter und kg
R_tatsächlich_ngc891_m = R_tatsächlich_ngc891 * 9.461e15  # Lj in m
R_tatsächlich_m101_m = R_tatsächlich_m101 * 9.461e15  # Lj in m
M_tatsächlich_ngc891_kg = M_tatsächlich_ngc891 * M_sun_kg
M_tatsächlich_m101_kg = M_tatsächlich_m101 * M_sun_kg

# Radiusbereich für die Simulation
r = np.logspace(np.log10(1e15), np.log10(max(R_tatsächlich_ngc891_m, R_tatsächlich_m101_m)), 100)

# Rotationsgeschwindigkeit OHNE RVT-Boost-Faktor
def rotation_velocity(r, M_0):
    return np.sqrt(G * M_0 / r)

# Berechnung der Rotationsgeschwindigkeiten
v_ngc891 = rotation_velocity(r, M_tatsächlich_ngc891_kg)
v_m101 = rotation_velocity(r, M_tatsächlich_m101_kg)

# Mittelwert und Maximalwert der Rotationsgeschwindigkeiten
mittelwert_v_ngc891 = np.mean(v_ngc891)
maxwert_v_ngc891 = np.max(v_ngc891)
mittelwert_v_m101 = np.mean(v_m101)
maxwert_v_m101 = np.max(v_m101)

print(f"Mittelwert der Rotationsgeschwindigkeit für NGC 891: {mittelwert_v_ngc891 / 1000:.2f} km/s")
print(f"Maximalwert der Rotationsgeschwindigkeit für NGC 891: {maxwert_v_ngc891 / 1000:.2f} km/s")
print(f"Mittelwert der Rotationsgeschwindigkeit für M101: {mittelwert_v_m101 / 1000:.2f} km/s")
print(f"Maximalwert der Rotationsgeschwindigkeit für M101: {maxwert_v_m101 / 1000:.2f} km/s")

# 3D-Plot der Rotationsgeschwindigkeiten
fig1 = plt.figure(figsize=(12, 8))
ax1 = fig1.add_subplot(111, projection='3d')

# Radius und Masse als Gitter für die 3D-Darstellung
R_grid, M_grid = np.meshgrid(r, np.linspace(min(M_tatsächlich_ngc891_kg, M_tatsächlich_m101_kg),
                                             max(M_tatsächlich_ngc891_kg, M_tatsächlich_m101_kg), 10))

# Rotationsgeschwindigkeit für das Gitter
V_grid = np.sqrt(G * M_grid / R_grid)

# Logarithmische Darstellung der Rotationsgeschwindigkeit
V_grid_log = np.log10(V_grid)

# 3D-Oberflächenplot mit logarithmischer z-Achse
surf1 = ax1.plot_surface(R_grid / 9.461e15, M_grid / M_sun_kg, V_grid_log, cmap='viridis', alpha=0.8)

# Spezifische Kurven für NGC 891 und M101
ax1.plot(r / 9.461e15, np.full_like(r, M_tatsächlich_ngc891), np.log10(v_ngc891), color='blue', linewidth=3, label='NGC 891')
ax1.plot(r / 9.461e15, np.full_like(r, M_tatsächlich_m101), np.log10(v_m101), color='orange', linewidth=3, label='M101')

ax1.set_xlabel('Radius $r$ (Lichtjahre)')
ax1.set_ylabel('Masse $M$ ($M_{\\odot}$)')
ax1.set_zlabel('log$_{10}$(Rotationsgeschwindigkeit $v_{rot}$ (km/s))')
ax1.set_title('3D-Darstellung der RVT-korrigierten Rotationsgeschwindigkeiten (logarithmische z-Achse)')
ax1.legend()

# Farbbar für die z-Achse
fig1.colorbar(surf1, shrink=0.5, aspect=5, label='log$_{10}$(Rotationsgeschwindigkeit $v_{rot}$ (km/s))')

# USK-Sphäre
fig2 = plt.figure(figsize=(12, 8))
ax2 = fig2.add_subplot(111, projection='3d')

# Parameter für die USK-Sphäre
R = 1  # Radius der Sphäre
alpha = 0.5  # Faltungsintensität
p = 2  # Projectionsexponent
n_steps = 10  # Anzahl der Faltungsschritte

# Sphärische Koordinaten
theta = np.linspace(0, np.pi, 50)
phi = np.linspace(0, 2 * np.pi, 50)
theta_grid, phi_grid = np.meshgrid(theta, phi)

# Faltung der Sphäre
def usk_position(n, theta, phi):
    xi = 1 / (1 + alpha * n**p)
    r = R * xi
    x = r * np.sin(theta_grid) * np.cos(phi_grid)
    y = r * np.sin(theta_grid) * np.sin(phi_grid)
    z = r * np.cos(theta_grid)
    return x, y, z

# Mittelwert und Maximalwert der Rotationsgeschwindigkeiten als y-Werte
y_mittelwert = np.mean([mittelwert_v_ngc891, mittelwert_v_m101]) / 1000
y_maxwert = np.max([maxwert_v_ngc891, maxwert_v_m101]) / 1000

# Plot der USK-Sphäre
for n in range(n_steps + 1):
    x, y, z = usk_position(n, theta_grid, phi_grid)
    ax2.plot_surface(x, y, z, alpha=0.3, color=plt.cm.viridis(n / n_steps), rstride=5, cstride=5)

# Mittelwert und Maximalwert als Punkte in der USK-Sphäre
ax2.scatter(0, y_mittelwert, 0, color='red', s=100, label='Mittelwert')
ax2.scatter(0, y_maxwert, 0, color='blue', s=100, label='Maximalwert')

ax2.set_xlabel('X')
ax2.set_ylabel('Mittelwert/Maximalwert der Rotationsgeschwindigkeit (km/s)')
ax2.set_zlabel('Z')
ax2.set_title('3D-USK-Sphäre mit Mittelwert und Maximalwert der Rotationsgeschwindigkeiten')
ax2.legend()

plt.tight_layout()
plt.show()

import numpy as np
import matplotlib.pyplot as plt
from mpl_toolkits.mplot3d import Axes3D

# Konstanten
G = 6.67430e-11  # Gravitationskonstante (m^3 kg^-1 s^-2)
c = 299792458     # Lichtgeschwindigkeit (m/s)
M_sun_kg = 1.989e30  # Masse der Sonne in kg

# RVT-korrigierte Massen und Radien
M_tatsächlich_ngc891 = 9e11   # M☉
M_tatsächlich_m101 = 1.25e12  # M☉
R_tatsächlich_ngc891 = 107820 # Lj
R_tatsächlich_m101 = 105995  # Lj

# Umrechnung in Meter und kg
R_tatsächlich_ngc891_m = R_tatsächlich_ngc891 * 9.461e15  # Lj in m
R_tatsächlich_m101_m = R_tatsächlich_m101 * 9.461e15  # Lj in m
M_tatsächlich_ngc891_kg = M_tatsächlich_ngc891 * M_sun_kg
M_tatsächlich_m101_kg = M_tatsächlich_m101 * M_sun_kg

# Radiusbereich für die Simulation
r = np.linspace(1e15, max(R_tatsächlich_ngc891_m, R_tatsächlich_m101_m), 1000)

# Rotationsgeschwindigkeit OHNE RVT-Boost-Faktor
def rotation_velocity(r, M_0):
    return np.sqrt(G * M_0 / r)

# Berechnung der Rotationsgeschwindigkeiten
v_ngc891 = rotation_velocity(r, M_tatsächlich_ngc891_kg)
v_m101 = rotation_velocity(r, M_tatsächlich_m101_kg)

# Mittelwert, Maximalwert und Minimalwert der Rotationsgeschwindigkeiten
mittelwert_v_ngc891 = np.mean(v_ngc891)
maxwert_v_ngc891 = np.max(v_ngc891)
minwert_v_ngc891 = np.min(v_ngc891)

mittelwert_v_m101 = np.mean(v_m101)
maxwert_v_m101 = np.max(v_m101)
minwert_v_m101 = np.min(v_m101)

# Rotationsgeschwindigkeit beim maximalen Radius
max_radius = max(R_tatsächlich_ngc891_m, R_tatsächlich_m101_m)
v_max_radius_ngc891 = rotation_velocity(max_radius, M_tatsächlich_ngc891_kg)
v_max_radius_m101 = rotation_velocity(max_radius, M_tatsächlich_m101_kg)

print(f"NGC 891 - Mittelwert: {mittelwert_v_ngc891 / 1000:.2f} km/s, Maximalwert: {maxwert_v_ngc891 / 1000:.2f} km/s, Minimalwert: {minwert_v_ngc891 / 1000:.2f} km/s")
print(f"M101   - Mittelwert: {mittelwert_v_m101 / 1000:.2f} km/s, Maximalwert: {maxwert_v_m101 / 1000:.2f} km/s, Minimalwert: {minwert_v_m101 / 1000:.2f} km/s")
print(f"NGC 891 - Rotationsgeschwindigkeit bei max. Radius: {v_max_radius_ngc891 / 1000:.2f} km/s")
print(f"M101   - Rotationsgeschwindigkeit bei max. Radius: {v_max_radius_m101 / 1000:.2f} km/s")

# Plot der RVT-korrigierten Rotationsgeschwindigkeiten mit logarithmischer y-Achse
fig1, ax1 = plt.subplots(figsize=(12, 8))
ax1.semilogy(r / 9.461e15, v_ngc891 / 1000, label=fr'NGC 891 ($M={M_tatsächlich_ngc891:.1e}$ $M_{{\odot}}$)', color='blue')
ax1.semilogy(r / 9.461e15, v_m101 / 1000, label=fr'M101 ($M={M_tatsächlich_m101:.1e}$ $M_{{\odot}}$)', color='orange')
ax1.axhline(y=c / 1000, color='red', linestyle='--', label=r'Lichtgeschwindigkeit $c$')

ax1.set_xlabel(r'Radius $r$ (Lichtjahre)')
ax1.set_ylabel(r'Rotationsgeschwindigkeit $v_{rot}$ (km/s)')
ax1.set_title(r'RVT-korrigierte Rotationsgeschwindigkeiten (logarithmische y-Achse)')
ax1.legend()
ax1.grid(True, which="both", ls="-")

# 3D-Plot der konstanten Rotationsgeschwindigkeit beim maximalen Radius
fig2 = plt.figure(figsize=(12, 8))
ax2 = fig2.add_subplot(111, projection='3d')

# Radius und logarithmische Rotationsgeschwindigkeit
R_grid, log_V_grid_ngc891 = np.meshgrid(r / 9.461e15, np.log10(v_ngc891 / 1000))
_, log_V_grid_m101 = np.meshgrid(r / 9.461e15, np.log10(v_m101 / 1000))

# Konstante Rotationsgeschwindigkeit beim maximalen Radius
const_v_max_ngc891 = np.full_like(R_grid, v_max_radius_ngc891 / 1000)
const_v_max_m101 = np.full_like(R_grid, v_max_radius_m101 / 1000)

# Plot der Oberflächen
ax2.plot_surface(R_grid, log_V_grid_ngc891, const_v_max_ngc891, alpha=0.5, color='blue', label='NGC 891')
ax2.plot_surface(R_grid, log_V_grid_m101, const_v_max_m101, alpha=0.5, color='orange', label='M101')

ax2.set_xlabel(r'Radius $r$ (Lichtjahre)')
ax2.set_ylabel(r'$\log_{10}$(Rotationsgeschwindigkeit $v_{rot}$ (km/s))')
ax2.set_zlabel(r'Konstante $v_{rot}$ bei max. Radius (km/s)')
ax2.set_title(r'3D-Darstellung der konstanten Rotationsgeschwindigkeit bei max. Radius')
ax2.legend()

plt.tight_layout()
plt.show()

import numpy as np
import matplotlib.pyplot as plt
from mpl_toolkits.mplot3d import Axes3D

# Konstanten
G = 6.67430e-11  # Gravitationskonstante (m^3 kg^-1 s^-2)
c = 299792458     # Lichtgeschwindigkeit (m/s)
M_sun_kg = 1.989e30  # Masse der Sonne in kg

# RVT-korrigierte Massen und Radien
M_tatsächlich_ngc891 = 9e11  # M☉
M_tatsächlich_m101 = 1.25e12  # M☉
R_tatsächlich_ngc891 = 107820  # Lj
R_tatsächlich_m101 = 105995   # Lj

# Umrechnung in Meter und kg
R_tatsächlich_ngc891_m = R_tatsächlich_ngc891 * 9.461e15  # Lj in m
R_tatsächlich_m101_m = R_tatsächlich_m101 * 9.461e15  # Lj in m
M_tatsächlich_ngc891_kg = M_tatsächlich_ngc891 * M_sun_kg
M_tatsächlich_m101_kg = M_tatsächlich_m101 * M_sun_kg

# Radiusbereich für die Simulation
r = np.logspace(np.log10(1e15), np.log10(max(R_tatsächlich_ngc891_m, R_tatsächlich_m101_m)), 100)

# Rotationsgeschwindigkeit OHNE RVT-Boost-Faktor
def rotation_velocity(r, M_0):
    return np.sqrt(G * M_0 / r)

# Berechnung der Rotationsgeschwindigkeiten
v_ngc891 = rotation_velocity(r, M_tatsächlich_ngc891_kg)
v_m101 = rotation_velocity(r, M_tatsächlich_m101_kg)

# Mittelwert und Maximalwert der Rotationsgeschwindigkeiten
mittelwert_v_ngc891 = np.mean(v_ngc891)
maxwert_v_ngc891 = np.max(v_ngc891)
mittelwert_v_m101 = np.mean(v_m101)
maxwert_v_m101 = np.max(v_m101)

print(f"Mittelwert der Rotationsgeschwindigkeit für NGC 891: {mittelwert_v_ngc891 / 1000:.2f} km/s")
print(f"Maximalwert der Rotationsgeschwindigkeit für NGC 891: {maxwert_v_ngc891 / 1000:.2f} km/s")
print(f"Mittelwert der Rotationsgeschwindigkeit für M101: {mittelwert_v_m101 / 1000:.2f} km/s")
print(f"Maximalwert der Rotationsgeschwindigkeit für M101: {maxwert_v_m101 / 1000:.2f} km/s")

# 3D-Plot der Rotationsgeschwindigkeiten
fig1 = plt.figure(figsize=(12, 8))
ax1 = fig1.add_subplot(111, projection='3d')

# Radius und Masse als Gitter für die 3D-Darstellung
R_grid, M_grid = np.meshgrid(r, np.linspace(min(M_tatsächlich_ngc891_kg, M_tatsächlich_m101_kg),
                                             max(M_tatsächlich_ngc891_kg, M_tatsächlich_m101_kg), 10))

# Rotationsgeschwindigkeit für das Gitter
V_grid = np.sqrt(G * M_grid / R_grid)

# Logarithmische Darstellung der Rotationsgeschwindigkeit
V_grid_log = np.log10(V_grid)

# 3D-Oberflächenplot mit logarithmischer z-Achse
surf1 = ax1.plot_surface(R_grid / 9.461e15, M_grid / M_sun_kg, V_grid_log, cmap='viridis', alpha=0.8)

# Spezifische Kurven für NGC 891 und M101
ax1.plot(r / 9.461e15, np.full_like(r, M_tatsächlich_ngc891), np.log10(v_ngc891), color='blue', linewidth=3, label='NGC 891')
ax1.plot(r / 9.461e15, np.full_like(r, M_tatsächlich_m101), np.log10(v_m101), color='orange', linewidth=3, label='M101')

ax1.set_xlabel('Radius $r$ (Lichtjahre)')
ax1.set_ylabel('Masse $M$ ($M_{\\odot}$)')
ax1.set_zlabel('log$_{10}$(Rotationsgeschwindigkeit $v_{rot}$ (km/s))')
ax1.set_title('3D-Darstellung der RVT-korrigierten Rotationsgeschwindigkeiten (logarithmische z-Achse)')
ax1.legend()

# Farbbar für die z-Achse
fig1.colorbar(surf1, shrink=0.5, aspect=5, label='log$_{10}$(Rotationsgeschwindigkeit $v_{rot}$ (km/s))')

# USK-Sphäre
fig2 = plt.figure(figsize=(12, 8))
ax2 = fig2.add_subplot(111, projection='3d')

# Parameter für die USK-Sphäre
R = 1  # Radius der Sphäre
alpha = 0.5  # Faltungsintensität
p = 2  # Projectionsexponent
n_steps = 10  # Anzahl der Faltungsschritte

# Sphärische Koordinaten
theta = np.linspace(0, np.pi, 50)
phi = np.linspace(0, 2 * np.pi, 50)
theta_grid, phi_grid = np.meshgrid(theta, phi)

# Faltung der Sphäre
def usk_position(n, theta, phi, gamma):
    xi = 1 / (1 + alpha * n**p) * gamma
    r = R * xi
    x = r * np.sin(theta) * np.cos(phi)
    y = r * np.sin(theta) * np.sin(phi)
    z = r * np.cos(theta)
    return x, y, z

# RVT-Boost-Faktor als Funktion des Inklinationswinkels i
def rvt_boost(i_deg):
    i_rad = np.radians(i_deg)
    return 1 + 0.8 * np.sin(i_rad)

# Inklinationswinkel
inclination_ngc891 = 85
inclination_m101 = 18

# RVT-Boost-Faktoren
gamma_ngc891 = rvt_boost(inclination_ngc891)
gamma_m101 = rvt_boost(inclination_m101)

# Mittelwert und Maximalwert der Rotationsgeschwindigkeiten als y-Werte
y_mittelwert = np.mean([mittelwert_v_ngc891, mittelwert_v_m101]) / 1000
y_maxwert = np.max([maxwert_v_ngc891, maxwert_v_m101]) / 1000

# Plot der USK-Sphäre für NGC 891 und M101
for n in range(n_steps + 1):
    x, y, z = usk_position(n, theta_grid, phi_grid, gamma_ngc891)
    ax2.plot_surface(x, y, z, alpha=0.3, color=plt.cm.Blues(0.5), rstride=5, cstride=5, label='NGC 891' if n == 0 else "")

    x, y, z = usk_position(n, theta_grid, phi_grid, gamma_m101)
    ax2.plot_surface(x, y, z, alpha=0.3, color=plt.cm.Oranges(0.5), rstride=5, cstride=5, label='M101' if n == 0 else "")

# Mittelwert und Maximalwert als Punkte in der USK-Sphäre
ax2.scatter(0, y_mittelwert, 0, color='red', s=100, label='Mittelwert')
ax2.scatter(0, y_maxwert, 0, color='blue', s=100, label='Maximalwert')

ax2.set_xlabel('X')
ax2.set_ylabel('Mittelwert/Maximalwert der Rotationsgeschwindigkeit (km/s)')
ax2.set_zlabel('Z')
ax2.set_title('3D-USK-Sphäre mit Mittelwert und Maximalwert der Rotationsgeschwindigkeiten')
ax2.legend()

plt.tight_layout()
plt.show()

import numpy as np
import matplotlib.pyplot as plt
from mpl_toolkits.mplot3d import Axes3D

# Konstanten
G = 6.67430e-11  # Gravitationskonstante (m^3 kg^-1 s^-2)
c = 299792458     # Lichtgeschwindigkeit (m/s)
M_sun_kg = 1.989e30  # Masse der Sonne in kg

# RVT-korrigierte Massen und Radien
M_tatsächlich_ngc891 = 9e11  # M☉
M_tatsächlich_m101 = 1.25e12  # M☉
R_tatsächlich_ngc891 = 107820  # Lj
R_tatsächlich_m101 = 105995   # Lj

# Umrechnung in Meter und kg
R_tatsächlich_ngc891_m = R_tatsächlich_ngc891 * 9.461e15  # Lj in m
R_tatsächlich_m101_m = R_tatsächlich_m101 * 9.461e15  # Lj in m
M_tatsächlich_ngc891_kg = M_tatsächlich_ngc891 * M_sun_kg
M_tatsächlich_m101_kg = M_tatsächlich_m101 * M_sun_kg

# Radiusbereich für die Simulation
r = np.logspace(np.log10(1e15), np.log10(max(R_tatsächlich_ngc891_m, R_tatsächlich_m101_m)), 100)

# Rotationsgeschwindigkeit OHNE RVT-Boost-Faktor
def rotation_velocity(r, M_0):
    return np.sqrt(G * M_0 / r)

# Berechnung der Rotationsgeschwindigkeiten
v_ngc891 = rotation_velocity(r, M_tatsächlich_ngc891_kg)
v_m101 = rotation_velocity(r, M_tatsächlich_m101_kg)

# Mittelwert und Maximalwert der Rotationsgeschwindigkeiten
mittelwert_v_ngc891 = np.mean(v_ngc891)
maxwert_v_ngc891 = np.max(v_ngc891)
mittelwert_v_m101 = np.mean(v_m101)
maxwert_v_m101 = np.max(v_m101)

print(f"Mittelwert der Rotationsgeschwindigkeit für NGC 891: {mittelwert_v_ngc891 / 1000:.2f} km/s")
print(f"Maximalwert der Rotationsgeschwindigkeit für NGC 891: {maxwert_v_ngc891 / 1000:.2f} km/s")
print(f"Mittelwert der Rotationsgeschwindigkeit für M101: {mittelwert_v_m101 / 1000:.2f} km/s")
print(f"Maximalwert der Rotationsgeschwindigkeit für M101: {maxwert_v_m101 / 1000:.2f} km/s")

# 3D-Plot der Rotationsgeschwindigkeiten
fig1 = plt.figure(figsize=(12, 8))
ax1 = fig1.add_subplot(111, projection='3d')

# Radius und Masse als Gitter für die 3D-Darstellung
R_grid, M_grid = np.meshgrid(r, np.linspace(min(M_tatsächlich_ngc891_kg, M_tatsächlich_m101_kg),
                                             max(M_tatsächlich_ngc891_kg, M_tatsächlich_m101_kg), 10))

# Rotationsgeschwindigkeit für das Gitter
V_grid = np.sqrt(G * M_grid / R_grid)

# Logarithmische Darstellung der Rotationsgeschwindigkeit
V_grid_log = np.log10(V_grid)

# 3D-Oberflächenplot mit logarithmischer z-Achse
surf1 = ax1.plot_surface(R_grid / 9.461e15, M_grid / M_sun_kg, V_grid_log, cmap='viridis', alpha=0.8)

# Spezifische Kurven für NGC 891 und M101
ax1.plot(r / 9.461e15, np.full_like(r, M_tatsächlich_ngc891), np.log10(v_ngc891), color='blue', linewidth=3, label='NGC 891')
ax1.plot(r / 9.461e15, np.full_like(r, M_tatsächlich_m101), np.log10(v_m101), color='orange', linewidth=3, label='M101')

ax1.set_xlabel('Radius $r$ (Lichtjahre)')
ax1.set_ylabel('Masse $M$ ($M_{\\odot}$)')
ax1.set_zlabel('log$_{10}$(Rotationsgeschwindigkeit $v_{rot}$ (km/s))')
ax1.set_title('3D-Darstellung der RVT-korrigierten Rotationsgeschwindigkeiten (logarithmische z-Achse)')
ax1.legend()

# Farbbar für die z-Achse
fig1.colorbar(surf1, shrink=0.5, aspect=5, label='log$_{10}$(Rotationsgeschwindigkeit $v_{rot}$ (km/s))')

# USK-Sphäre mit 5 Faltungsschritten
fig2 = plt.figure(figsize=(12, 8))
ax2 = fig2.add_subplot(111, projection='3d')

# Parameter für die USK-Sphäre
R = 1  # Radius der Sphäre
alpha = 0.5  # Faltungsintensität
p = 2  # Projectionsexponent
n_steps = 5  # Anzahl der Faltungsschritte

# Sphärische Koordinaten
theta = np.linspace(0, np.pi, 50)
phi = np.linspace(0, 2 * np.pi, 50)
theta_grid, phi_grid = np.meshgrid(theta, phi)

# Faltung der Sphäre
def usk_position(n, theta, phi, gamma):
    xi = 1 / (1 + alpha * n**p) * gamma
    r = R * xi
    x = r * np.sin(theta) * np.cos(phi)
    y = r * np.sin(theta) * np.sin(phi)
    z = r * np.cos(theta)
    return x, y, z

# RVT-Boost-Faktor als Funktion des Inklinationswinkels i
def rvt_boost(i_deg):
    i_rad = np.radians(i_deg)
    return 1 + 0.8 * np.sin(i_rad)

# Inklinationswinkel
inclination_ngc891 = 85
inclination_m101 = 18

# RVT-Boost-Faktoren
gamma_ngc891 = rvt_boost(inclination_ngc891)
gamma_m101 = rvt_boost(inclination_m101)

# Massenkompression nach dem USK-Modell
def mass_compaction(n, M_0, kappa, q):
    return M_0 + kappa * np.sum(1 / np.arange(1, n + 1)**q)

kappa = 1e10  # Kompressionsfaktor
q = 1.5       # Konvergenzexponent

M_0 = min(M_tatsächlich_ngc891_kg, M_tatsächlich_m101_kg)

# Massenkompression für 5 Faltungsschritte
mass_compaction_values = [mass_compaction(n, M_0, kappa, q) for n in range(1, n_steps + 1)]

# Mittelwert und Maximalwert der Rotationsgeschwindigkeiten als y-Werte
y_mittelwert = np.mean([mittelwert_v_ngc891, mittelwert_v_m101]) / 1000
y_maxwert = np.max([maxwert_v_ngc891, maxwert_v_m101]) / 1000

# Skalierung der Massenkompression auf Mittel- und Maximalwert
mass_compaction_mittelwert = [m / max(mass_compaction_values) * y_mittelwert for m in mass_compaction_values]
mass_compaction_maxwert = [m / max(mass_compaction_values) * y_maxwert for m in mass_compaction_values]

# Plot der USK-Sphäre für NGC 891 und M101
for n in range(1, n_steps + 1):
    x, y, z = usk_position(n, theta_grid, phi_grid, gamma_ngc891)
    ax2.plot_surface(x, mass_compaction_mittelwert[n-1] * np.ones_like(y), z,
                     alpha=0.3, color=plt.cm.Blues(0.5), rstride=5, cstride=5, label='Mittelwert' if n == 1 else "")

    ax2.plot_surface(x, mass_compaction_maxwert[n-1] * np.ones_like(y), z,
                     alpha=0.3, color=plt.cm.Reds(0.5), rstride=5, cstride=5, label='Maximalwert' if n == 1 else "")

ax2.set_xlabel('X')
ax2.set_ylabel('Massenkompression (skaliert auf Mittel-/Maximalwert)')
ax2.set_zlabel('Z')
ax2.set_title('3D-USK-Sphäre mit Massenkompression (5 Faltungsschritte)')
ax2.legend()

plt.tight_layout()
plt.show()

import numpy as np
import matplotlib.pyplot as plt
from mpl_toolkits.mplot3d import Axes3D

# Konstanten
G = 6.67430e-11  # Gravitationskonstante (m^3 kg^-1 s^-2)
c = 299792458     # Lichtgeschwindigkeit (m/s)
M_sun_kg = 1.989e30  # Masse der Sonne in kg

# RVT-korrigierte Massen und Radien
M_tatsächlich_ngc891 = 9e11  # M☉
M_tatsächlich_m101 = 1.25e12  # M☉
R_tatsächlich_ngc891 = 107820  # Lj
R_tatsächlich_m101 = 105995   # Lj

# Umrechnung in Meter und kg
R_tatsächlich_ngc891_m = R_tatsächlich_ngc891 * 9.461e15  # Lj in m
R_tatsächlich_m101_m = R_tatsächlich_m101 * 9.461e15  # Lj in m
M_tatsächlich_ngc891_kg = M_tatsächlich_ngc891 * M_sun_kg
M_tatsächlich_m101_kg = M_tatsächlich_m101 * M_sun_kg

# Radiusbereich für die Simulation
r = np.logspace(np.log10(1e15), np.log10(max(R_tatsächlich_ngc891_m, R_tatsächlich_m101_m)), 100)

# Rotationsgeschwindigkeit OHNE RVT-Boost-Faktor
def rotation_velocity(r, M_0):
    return np.sqrt(G * M_0 / r)

# Berechnung der Rotationsgeschwindigkeiten
v_ngc891 = rotation_velocity(r, M_tatsächlich_ngc891_kg)
v_m101 = rotation_velocity(r, M_tatsächlich_m101_kg)

# Mittelwert, Maximalwert und Minimalwert der Rotationsgeschwindigkeiten
mittelwert_v_ngc891 = np.mean(v_ngc891)
maxwert_v_ngc891 = np.max(v_ngc891)
minwert_v_ngc891 = np.min(v_ngc891)

mittelwert_v_m101 = np.mean(v_m101)
maxwert_v_m101 = np.max(v_m101)
minwert_v_m101 = np.min(v_m101)

print(f"Mittelwert der Rotationsgeschwindigkeit für NGC 891: {mittelwert_v_ngc891 / 1000:.2f} km/s")
print(f"Maximalwert der Rotationsgeschwindigkeit für NGC 891: {maxwert_v_ngc891 / 1000:.2f} km/s")
print(f"Minimalwert der Rotationsgeschwindigkeit für NGC 891: {minwert_v_ngc891 / 1000:.2f} km/s")

print(f"Mittelwert der Rotationsgeschwindigkeit für M101: {mittelwert_v_m101 / 1000:.2f} km/s")
print(f"Maximalwert der Rotationsgeschwindigkeit für M101: {maxwert_v_m101 / 1000:.2f} km/s")
print(f"Minimalwert der Rotationsgeschwindigkeit für M101: {minwert_v_m101 / 1000:.2f} km/s")

# 3D-Plot der Rotationsgeschwindigkeiten
fig1 = plt.figure(figsize=(12, 8))
ax1 = fig1.add_subplot(111, projection='3d')

# Radius und Masse als Gitter für die 3D-Darstellung
R_grid, M_grid = np.meshgrid(r, np.linspace(min(M_tatsächlich_ngc891_kg, M_tatsächlich_m101_kg),
                                             max(M_tatsächlich_ngc891_kg, M_tatsächlich_m101_kg), 10))

# Rotationsgeschwindigkeit für das Gitter
V_grid = np.sqrt(G * M_grid / R_grid)

# Logarithmische Darstellung der Rotationsgeschwindigkeit
V_grid_log = np.log10(V_grid)

# 3D-Oberflächenplot mit logarithmischer z-Achse
surf1 = ax1.plot_surface(R_grid / 9.461e15, M_grid / M_sun_kg, V_grid_log, cmap='viridis', alpha=0.8)

# Spezifische Kurven für NGC 891 und M101
ax1.plot(r / 9.461e15, np.full_like(r, M_tatsächlich_ngc891), np.log10(v_ngc891), color='blue', linewidth=3, label='NGC 891')
ax1.plot(r / 9.461e15, np.full_like(r, M_tatsächlich_m101), np.log10(v_m101), color='orange', linewidth=3, label='M101')

ax1.set_xlabel('Radius $r$ (Lichtjahre)')
ax1.set_ylabel('Masse $M$ ($M_{\\odot}$)')
ax1.set_zlabel(r'$\log_{10}$(Rotationsgeschwindigkeit $v_{rot}$ (km/s))')
ax1.set_title('3D-Darstellung der RVT-korrigierten Rotationsgeschwindigkeiten (logarithmische z-Achse)')
ax1.legend()

# Farbbar für die z-Achse
fig1.colorbar(surf1, shrink=0.5, aspect=5, label=r'$\log_{10}$(Rotationsgeschwindigkeit $v_{rot}$ (km/s))')

# USK-Sphäre mit 5 Faltungsschritten
fig2 = plt.figure(figsize=(12, 8))
ax2 = fig2.add_subplot(111, projection='3d')

# Parameter für die USK-Sphäre
R = 1  # Radius der Sphäre
alpha = 0.5  # Faltungsintensität
p = 2  # Projectionsexponent
n_steps = 5  # Anzahl der Faltungsschritte

# Sphärische Koordinaten
theta = np.linspace(0, np.pi, 50)
phi = np.linspace(0, 2 * np.pi, 50)
theta_grid, phi_grid = np.meshgrid(theta, phi)

# Faltung der Sphäre
def usk_position(n, theta, phi, gamma):
    xi = 1 / (1 + alpha * n**p) * gamma
    r = R * xi
    x = r * np.sin(theta) * np.cos(phi)
    y = r * np.sin(theta) * np.sin(phi)
    z = r * np.cos(theta)
    return x, y, z

# RVT-Boost-Faktor als Funktion des Inklinationswinkels i
def rvt_boost(i_deg):
    i_rad = np.radians(i_deg)
    return 1 + 0.8 * np.sin(i_rad)

# Inklinationswinkel
inclination_ngc891 = 85
inclination_m101 = 18

# RVT-Boost-Faktoren
gamma_ngc891 = rvt_boost(inclination_ngc891)
gamma_m101 = rvt_boost(inclination_m101)

# Massenkompression nach dem USK-Modell
def mass_compaction(n, M_0, kappa, q):
    return M_0 + kappa * np.sum(1 / np.arange(1, n + 1)**q)

kappa = 1e10  # Kompressionsfaktor
q = 1.5       # Konvergenzexponent

M_0 = min(M_tatsächlich_ngc891_kg, M_tatsächlich_m101_kg)

# Massenkompression für 5 Faltungsschritte
mass_compaction_values = [mass_compaction(n, M_0, kappa, q) for n in range(1, n_steps + 1)]

# Mittelwert, Maximalwert und Minimalwert der Rotationsgeschwindigkeiten als y-Werte
y_mittelwert = np.mean([mittelwert_v_ngc891, mittelwert_v_m101]) / 1000
y_maxwert = np.max([maxwert_v_ngc891, maxwert_v_m101]) / 1000
y_minwert = np.min([minwert_v_ngc891, minwert_v_m101]) / 1000

# Skalierung der Massenkompression auf Mittel-, Maximal- und Minimalwert
mass_compaction_mittelwert = [m / max(mass_compaction_values) * y_mittelwert for m in mass_compaction_values]
mass_compaction_maxwert = [m / max(mass_compaction_values) * y_maxwert for m in mass_compaction_values]
mass_compaction_minwert = [m / max(mass_compaction_values) * y_minwert for m in mass_compaction_values]

# Plot der USK-Sphäre für NGC 891 und M101
for n in range(1, n_steps + 1):
    x, y, z = usk_position(n, theta_grid, phi_grid, gamma_ngc891)
    ax2.plot_surface(x, mass_compaction_mittelwert[n-1] * np.ones_like(y), z,
                     alpha=0.3, color=plt.cm.Blues(0.5), rstride=5, cstride=5, label='Mittelwert' if n == 1 else "")
    ax2.plot_surface(x, mass_compaction_maxwert[n-1] * np.ones_like(y), z,
                     alpha=0.3, color=plt.cm.Reds(0.7), rstride=5, cstride=5, label='Maximalwert' if n == 1 else "")
    ax2.plot_surface(x, mass_compaction_minwert[n-1] * np.ones_like(y), z,
                     alpha=0.3, color=plt.cm.Greens(0.7), rstride=5, cstride=5, label='Minimalwert' if n == 1 else "")

ax2.set_xlabel('X')
ax2.set_ylabel('Massenkompression (skaliert auf Mittel-/Maximal-/Minimalwert)')
ax2.set_zlabel('Z')
ax2.set_title('3D-USK-Sphäre mit Massenkompression (5 Faltungsschritte)')
ax2.legend()

plt.tight_layout()
plt.show()

import numpy as np
import matplotlib.pyplot as plt
from mpl_toolkits.mplot3d import Axes3D

# Konstanten
G = 6.67430e-11  # Gravitationskonstante (m^3 kg^-1 s^-2)
c = 299792458     # Lichtgeschwindigkeit (m/s)
M_sun_kg = 1.989e30  # Masse der Sonne in kg

# RVT-korrigierte Massen und Radien
M_tatsächlich_ngc891 = 9e11  # M☉
M_tatsächlich_m101 = 1.25e12  # M☉
R_tatsächlich_ngc891 = 107820  # Lj
R_tatsächlich_m101 = 105995   # Lj

# Umrechnung in Meter und kg
R_tatsächlich_ngc891_m = R_tatsächlich_ngc891 * 9.461e15  # Lj in m
R_tatsächlich_m101_m = R_tatsächlich_m101 * 9.461e15  # Lj in m
M_tatsächlich_ngc891_kg = M_tatsächlich_ngc891 * M_sun_kg
M_tatsächlich_m101_kg = M_tatsächlich_m101 * M_sun_kg

# Radiusbereich für die Simulation
r = np.logspace(np.log10(1e15), np.log10(max(R_tatsächlich_ngc891_m, R_tatsächlich_m101_m)), 100)

# Rotationsgeschwindigkeit OHNE RVT-Boost-Faktor
def rotation_velocity(r, M_0):
    return np.sqrt(G * M_0 / r)

# Berechnung der Rotationsgeschwindigkeiten
v_ngc891 = rotation_velocity(r, M_tatsächlich_ngc891_kg)
v_m101 = rotation_velocity(r, M_tatsächlich_m101_kg)

# Mittelwert, Maximalwert und Minimalwert der Rotationsgeschwindigkeiten
mittelwert_v_ngc891 = np.mean(v_ngc891)
maxwert_v_ngc891 = np.max(v_ngc891)
minwert_v_ngc891 = np.min(v_ngc891)

mittelwert_v_m101 = np.mean(v_m101)
maxwert_v_m101 = np.max(v_m101)
minwert_v_m101 = np.min(v_m101)

print(f"Mittelwert der Rotationsgeschwindigkeit für NGC 891: {mittelwert_v_ngc891 / 1000:.2f} km/s")
print(f"Maximalwert der Rotationsgeschwindigkeit für NGC 891: {maxwert_v_ngc891 / 1000:.2f} km/s")
print(f"Minimalwert der Rotationsgeschwindigkeit für NGC 891: {minwert_v_ngc891 / 1000:.2f} km/s")

print(f"Mittelwert der Rotationsgeschwindigkeit für M101: {mittelwert_v_m101 / 1000:.2f} km/s")
print(f"Maximalwert der Rotationsgeschwindigkeit für M101: {maxwert_v_m101 / 1000:.2f} km/s")
print(f"Minimalwert der Rotationsgeschwindigkeit für M101: {minwert_v_m101 / 1000:.2f} km/s")

# 3D-Plot der Rotationsgeschwindigkeiten
fig1 = plt.figure(figsize=(12, 8))
ax1 = fig1.add_subplot(111, projection='3d')

# Radius und Masse als Gitter für die 3D-Darstellung
R_grid, M_grid = np.meshgrid(r, np.linspace(min(M_tatsächlich_ngc891_kg, M_tatsächlich_m101_kg),
                                             max(M_tatsächlich_ngc891_kg, M_tatsächlich_m101_kg), 10))

# Rotationsgeschwindigkeit für das Gitter
V_grid = np.sqrt(G * M_grid / R_grid)

# Logarithmische Darstellung der Rotationsgeschwindigkeit
V_grid_log = np.log10(V_grid)

# 3D-Oberflächenplot mit logarithmischer z-Achse
surf1 = ax1.plot_surface(R_grid / 9.461e15, M_grid / M_sun_kg, V_grid_log, cmap='viridis', alpha=0.8)

# Spezifische Kurven für NGC 891 und M101
ax1.plot(r / 9.461e15, np.full_like(r, M_tatsächlich_ngc891), np.log10(v_ngc891), color='blue', linewidth=3, label='NGC 891')
ax1.plot(r / 9.461e15, np.full_like(r, M_tatsächlich_m101), np.log10(v_m101), color='orange', linewidth=3, label='M101')

ax1.set_xlabel('Radius $r$ (Lichtjahre)')
ax1.set_ylabel('Masse $M$ ($M_{\\odot}$)')
ax1.set_zlabel(r'$\log_{10}$(Rotationsgeschwindigkeit $v_{rot}$ (km/s))')
ax1.set_title('3D-Darstellung der RVT-korrigierten Rotationsgeschwindigkeiten (logarithmische z-Achse)')
ax1.legend()

# Farbbar für die z-Achse
fig1.colorbar(surf1, shrink=0.5, aspect=5, label=r'$\log_{10}$(Rotationsgeschwindigkeit $v_{rot}$ (km/s))')

# USK-Sphäre mit logarithmischen Rotationsgeschwindigkeiten
fig2 = plt.figure(figsize=(12, 8))
ax2 = fig2.add_subplot(111, projection='3d')

# Parameter für die USK-Sphäre
R = 1  # Radius der Sphäre
alpha = 0.5  # Faltungsintensität
p = 2  # Projectionsexponent
n_steps = 5  # Anzahl der Faltungsschritte

# Sphärische Koordinaten
theta = np.linspace(0, np.pi, 50)
phi = np.linspace(0, 2 * np.pi, 50)
theta_grid, phi_grid = np.meshgrid(theta, phi)

# Faltung der Sphäre
def usk_position(n, theta, phi, gamma):
    xi = 1 / (1 + alpha * n**p) * gamma
    r = R * xi
    x = r * np.sin(theta) * np.cos(phi)
    y = r * np.sin(theta) * np.sin(phi)
    z = r * np.cos(theta)
    return x, y, z

# RVT-Boost-Faktor als Funktion des Inklinationswinkels i
def rvt_boost(i_deg):
    i_rad = np.radians(i_deg)
    return 1 + 0.8 * np.sin(i_rad)

# Inklinationswinkel
inclination_ngc891 = 85
inclination_m101 = 18

# RVT-Boost-Faktoren
gamma_ngc891 = rvt_boost(inclination_ngc891)
gamma_m101 = rvt_boost(inclination_m101)

# Mittelwert, Maximalwert und Minimalwert der Rotationsgeschwindigkeiten (logarithmisch)
log_y_mittelwert = np.log10(np.mean([mittelwert_v_ngc891, mittelwert_v_m101]) / 1000)
log_y_maxwert = np.log10(np.max([maxwert_v_ngc891, maxwert_v_m101]) / 1000)
log_y_minwert = np.log10(np.min([minwert_v_ngc891, minwert_v_m101]) / 1000)

# Plot der USK-Sphäre für Minimal-, Mittel- und Maximalwerte der logarithmischen Rotationsgeschwindigkeiten
for n in range(1, n_steps + 1):
    x, y, z = usk_position(n, theta_grid, phi_grid, gamma_ngc891)
    ax2.plot_surface(x, np.full_like(y, log_y_minwert), z, alpha=0.3, color='green', rstride=5, cstride=5, label='Minimalwert' if n == 1 else "")
    ax2.plot_surface(x, np.full_like(y, log_y_mittelwert), z, alpha=0.3, color='blue', rstride=5, cstride=5, label='Mittelwert' if n == 1 else "")
    ax2.plot_surface(x, np.full_like(y, log_y_maxwert), z, alpha=0.3, color='red', rstride=5, cstride=5, label='Maximalwert' if n == 1 else "")

ax2.set_xlabel('X')
ax2.set_ylabel(r'$\log_{10}$(Rotationsgeschwindigkeit $v_{rot}$ (km/s))')
ax2.set_zlabel('Z')
ax2.set_title('3D-USK-Sphäre mit logarithmischen Rotationsgeschwindigkeiten (5 Faltungsschritte)')
ax2.legend()

plt.tight_layout()
plt.show()

import numpy as np
import matplotlib.pyplot as plt
from mpl_toolkits.mplot3d import Axes3D

# Konstanten
G = 6.67430e-11  # Gravitationskonstante (m^3 kg^-1 s^-2)
c = 299792458     # Lichtgeschwindigkeit (m/s)
M_sun_kg = 1.989e30  # Masse der Sonne in kg

# RVT-korrigierte Massen und Radien
M_tatsächlich_ngc891 = 9e11  # M☉
M_tatsächlich_m101 = 1.25e12  # M☉
R_tatsächlich_ngc891 = 107820  # Lj
R_tatsächlich_m101 = 105995   # Lj

# Umrechnung in Meter und kg
R_tatsächlich_ngc891_m = R_tatsächlich_ngc891 * 9.461e15  # Lj in m
R_tatsächlich_m101_m = R_tatsächlich_m101 * 9.461e15  # Lj in m
M_tatsächlich_ngc891_kg = M_tatsächlich_ngc891 * M_sun_kg
M_tatsächlich_m101_kg = M_tatsächlich_m101 * M_sun_kg

# Radiusbereich für die Simulation
r = np.logspace(np.log10(1e15), np.log10(max(R_tatsächlich_ngc891_m, R_tatsächlich_m101_m)), 100)

# Rotationsgeschwindigkeit OHNE RVT-Boost-Faktor
def rotation_velocity(r, M_0):
    return np.sqrt(G * M_0 / r)

# Berechnung der Rotationsgeschwindigkeiten
v_ngc891 = rotation_velocity(r, M_tatsächlich_ngc891_kg)
v_m101 = rotation_velocity(r, M_tatsächlich_m101_kg)

# Mittelwert, Maximalwert und Minimalwert der Rotationsgeschwindigkeiten
mittelwert_v_ngc891 = np.mean(v_ngc891)
maxwert_v_ngc891 = np.max(v_ngc891)
minwert_v_ngc891 = np.min(v_ngc891)

mittelwert_v_m101 = np.mean(v_m101)
maxwert_v_m101 = np.max(v_m101)
minwert_v_m101 = np.min(v_m101)

print(f"Mittelwert der Rotationsgeschwindigkeit für NGC 891: {mittelwert_v_ngc891 / 1000:.2f} km/s")
print(f"Maximalwert der Rotationsgeschwindigkeit für NGC 891: {maxwert_v_ngc891 / 1000:.2f} km/s")
print(f"Minimalwert der Rotationsgeschwindigkeit für NGC 891: {minwert_v_ngc891 / 1000:.2f} km/s")

print(f"Mittelwert der Rotationsgeschwindigkeit für M101: {mittelwert_v_m101 / 1000:.2f} km/s")
print(f"Maximalwert der Rotationsgeschwindigkeit für M101: {maxwert_v_m101 / 1000:.2f} km/s")
print(f"Minimalwert der Rotationsgeschwindigkeit für M101: {minwert_v_m101 / 1000:.2f} km/s")

# Massenkompression nach dem USK-Modell
def mass_compaction(n, M_0, kappa, q):
    return M_0 + kappa * np.sum(1 / np.arange(1, n + 1)**q)

kappa = 1e10  # Kompressionsfaktor
q = 1.5       # Konvergenzexponent

# RVT-Boost-Faktor als Funktion des Inklinationswinkels i
def rvt_boost(i_deg):
    i_rad = np.radians(i_deg)
    return 1 + 0.8 * np.sin(i_rad)

# Inklinationswinkel
inclination_ngc891 = 85
inclination_m101 = 18

# RVT-Boost-Faktoren
gamma_ngc891 = rvt_boost(inclination_ngc891)
gamma_m101 = rvt_boost(inclination_m101)

# Massenkompression für NGC 891 und M101 separat berechnen
M_0_ngc891 = M_tatsächlich_ngc891_kg
M_0_m101 = M_tatsächlich_m101_kg

mass_compaction_values_ngc891 = [mass_compaction(n, M_0_ngc891, kappa, q) for n in range(1, 6)]
mass_compaction_values_m101 = [mass_compaction(n, M_0_m101, kappa, q) for n in range(1, 6)]

# Ausgabe der Massenkompression für NGC 891 und M101
print("\n--- Massenkompression für NGC 891 (5 Faltungsschritte) ---")
for n in range(1, 6):
    print(f"Faltungsschritt {n}: {mass_compaction_values_ngc891[n-1] / 1e30:.2f} M☉")

print("\n--- Massenkompression für M101 (5 Faltungsschritte) ---")
for n in range(1, 6):
    print(f"Faltungsschritt {n}: {mass_compaction_values_m101[n-1] / 1e30:.2f} M☉")

# Logarithmische Darstellung der Rotationsgeschwindigkeiten
log_y_mittelwert_ngc891 = np.log10(mittelwert_v_ngc891 / 1000)
log_y_maxwert_ngc891 = np.log10(maxwert_v_ngc891 / 1000)
log_y_minwert_ngc891 = np.log10(minwert_v_ngc891 / 1000)

log_y_mittelwert_m101 = np.log10(mittelwert_v_m101 / 1000)
log_y_maxwert_m101 = np.log10(maxwert_v_m101 / 1000)
log_y_minwert_m101 = np.log10(minwert_v_m101 / 1000)

# Sphärische Koordinaten
theta = np.linspace(0, np.pi, 50)
phi = np.linspace(0, 2 * np.pi, 50)
theta_grid, phi_grid = np.meshgrid(theta, phi)

# Faltung der Sphäre
def usk_position(n, theta, phi, gamma):
    alpha = 0.5  # Faltungsintensität
    p = 2        # Projectionsexponent
    xi = 1 / (1 + alpha * n**p) * gamma
    r = 1 * xi
    x = r * np.sin(theta) * np.cos(phi)
    y = r * np.sin(theta) * np.sin(phi)
    z = r * np.cos(theta)
    return x, y, z

# Erstellen der 3D-Schaubilder für NGC 891 und M101
fig_ngc891 = plt.figure(figsize=(12, 8))
ax_ngc891 = fig_ngc891.add_subplot(111, projection='3d')

fig_m101 = plt.figure(figsize=(12, 8))
ax_m101 = fig_m101.add_subplot(111, projection='3d')

# Plot der USK-Sphäre für NGC 891
for n in range(1, 6):
    x, y, z = usk_position(n, theta_grid, phi_grid, gamma_ngc891)
    ax_ngc891.plot_surface(x, np.full_like(y, log_y_minwert_ngc891), z, alpha=0.3, color='green', rstride=5, cstride=5, label=r'Minimalwert' if n == 1 else "")
    ax_ngc891.plot_surface(x, np.full_like(y, log_y_mittelwert_ngc891), z, alpha=0.3, color='blue', rstride=5, cstride=5, label=r'Mittelwert' if n == 1 else "")
    ax_ngc891.plot_surface(x, np.full_like(y, log_y_maxwert_ngc891), z, alpha=0.3, color='red', rstride=5, cstride=5, label=r'Maximalwert' if n == 1 else "")

ax_ngc891.set_xlabel(r'$X$')
ax_ngc891.set_ylabel(r'$\log_{10}$(Rotationsgeschwindigkeit $v_{rot}$ (km/s))')
ax_ngc891.set_zlabel(r'$Z$')
ax_ngc891.set_title(r'3D-USK-Sphäre für NGC 891 (5 Faltungsschritte)')
ax_ngc891.legend()

# Plot der USK-Sphäre für M101
for n in range(1, 6):
    x, y, z = usk_position(n, theta_grid, phi_grid, gamma_m101)
    ax_m101.plot_surface(x, np.full_like(y, log_y_minwert_m101), z, alpha=0.3, color='cyan', rstride=5, cstride=5, label=r'Minimalwert' if n == 1 else "")
    ax_m101.plot_surface(x, np.full_like(y, log_y_mittelwert_m101), z, alpha=0.3, color='magenta', rstride=5, cstride=5, label=r'Mittelwert' if n == 1 else "")
    ax_m101.plot_surface(x, np.full_like(y, log_y_maxwert_m101), z, alpha=0.3, color='yellow', rstride=5, cstride=5, label=r'Maximalwert' if n == 1 else "")

ax_m101.set_xlabel(r'$X$')
ax_m101.set_ylabel(r'$\log_{10}$(Rotationsgeschwindigkeit $v_{rot}$ (km/s))')
ax_m101.set_zlabel(r'$Z$')
ax_m101.set_title(r'3D-USK-Sphäre für M101 (5 Faltungsschritte)')
ax_m101.legend()

plt.tight_layout()
plt.show()

import numpy as np
import matplotlib.pyplot as plt
from mpl_toolkits.mplot3d import Axes3D

# Konstanten
G = 6.67430e-11  # Gravitationskonstante (m^3 kg^-1 s^-2)
c = 299792458     # Lichtgeschwindigkeit (m/s)
M_sun_kg = 1.989e30  # Masse der Sonne in kg

# RVT-korrigierte Massen und Radien
M_tatsächlich_ngc891 = 9e11  # M☉
M_tatsächlich_m101 = 1.25e12  # M☉
R_tatsächlich_ngc891 = 107820  # Lj
R_tatsächlich_m101 = 105995   # Lj

# Umrechnung in Meter und kg
R_tatsächlich_ngc891_m = R_tatsächlich_ngc891 * 9.461e15  # Lj in m
R_tatsächlich_m101_m = R_tatsächlich_m101 * 9.461e15  # Lj in m
M_tatsächlich_ngc891_kg = M_tatsächlich_ngc891 * M_sun_kg
M_tatsächlich_m101_kg = M_tatsächlich_m101 * M_sun_kg

# Radiusbereich für die Simulation
r = np.logspace(np.log10(1e15), np.log10(max(R_tatsächlich_ngc891_m, R_tatsächlich_m101_m)), 100)

# Rotationsgeschwindigkeit OHNE RVT-Boost-Faktor
def rotation_velocity(r, M_0):
    return np.sqrt(G * M_0 / r)

# Berechnung der Rotationsgeschwindigkeiten
v_ngc891 = rotation_velocity(r, M_tatsächlich_ngc891_kg)
v_m101 = rotation_velocity(r, M_tatsächlich_m101_kg)

# Mittelwert, Maximalwert und Minimalwert der Rotationsgeschwindigkeiten
mittelwert_v_ngc891 = np.mean(v_ngc891)
maxwert_v_ngc891 = np.max(v_ngc891)
minwert_v_ngc891 = np.min(v_ngc891)

mittelwert_v_m101 = np.mean(v_m101)
maxwert_v_m101 = np.max(v_m101)
minwert_v_m101 = np.min(v_m101)

print(f"Mittelwert der Rotationsgeschwindigkeit für NGC 891: {mittelwert_v_ngc891 / 1000:.2f} km/s")
print(f"Maximalwert der Rotationsgeschwindigkeit für NGC 891: {maxwert_v_ngc891 / 1000:.2f} km/s")
print(f"Minimalwert der Rotationsgeschwindigkeit für NGC 891: {minwert_v_ngc891 / 1000:.2f} km/s")

print(f"Mittelwert der Rotationsgeschwindigkeit für M101: {mittelwert_v_m101 / 1000:.2f} km/s")
print(f"Maximalwert der Rotationsgeschwindigkeit für M101: {maxwert_v_m101 / 1000:.2f} km/s")
print(f"Minimalwert der Rotationsgeschwindigkeit für M101: {minwert_v_m101 / 1000:.2f} km/s")

# Massenkompression nach dem USK-Modell
def mass_compaction(n, M_0, kappa, q):
    return M_0 + kappa * np.sum(1 / np.arange(1, n + 1)**q)

kappa = 1e10  # Kompressionsfaktor
q = 1.5       # Konvergenzexponent

# RVT-Boost-Faktor als Funktion des Inklinationswinkels i
def rvt_boost(i_deg):
    i_rad = np.radians(i_deg)
    return 1 + 0.8 * np.sin(i_rad)

# Inklinationswinkel
inclination_ngc891 = 85
inclination_m101 = 18

# RVT-Boost-Faktoren
gamma_ngc891 = rvt_boost(inclination_ngc891)
gamma_m101 = rvt_boost(inclination_m101)

# Massenkompression für NGC 891 und M101 separat berechnen
M_0_ngc891 = M_tatsächlich_ngc891_kg
M_0_m101 = M_tatsächlich_m101_kg

# Berechnung der Massenkompression für 5 Faltungsschritte
mass_compaction_values_ngc891 = [mass_compaction(n, M_0_ngc891, kappa, q) for n in range(1, 6)]
mass_compaction_values_m101 = [mass_compaction(n, M_0_m101, kappa, q) for n in range(1, 6)]

# Sphärische Koordinaten
theta = np.linspace(0, np.pi, 50)
phi = np.linspace(0, 2 * np.pi, 50)
theta_grid, phi_grid = np.meshgrid(theta, phi)

# Faltung der S³-Sphäre
def usk_position(n, theta, phi, gamma):
    alpha = 0.5  # Faltungsintensität
    p = 2        # Projectionsexponent
    xi = 1 / (1 + alpha * n**p) * gamma
    r = 1 * xi
    x = r * np.sin(theta) * np.cos(phi)
    y = r * np.sin(theta) * np.sin(phi)
    z = r * np.cos(theta)
    return x, y, z

# Erstellen der 3D-Schaubilder für NGC 891
fig_ngc891 = plt.figure(figsize=(18, 6))

# Minimalwert
ax_ngc891_min = fig_ngc891.add_subplot(131, projection='3d')
x, y, z = usk_position(5, theta_grid, phi_grid, gamma_ngc891)
mass = mass_compaction_values_ngc891[4] / 1e30
ax_ngc891_min.plot_surface(x, y, z + minwert_v_ngc891 / 1000, alpha=0.7, color='green', rstride=5, cstride=5)
ax_ngc891_min.set_title(f'NGC 891 - Minimalwert\n{minwert_v_ngc891 / 1000:.2f} km/s\nMasse: {mass:.2f} M☉')
ax_ngc891_min.set_xlabel('X')
ax_ngc891_min.set_ylabel('Y')
ax_ngc891_min.set_zlabel('Z')

# Mittelwert
ax_ngc891_mid = fig_ngc891.add_subplot(132, projection='3d')
x, y, z = usk_position(5, theta_grid, phi_grid, gamma_ngc891)
mass = mass_compaction_values_ngc891[4] / 1e30
ax_ngc891_mid.plot_surface(x, y, z + mittelwert_v_ngc891 / 1000, alpha=0.7, color='blue', rstride=5, cstride=5)
ax_ngc891_mid.set_title(f'NGC 891 - Mittelwert\n{mittelwert_v_ngc891 / 1000:.2f} km/s\nMasse: {mass:.2f} M☉')
ax_ngc891_mid.set_xlabel('X')
ax_ngc891_mid.set_ylabel('Y')
ax_ngc891_mid.set_zlabel('Z')

# Maximalwert
ax_ngc891_max = fig_ngc891.add_subplot(133, projection='3d')
x, y, z = usk_position(5, theta_grid, phi_grid, gamma_ngc891)
mass = mass_compaction_values_ngc891[4] / 1e30
ax_ngc891_max.plot_surface(x, y, z + maxwert_v_ngc891 / 1000, alpha=0.7, color='red', rstride=5, cstride=5)
ax_ngc891_max.set_title(f'NGC 891 - Maximalwert\n{maxwert_v_ngc891 / 1000:.2f} km/s\nMasse: {mass:.2f} M☉')
ax_ngc891_max.set_xlabel('X')
ax_ngc891_max.set_ylabel('Y')
ax_ngc891_max.set_zlabel('Z')

# Erstellen der 3D-Schaubilder für M101
fig_m101 = plt.figure(figsize=(18, 6))

# Minimalwert
ax_m101_min = fig_m101.add_subplot(131, projection='3d')
x, y, z = usk_position(5, theta_grid, phi_grid, gamma_m101)
mass = mass_compaction_values_m101[4] / 1e30
ax_m101_min.plot_surface(x, y, z + minwert_v_m101 / 1000, alpha=0.7, color='cyan', rstride=5, cstride=5)
ax_m101_min.set_title(f'M101 - Minimalwert\n{minwert_v_m101 / 1000:.2f} km/s\nMasse: {mass:.2f} M☉')
ax_m101_min.set_xlabel('X')
ax_m101_min.set_ylabel('Y')
ax_m101_min.set_zlabel('Z')

# Mittelwert
ax_m101_mid = fig_m101.add_subplot(132, projection='3d')
x, y, z = usk_position(5, theta_grid, phi_grid, gamma_m101)
mass = mass_compaction_values_m101[4] / 1e30
ax_m101_mid.plot_surface(x, y, z + mittelwert_v_m101 / 1000, alpha=0.7, color='magenta', rstride=5, cstride=5)
ax_m101_mid.set_title(f'M101 - Mittelwert\n{mittelwert_v_m101 / 1000:.2f} km/s\nMasse: {mass:.2f} M☉')
ax_m101_mid.set_xlabel('X')
ax_m101_mid.set_ylabel('Y')
ax_m101_mid.set_zlabel('Z')

# Maximalwert
ax_m101_max = fig_m101.add_subplot(133, projection='3d')
x, y, z = usk_position(5, theta_grid, phi_grid, gamma_m101)
mass = mass_compaction_values_m101[4] / 1e30
ax_m101_max.plot_surface(x, y, z + maxwert_v_m101 / 1000, alpha=0.7, color='yellow', rstride=5, cstride=5)
ax_m101_max.set_title(f'M101 - Maximalwert\n{maxwert_v_m101 / 1000:.2f} km/s\nMasse: {mass:.2f} M☉')
ax_m101_max.set_xlabel('X')
ax_m101_max.set_ylabel('Y')
ax_m101_max.set_zlabel('Z')

plt.tight_layout()
plt.show()

import numpy as np
import matplotlib.pyplot as plt
from mpl_toolkits.mplot3d import Axes3D

# Konstanten
G = 6.67430e-11  # Gravitationskonstante (m^3 kg^-1 s^-2)
c = 299792458     # Lichtgeschwindigkeit (m/s)
M_sun_kg = 1.989e30  # Masse der Sonne in kg

# RVT-korrigierte Massen und Radien
M_tatsächlich_ngc891 = 9e11  # M☉
M_tatsächlich_m101 = 1.25e12  # M☉
R_tatsächlich_ngc891 = 107820  # Lj
R_tatsächlich_m101 = 105995   # Lj

# Umrechnung in Meter und kg
R_tatsächlich_ngc891_m = R_tatsächlich_ngc891 * 9.461e15  # Lj in m
R_tatsächlich_m101_m = R_tatsächlich_m101 * 9.461e15  # Lj in m
M_tatsächlich_ngc891_kg = M_tatsächlich_ngc891 * M_sun_kg
M_tatsächlich_m101_kg = M_tatsächlich_m101 * M_sun_kg

# Radiusbereich für die Simulation
r = np.logspace(np.log10(1e15), np.log10(max(R_tatsächlich_ngc891_m, R_tatsächlich_m101_m)), 100)

# Rotationsgeschwindigkeit OHNE RVT-Boost-Faktor
def rotation_velocity(r, M_0):
    return np.sqrt(G * M_0 / r)

# Berechnung der Rotationsgeschwindigkeiten
v_ngc891 = rotation_velocity(r, M_tatsächlich_ngc891_kg)
v_m101 = rotation_velocity(r, M_tatsächlich_m101_kg)

# Mittelwert, Maximalwert und Minimalwert der Rotationsgeschwindigkeiten
mittelwert_v_ngc891 = np.mean(v_ngc891)
maxwert_v_ngc891 = np.max(v_ngc891)
minwert_v_ngc891 = np.min(v_ngc891)

mittelwert_v_m101 = np.mean(v_m101)
maxwert_v_m101 = np.max(v_m101)
minwert_v_m101 = np.min(v_m101)

print(f"Mittelwert der Rotationsgeschwindigkeit für NGC 891: {mittelwert_v_ngc891 / 1000:.2f} km/s")
print(f"Maximalwert der Rotationsgeschwindigkeit für NGC 891: {maxwert_v_ngc891 / 1000:.2f} km/s")
print(f"Minimalwert der Rotationsgeschwindigkeit für NGC 891: {minwert_v_ngc891 / 1000:.2f} km/s")

print(f"Mittelwert der Rotationsgeschwindigkeit für M101: {mittelwert_v_m101 / 1000:.2f} km/s")
print(f"Maximalwert der Rotationsgeschwindigkeit für M101: {maxwert_v_m101 / 1000:.2f} km/s")
print(f"Minimalwert der Rotationsgeschwindigkeit für M101: {minwert_v_m101 / 1000:.2f} km/s")

# Massenkompression nach dem USK-Modell
def mass_compaction(n, M_0, kappa, q):
    return M_0 + kappa * np.sum(1 / np.arange(1, n + 1)**q)

kappa = 1e10  # Kompressionsfaktor
q = 1.5       # Konvergenzexponent

# RVT-Boost-Faktor als Funktion des Inklinationswinkels i
def rvt_boost(i_deg):
    i_rad = np.radians(i_deg)
    return 1 + 0.8 * np.sin(i_rad)

# Inklinationswinkel
inclination_ngc891 = 85
inclination_m101 = 18

# RVT-Boost-Faktoren
gamma_ngc891 = rvt_boost(inclination_ngc891)
gamma_m101 = rvt_boost(inclination_m101)

# Massenkompression für NGC 891 und M101 separat berechnen
M_0_ngc891 = M_tatsächlich_ngc891_kg
M_0_m101 = M_tatsächlich_m101_kg

# Berechnung der Massenkompression für 5 Faltungsschritte
mass_compaction_values_ngc891 = [mass_compaction(n, M_0_ngc891, kappa, q) for n in range(1, 6)]
mass_compaction_values_m101 = [mass_compaction(n, M_0_m101, kappa, q) for n in range(1, 6)]

# Sphärische Koordinaten
theta = np.linspace(0, np.pi, 50)
phi = np.linspace(0, 2 * np.pi, 50)
theta_grid, phi_grid = np.meshgrid(theta, phi)

# Faltung der S³-Sphäre
def usk_position(n, theta, phi, gamma, declination=0):
    alpha = 0.5  # Faltungsintensität
    p = 2        # Projectionsexponent
    xi = 1 / (1 + alpha * n**p) * gamma
    r = 1 * xi

    # Deklination einbeziehen
    decl_rad = np.radians(declination)
    x = r * np.sin(theta) * np.cos(phi) * np.cos(decl_rad)
    y = r * (np.sin(theta) * np.sin(phi) * np.cos(decl_rad) + np.cos(theta) * np.sin(decl_rad))
    z = r * (np.cos(theta) * np.cos(decl_rad) - np.sin(theta) * np.sin(phi) * np.sin(decl_rad))

    return x, y, z

# Erstellen der 3D-Schaubilder für NGC 891
fig_ngc891 = plt.figure(figsize=(18, 12))

# Minimalwert
ax_ngc891_min = fig_ngc891.add_subplot(231, projection='3d')
x, y, z = usk_position(5, theta_grid, phi_grid, gamma_ngc891)
mass = mass_compaction_values_ngc891[4] / 1e30
ax_ngc891_min.plot_surface(x, y, z + minwert_v_ngc891 / 1000, alpha=0.7, color='green', rstride=5, cstride=5)
ax_ngc891_min.set_title(f'NGC 891 - Minimalwert\n{minwert_v_ngc891 / 1000:.2f} km/s\nMasse: {mass:.2f} M☉')
ax_ngc891_min.set_xlabel('X')
ax_ngc891_min.set_ylabel('Y')
ax_ngc891_min.set_zlabel('Z')

# Mittelwert
ax_ngc891_mid = fig_ngc891.add_subplot(232, projection='3d')
x, y, z = usk_position(5, theta_grid, phi_grid, gamma_ngc891)
mass = mass_compaction_values_ngc891[4] / 1e30
ax_ngc891_mid.plot_surface(x, y, z + mittelwert_v_ngc891 / 1000, alpha=0.7, color='blue', rstride=5, cstride=5)
ax_ngc891_mid.set_title(f'NGC 891 - Mittelwert\n{mittelwert_v_ngc891 / 1000:.2f} km/s\nMasse: {mass:.2f} M☉')
ax_ngc891_mid.set_xlabel('X')
ax_ngc891_mid.set_ylabel('Y')
ax_ngc891_mid.set_zlabel('Z')

# Maximalwert
ax_ngc891_max = fig_ngc891.add_subplot(233, projection='3d')
x, y, z = usk_position(5, theta_grid, phi_grid, gamma_ngc891)
mass = mass_compaction_values_ngc891[4] / 1e30
ax_ngc891_max.plot_surface(x, y, z + maxwert_v_ngc891 / 1000, alpha=0.7, color='red', rstride=5, cstride=5)
ax_ngc891_max.set_title(f'NGC 891 - Maximalwert\n{maxwert_v_ngc891 / 1000:.2f} km/s\nMasse: {mass:.2f} M☉')
ax_ngc891_max.set_xlabel('X')
ax_ngc891_max.set_ylabel('Y')
ax_ngc891_max.set_zlabel('Z')

# 45° Deklination für NGC 891
ax_ngc891_decl = fig_ngc891.add_subplot(234, projection='3d')
x, y, z = usk_position(5, theta_grid, phi_grid, gamma_ngc891, declination=45)
mass = mass_compaction_values_ngc891[4] / 1e30
ax_ngc891_decl.plot_surface(x, y, z + mittelwert_v_ngc891 / 1000, alpha=0.7, color='purple', rstride=5, cstride=5)
ax_ngc891_decl.set_title(f'NGC 891 - 45° Deklination\n{mittelwert_v_ngc891 / 1000:.2f} km/s\nMasse: {mass:.2f} M☉')
ax_ngc891_decl.set_xlabel('X')
ax_ngc891_decl.set_ylabel('Y')
ax_ngc891_decl.set_zlabel('Z')

# 90° Projektion für NGC 891
ax_ngc891_90 = fig_ngc891.add_subplot(235, projection='3d')
x, y, z = usk_position(5, theta_grid, phi_grid, gamma_ngc891, declination=90)
mass = mass_compaction_values_ngc891[4] / 1e30
ax_ngc891_90.plot_surface(x, y, z + mittelwert_v_ngc891 / 1000, alpha=0.7, color='orange', rstride=5, cstride=5)
ax_ngc891_90.set_title(f'NGC 891 - 90° Projektion\n{mittelwert_v_ngc891 / 1000:.2f} km/s\nMasse: {mass:.2f} M☉')
ax_ngc891_90.set_xlabel('X')
ax_ngc891_90.set_ylabel('Y')
ax_ngc891_90.set_zlabel('Z')

# Erstellen der 3D-Schaubilder für M101
fig_m101 = plt.figure(figsize=(18, 12))

# Minimalwert
ax_m101_min = fig_m101.add_subplot(231, projection='3d')
x, y, z = usk_position(5, theta_grid, phi_grid, gamma_m101)
mass = mass_compaction_values_m101[4] / 1e30
ax_m101_min.plot_surface(x, y, z + minwert_v_m101 / 1000, alpha=0.7, color='cyan', rstride=5, cstride=5)
ax_m101_min.set_title(f'M101 - Minimalwert\n{minwert_v_m101 / 1000:.2f} km/s\nMasse: {mass:.2f} M☉')
ax_m101_min.set_xlabel('X')
ax_m101_min.set_ylabel('Y')
ax_m101_min.set_zlabel('Z')

# Mittelwert
ax_m101_mid = fig_m101.add_subplot(232, projection='3d')
x, y, z = usk_position(5, theta_grid, phi_grid, gamma_m101)
mass = mass_compaction_values_m101[4] / 1e30
ax_m101_mid.plot_surface(x, y, z + mittelwert_v_m101 / 1000, alpha=0.7, color='magenta', rstride=5, cstride=5)
ax_m101_mid.set_title(f'M101 - Mittelwert\n{mittelwert_v_m101 / 1000:.2f} km/s\nMasse: {mass:.2f} M☉')
ax_m101_mid.set_xlabel('X')
ax_m101_mid.set_ylabel('Y')
ax_m101_mid.set_zlabel('Z')

# Maximalwert
ax_m101_max = fig_m101.add_subplot(233, projection='3d')
x, y, z = usk_position(5, theta_grid, phi_grid, gamma_m101)
mass = mass_compaction_values_m101[4] / 1e30
ax_m101_max.plot_surface(x, y, z + maxwert_v_m101 / 1000, alpha=0.7, color='yellow', rstride=5, cstride=5)
ax_m101_max.set_title(f'M101 - Maximalwert\n{maxwert_v_m101 / 1000:.2f} km/s\nMasse: {mass:.2f} M☉')
ax_m101_max.set_xlabel('X')
ax_m101_max.set_ylabel('Y')
ax_m101_max.set_zlabel('Z')

# 45° Deklination für M101
ax_m101_decl = fig_m101.add_subplot(234, projection='3d')
x, y, z = usk_position(5, theta_grid, phi_grid, gamma_m101, declination=45)
mass = mass_compaction_values_m101[4] / 1e30
ax_m101_decl.plot_surface(x, y, z + mittelwert_v_m101 / 1000, alpha=0.7, color='purple', rstride=5, cstride=5)
ax_m101_decl.set_title(f'M101 - 45° Deklination\n{mittelwert_v_m101 / 1000:.2f} km/s\nMasse: {mass:.2f} M☉')
ax_m101_decl.set_xlabel('X')
ax_m101_decl.set_ylabel('Y')
ax_m101_decl.set_zlabel('Z')

# 90° Projektion für M101
ax_m101_90 = fig_m101.add_subplot(235, projection='3d')
x, y, z = usk_position(5, theta_grid, phi_grid, gamma_m101, declination=90)
mass = mass_compaction_values_m101[4] / 1e30
ax_m101_90.plot_surface(x, y, z + mittelwert_v_m101 / 1000, alpha=0.7, color='orange', rstride=5, cstride=5)
ax_m101_90.set_title(f'M101 - 90° Projektion\n{mittelwert_v_m101 / 1000:.2f} km/s\nMasse: {mass:.2f} M☉')
ax_m101_90.set_xlabel('X')
ax_m101_90.set_ylabel('Y')
ax_m101_90.set_zlabel('Z')

plt.tight_layout()
plt.show()

# Python-Skript: "Enten-Ragout-Regiment v1.0"
import numpy as np

class Ente:
    def __init__(self, name, geschwindigkeit_km_s):
        self.name = name
        self.geschwindigkeit = geschwindigkeit_km_s
        self.projiziert = False

    def projiziere(self):
        self.projiziert = True
        print(f"{self.name} projiziert auf $A_{{Lor}}$ – *WACK!* ") # Fixed: Escaped curly braces

    def marschieren(self):
        print(f"{self.name} marschiert mit {self.geschwindigkeit} km/s – *Watscheln, watscheln!* ")

# Regiment aufstellen
ragout_regiment = [
    Ente("Küken Karl", 220),
    Ente("Ente Emma", 250),
    Ente("Gans Günther", 270),
    Ente("Pittiplatsch", 300)  # Feldwebel – extra schnell!
]

# Befehlskette
for ente in ragout_regiment:
    ente.projiziere()
    ente.marschieren()

print("\n--- REGIMENT BEREIT! ---")
print("RVT-Ragout wird serviert – *mit geometrischer Präzision!* ")

import numpy as np
import matplotlib.pyplot as plt
from mpl_toolkits.mplot3d import Axes3D
from matplotlib.animation import FuncAnimation

fig = plt.figure(figsize=(14, 10))
ax = fig.add_subplot(111, projection='3d')

# Zaun (Grenze der etablierten Physik)
zaun_length = 4
zaun_x = np.linspace(-zaun_length/2, zaun_length/2, 20)
zaun_y = -2 * np.ones_like(zaun_x)
zaun_z = np.zeros_like(zaun_x)
ax.plot(zaun_x, zaun_y, zaun_z, color='brown', linewidth=3, label='Zaun (Grenze der Physik)')

# Eiergeknacke (Ursprung)
def egg(x, y, z, size=0.3):
    u = np.linspace(0, 2 * np.pi, 20)
    v = np.linspace(0, np.pi, 20)
    x_egg = size * np.outer(np.cos(u), np.sin(v)) + x
    y_egg = size * 1.2 * np.outer(np.sin(u), np.sin(v)) + y  # Ei-Form
    z_egg = size * np.outer(np.ones(np.size(u)), np.cos(v)) + z
    return ax.plot_surface(x_egg, y_egg, z_egg, color='white', alpha=0.8)

# Küken (neue RVT-Ideen)
def kueken(x, y, z, color='yellow', size=0.2):
    # Körper (Kugel)
    u = np.linspace(0, 2 * np.pi, 20)
    v = np.linspace(0, np.pi, 20)
    x_body = size * np.outer(np.cos(u), np.sin(v)) + x
    y_body = size * np.outer(np.sin(u), np.sin(v)) + y
    z_body = size * np.outer(np.ones(np.size(u)), np.cos(v)) + z
    ax.plot_surface(x_body, y_body, z_body, color=color, alpha=0.8)

    # Schnabel (Dreieck)
    schnabel = np.array([[x + size, y, z], [x + 1.5*size, y + 0.3*size, z], [x + 1.5*size, y - 0.3*size, z]])
    ax.plot_trisurf(schnabel[:, 0], schnabel[:, 1], schnabel[:, 2], color='orange', alpha=0.8)

    # Augen (2 Punkte)
    ax.scatter(x + 0.3*size, y + 0.2*size, z + 0.2*size, color='black', s=10)
    ax.scatter(x + 0.3*size, y - 0.2*size, z + 0.2*size, color='black', s=10)

    return ax.text(x, y, z + 0.5, 'Küken', color='black', ha='center', fontsize=8)

# Dinzinger (verlorenes Fahrradteil)
def dinzinger(x, y, z, size=0.2):
    # Zahnrad (symbolisiert das fehlende Teil)
    u = np.linspace(0, 2 * np.pi, 20)
    x_gear = size * np.cos(u) + x
    y_gear = size * np.sin(u) + y
    z_gear = np.zeros_like(u) + z
    ax.plot(x_gear, y_gear, z_gear, color='black', linewidth=2)

    # Speichen
    for i in range(6):
        angle = i * np.pi / 3
        ax.plot([x, x + size * np.cos(angle)],
                [y, y + size * np.sin(angle)],
                [z, z], color='black', linewidth=1)

    return ax.text(x, y, z + 0.3, 'Dinzinger\n(vom Felix Fahrrad)', color='black', ha='center', fontsize=8)

# Birk Borkasohn (depperter Beobachter)
def birk(x, y, z):
    # Kopf (Kugel)
    u = np.linspace(0, 2 * np.pi, 20)
    v = np.linspace(0, np.pi, 20)
    x_head = 0.3 * np.outer(np.cos(u), np.sin(v)) + x
    y_head = 0.3 * np.outer(np.sin(u), np.sin(v)) + y
    z_head = 0.3 * np.outer(np.ones(np.size(u)), np.cos(v)) + z + 0.5
    ax.plot_surface(x_head, y_head, z_head, color='lightblue', alpha=0.8)

    # Körper (Zylinder)
    body_z = np.linspace(0, 0.5, 2)
    body_theta = np.linspace(0, 2 * np.pi, 20)
    X_body, Z_body = np.meshgrid(np.cos(body_theta) * 0.2 + x, body_z + z)
    Y_body, _ = np.meshgrid(np.sin(body_theta) * 0.2 + y, body_z + z)
    ax.plot_surface(X_body, Y_body, Z_body, color='blue', alpha=0.5)

    # Sprechblase
    ax.text(x + 0.5, y, z + 0.8, '"Achherrje, wat nu?"', color='black', fontsize=9, ha='left')
    return ax.text(x, y, z + 0.7, 'Birk Borkasohn\ndeppert', color='black', ha='center', fontsize=8)

# Horst (Vereinbarungspartner)
def horst(x, y, z):
    # Horst als würdevoller Zylinder (symbolisiert die Vereinbarung)
    body_z = np.linspace(0, 1, 2)
    body_theta = np.linspace(0, 2 * np.pi, 20)
    X_body, Z_body = np.meshgrid(np.cos(body_theta) * 0.3 + x, body_z + z)
    Y_body, _ = np.meshgrid(np.sin(body_theta) * 0.3 + y, body_z + z)
    ax.plot_surface(X_body, Y_body, Z_body, color='darkgreen', alpha=0.7)

    # Hut (Kegel)
    u = np.linspace(0, 2 * np.pi, 20)
    v = np.linspace(0, np.pi/2, 10)
    x_hat = 0.2 * np.outer(np.cos(u), np.sin(v)) + x
    y_hat = 0.2 * np.outer(np.sin(u), np.sin(v)) + y
    z_hat = 0.2 * np.outer(np.ones(np.size(u)), np.cos(v)) + z + 1
    ax.plot_surface(x_hat, y_hat, z_hat, color='brown', alpha=0.7)

    return ax.text(x, y, z + 1.2, 'Horst\n"Wir hatten ne Vereinbarung!"', color='black', ha='center', fontsize=8)

# Laboe (Störfaktor)
def laboe(x, y, z):
    # Wolke (symbolisiert Verwirrung)
    u = np.linspace(0, 2 * np.pi, 20)
    v = np.linspace(0, np.pi, 20)
    x_cloud = 0.4 * np.outer(np.cos(u), np.sin(v)) + x + np.random.normal(0, 0.1, 400).reshape(20, 20)
    y_cloud = 0.4 * np.outer(np.sin(u), np.sin(v)) + y + np.random.normal(0, 0.1, 400).reshape(20, 20)
    z_cloud = 0.3 * np.outer(np.ones(np.size(u)), np.cos(v)) + z + np.random.normal(0, 0.1, 400).reshape(20, 20)
    ax.plot_surface(x_cloud, y_cloud, z_cloud, color='lightgray', alpha=0.5)
    return ax.text(x, y, z + 0.5, 'Laboe\n(verdorben vong MYstyle)', color='black', ha='center', fontsize=8)

# Animation: Die Szene entsteht
def update(frame):
    ax.clear()

    # Zaun
    ax.plot(zaun_x, zaun_y, zaun_z, color='brown', linewidth=3, label='Zaun')

    # Phase 1: Eiergeknacke (Ursprung)
    if frame < 10:
        egg(-1, -1.5, 0, 0.4)
        ax.set_title(f'Eiergeknacke am Zaun (Frame {frame})')

    # Phase 2: Küken schlüpfen (RVT entsteht)
    elif 10 <= frame < 20:
        egg(-1, -1.5, 0, 0.4)
        kueken(-1.3 + 0.1*frame, -1.5, 0, 'yellow', 0.2)
        ax.set_title(f'Küken schlüpfen (Frame {frame})')

    # Phase 3: Dinzinger fehlt (Fahrradteil)
    elif 20 <= frame < 30:
        egg(-1, -1.5, 0, 0.4)
        kueken(-0.3, -1.5, 0, 'yellow', 0.2)
        dinzinger(1, -1.5, 0, 0.2)
        ax.set_title(f'Dinzinger fehlt! (Frame {frame})')

    # Phase 4: Birk Borkasohn fragt, Horst ist enttäuscht
    elif 30 <= frame < 40:
        egg(-1, -1.5, 0, 0.4)
        kueken(-0.3, -1.5, 0, 'yellow', 0.2)
        dinzinger(1, -1.5, 0, 0.2)
        birk(0, 1, 0)
        horst(-2, 1, 0)
        ax.set_title(f'"Achherrje, wat nu?" (Frame {frame})')

    # Phase 5: Laboe verdirbt alles
    else:
        egg(-1, -1.5, 0, 0.4)
        kueken(-0.3, -1.5, 0, 'yellow', 0.2)
        dinzinger(1, -1.5, 0, 0.2)
        birk(0, 1, 0)
        horst(-2, 1, 0)
        laboe(1, 1, 0)
        ax.text(-1, 2, 0, '"Nix.", sagte ich und dachte,\nHorst und ich hatten ne Vereinbarung.',
                color='black', fontsize=9, ha='left')
        ax.set_title(f'Laboe verdorben vong MYstyle (Frame {frame})')

    ax.set_xlim(-3, 3)
    ax.set_ylim(-3, 2)
    ax.set_zlim(-1, 2)
    ax.set_xlabel('X (Raum)')
    ax.set_ylabel('Y (Raum)')
    ax.set_zlabel('Z (Zeit)')
    ax.legend()

ani = FuncAnimation(fig, update, frames=50, interval=200, repeat=True)
plt.tight_layout()
plt.show()

"""wo kommen denn bitte diese Werte her? hmmmm Phantasie vlt.?"""