# -*- coding: utf-8 -*-
"""rotation fix 2nd.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1O8g4VVgBp5FuL8AUYbqvasCYqMba3MUp
"""

import matplotlib.pyplot as plt
import numpy as np
from matplotlib.animation import FuncAnimation
from IPython.display import HTML

# Parameter
r = 1.0
tilt_deg = 23.5
tilt_rad = np.deg2rad(tilt_deg)
lat_45_rad = np.deg2rad(45)
fps = 16
duration_s = 8
total_frames = fps * duration_s

fig = plt.figure(figsize=(10, 10))
ax = fig.add_subplot(111, projection='3d')
fig.patch.set_facecolor('#0d1117')
ax.set_facecolor('#161b22')

# Basis-Daten für die Erde
u_vec = np.linspace(0, 2*np.pi, 30)
v_vec = np.linspace(0, np.pi, 20)
U, V = np.meshgrid(u_vec, v_vec)
x_base = r * np.cos(U) * np.sin(V)
y_base = r * np.sin(U) * np.sin(V)
z_base = r * np.cos(V)

def apply_tilt(x, y, z):
    xt = x * np.cos(tilt_rad) + z * np.sin(tilt_rad)
    yt = y
    zt = -x * np.sin(tilt_rad) + z * np.cos(tilt_rad)
    return xt, yt, zt

def rotate_around_axis(x, y, z, angle):
    xr = x * np.cos(angle) - y * np.sin(angle)
    yr = x * np.sin(angle) + y * np.cos(angle)
    zr = z
    return xr, yr, zr

# Statische Achse
axis_len = 1.8
north = np.array([axis_len * np.sin(tilt_rad), 0, axis_len * np.cos(tilt_rad)])
south = -north
ax.plot([south[0], north[0]], [0, 0], [south[2], north[2]], color='white', linewidth=3)

# Plots initialisieren
wireframe = [ax.plot_wireframe(*apply_tilt(x_base, y_base, z_base), color='#58a6ff', alpha=0.1, linewidth=0.5)]
phi = np.linspace(0, 2*np.pi, 100)
eq_x_b, eq_y_b, eq_z_b = r * np.cos(phi), r * np.sin(phi), np.zeros_like(phi)
equator_plot, = ax.plot(*apply_tilt(eq_x_b, eq_y_b, eq_z_b), color='#ff7b72', linewidth=2.5)

# Beobachter und Linien
obs_point, = ax.plot([], [], [], 'o', color='#1f6feb', markersize=8)
obs_dotted_line, = ax.plot([], [], [], color='#1f6feb', linestyle=':', linewidth=2)
horiz_line, = ax.plot([], [], [], color='#1f6feb', linewidth=2)
yellow_line, = ax.plot([], [], [], color='#ffeb3b', linewidth=3)
eq_obs_line, = ax.plot([], [], [], color='#ff7b72', linewidth=2)

# Grüne Viertel-Markierungen (Punkte und Linien)
green_dots_x, green_dots_y, green_dots_z = [], [], []
green_dots_plot, = ax.plot([], [], [], 'o', color='#2ea043', markersize=8, alpha=0.8, linestyle='None')
green_lines_plots = []
orange_fixed_points = []

# Traces
blue_trace_x, blue_trace_y, blue_trace_z = [], [], []
yellow_trace1_x, yellow_trace1_y, yellow_trace1_z = [], [], []
yellow_trace2_x, yellow_trace2_y, yellow_trace2_z = [], [], []
eq_trace_x, eq_trace_y, eq_trace_z = [], [], []

blue_trace_plot, = ax.plot([], [], [], color='#1f6feb', alpha=0.6, linewidth=1.5)
yellow_trace1_plot, = ax.plot([], [], [], color='#ffeb3b', alpha=0.6, linewidth=1.5)
yellow_trace2_plot, = ax.plot([], [], [], color='#ffeb3b', alpha=0.6, linewidth=1.5)
eq_trace_plot, = ax.plot([], [], [], color='#ff7b72', alpha=0.6, linewidth=1.5)

def update(frame):
    angle = (frame / total_frames) * 4 * np.pi

    if frame == 0 or frame == total_frames // 2:
        for t in [blue_trace_x, blue_trace_y, blue_trace_z,
                  yellow_trace1_x, yellow_trace1_y, yellow_trace1_z,
                  yellow_trace2_x, yellow_trace2_y, yellow_trace2_z,
                  eq_trace_x, eq_trace_y, eq_trace_z,
                  green_dots_x, green_dots_y, green_dots_z]: t.clear()
        for ln in green_lines_plots:
            try: ln.remove()
            except: pass
        for pt in orange_fixed_points:
            try: pt.remove()
            except: pass
        green_lines_plots.clear()
        orange_fixed_points.clear()

    xr, yr, zr = rotate_around_axis(x_base, y_base, z_base, angle)
    xt, yt, zt = apply_tilt(xr, yr, zr)
    wireframe[0].remove()
    wireframe[0] = ax.plot_wireframe(xt, yt, zt, color='#58a6ff', alpha=0.1, linewidth=0.5)

    exr, eyr, ezr = rotate_around_axis(eq_x_b, eq_y_b, eq_z_b, angle)
    ext, eyt, ezt = apply_tilt(exr, eyr, ezr)
    equator_plot.set_data(ext, eyt); equator_plot.set_3d_properties(ezt)

    l = 0.8
    center = np.array([0, 0, 0])
    b45 = np.array([r * np.sin(-lat_45_rad), 0, r * np.cos(-lat_45_rad)])

    y45_ang = -lat_45_rad - np.pi/2
    y45_end1 = b45 + np.array([l * np.sin(y45_ang), 0, l * np.cos(y45_ang)])
    y45_end2 = b45 - np.array([l * np.sin(y45_ang), 0, l * np.cos(y45_ang)])

    pts_loc = [center, b45, y45_end1, y45_end2]
    pts_final = [apply_tilt(*rotate_around_axis(p[0], p[1], p[2], angle)) for p in pts_loc]
    c_rot, obs, yel1, yel2 = pts_final

    h45_loc = b45 + np.array([-l, 0, 0])
    hor = apply_tilt(*rotate_around_axis(h45_loc[0], h45_loc[1], h45_loc[2], angle))

    obs_point.set_data([obs[0]], [obs[1]]); obs_point.set_3d_properties([obs[2]])
    obs_dotted_line.set_data([c_rot[0], obs[0]], [c_rot[1], obs[1]]); obs_dotted_line.set_3d_properties([c_rot[2], obs[2]])
    horiz_line.set_data([obs[0], hor[0]], [obs[1], hor[1]]); horiz_line.set_3d_properties([obs[2], hor[2]])
    yellow_line.set_data([yel1[0], yel2[0]], [yel1[1], yel2[1]]); yellow_line.set_3d_properties([yel1[2], yel2[2]])

    beq_loc = np.array([-r, 0, 0])
    heq_loc = beq_loc + np.array([-l, 0, 0])
    eq_b_final = apply_tilt(*rotate_around_axis(beq_loc[0], beq_loc[1], beq_loc[2], angle))
    eq_h_final = apply_tilt(*rotate_around_axis(heq_loc[0], heq_loc[1], heq_loc[2], angle))
    eq_obs_line.set_data([eq_b_final[0], eq_h_final[0]], [eq_b_final[1], eq_h_final[1]]); eq_obs_line.set_3d_properties([eq_b_final[2], eq_h_final[2]])

    blue_trace_x.append(hor[0]); blue_trace_y.append(hor[1]); blue_trace_z.append(hor[2])
    yellow_trace1_x.append(yel1[0]); yellow_trace1_y.append(yel1[1]); yellow_trace1_z.append(yel1[2])
    yellow_trace2_x.append(yel2[0]); yellow_trace2_y.append(yel2[1]); yellow_trace2_z.append(yel2[2])
    eq_trace_x.append(eq_h_final[0]); eq_trace_y.append(eq_h_final[1]); eq_trace_z.append(eq_h_final[2])

    quarter_step = total_frames / 8
    if frame % int(quarter_step) == 0:
        green_dots_x.append(hor[0]); green_dots_y.append(hor[1]); green_dots_z.append(hor[2])
        obs_arr = np.array(obs)
        hor_arr = np.array(hor)
        direction_vector = hor_arr - obs_arr
        g_line_end = hor_arr + 2.0 * direction_vector
        new_ln, = ax.plot([hor_arr[0], g_line_end[0]], [hor_arr[1], g_line_end[1]], [hor_arr[2], g_line_end[2]], color='#2ea043', linewidth=2, alpha=0.8)
        green_lines_plots.append(new_ln)
        # Oranger Punkt am Endpunkt der grünen Linie
        pt = ax.scatter([g_line_end[0]], [g_line_end[1]], [g_line_end[2]], color='#ffa657', s=150, edgecolors='white', linewidth=2, zorder=50)
        orange_fixed_points.append(pt)

    blue_trace_plot.set_data(blue_trace_x, blue_trace_y); blue_trace_plot.set_3d_properties(blue_trace_z)
    yellow_trace1_plot.set_data(yellow_trace1_x, yellow_trace1_y); yellow_trace1_plot.set_3d_properties(yellow_trace1_z)
    yellow_trace2_plot.set_data(yellow_trace2_x, yellow_trace2_y); yellow_trace2_plot.set_3d_properties(yellow_trace2_z)
    eq_trace_plot.set_data(eq_trace_x, eq_trace_y); eq_trace_plot.set_3d_properties(eq_trace_z)
    green_dots_plot.set_data(green_dots_x, green_dots_y); green_dots_plot.set_3d_properties(green_dots_z)

    return [equator_plot, obs_point, obs_dotted_line, horiz_line, yellow_line, eq_obs_line, blue_trace_plot, green_dots_plot] + green_lines_plots

ax.view_init(elev=5, azim=-90)
ax.set_axis_off()
ax.set_xlim(-2.5, 2.5); ax.set_ylim(-2.5, 2.5); ax.set_zlim(-2.5, 2.5)
ani = FuncAnimation(fig, update, frames=total_frames, interval=1000/fps, blit=False)
plt.close()
HTML(ani.to_jshtml())

import matplotlib.pyplot as plt
import numpy as np
from matplotlib.animation import FuncAnimation
from IPython.display import HTML

# Parameter
r = 1.0
tilt_deg = 23.5
tilt_rad = np.deg2rad(tilt_deg)
lat_45_rad = np.deg2rad(45)
fps = 16
duration_s = 8
total_frames = fps * duration_s

fig = plt.figure(figsize=(10, 10))
ax = fig.add_subplot(111, projection='3d')
fig.patch.set_facecolor('#0d1117')
ax.set_facecolor('#161b22')

# Basis-Daten für die Erde
u_vec = np.linspace(0, 2*np.pi, 30)
v_vec = np.linspace(0, np.pi, 20)
U, V = np.meshgrid(u_vec, v_vec)
x_base = r * np.cos(U) * np.sin(V)
y_base = r * np.sin(U) * np.sin(V)
z_base = r * np.cos(V)

def apply_tilt(x, y, z):
    xt = x * np.cos(tilt_rad) + z * np.sin(tilt_rad)
    yt = y
    zt = -x * np.sin(tilt_rad) + z * np.cos(tilt_rad)
    return xt, yt, zt

def rotate_around_axis(x, y, z, angle):
    xr = x * np.cos(angle) - y * np.sin(angle)
    yr = x * np.sin(angle) + y * np.cos(angle)
    zr = z
    return xr, yr, zr

def rotate_global(x, y, z, g_angle):
    # Zweite Form der Rotation: Drehung des gesamten Raums/Gitters um die globale Z-Achse
    xg = x * np.cos(g_angle) - y * np.sin(g_angle)
    yg = x * np.sin(g_angle) + y * np.cos(g_angle)
    zg = z
    return xg, yg, zg

# Statische Achsen-Basisvektoren
axis_len = 1.8
north_base = np.array([axis_len * np.sin(tilt_rad), 0, axis_len * np.cos(tilt_rad)])
south_base = -north_base

# Plots initialisieren
wireframe = [ax.plot_wireframe(*apply_tilt(x_base, y_base, z_base), color='#58a6ff', alpha=0.1, linewidth=0.5)]
phi = np.linspace(0, 2*np.pi, 100)
eq_x_b, eq_y_b, eq_z_b = r * np.cos(phi), r * np.sin(phi), np.zeros_like(phi)
equator_plot, = ax.plot(*apply_tilt(eq_x_b, eq_y_b, eq_z_b), color='#ff7b72', linewidth=2.5)
axis_plot, = ax.plot([], [], [], color='white', linewidth=3)

# Beobachter und Linien
obs_point, = ax.plot([], [], [], 'o', color='#1f6feb', markersize=8)
obs_dotted_line, = ax.plot([], [], [], color='#1f6feb', linestyle=':', linewidth=2)
horiz_line, = ax.plot([], [], [], color='#1f6feb', linewidth=2)
yellow_line, = ax.plot([], [], [], color='#ffeb3b', linewidth=3)
eq_obs_line, = ax.plot([], [], [], color='#ff7b72', linewidth=2)

# Grüne Viertel-Markierungen (Punkte und Linien)
green_dots_x, green_dots_y, green_dots_z = [], [], []
green_dots_plot, = ax.plot([], [], [], 'o', color='#2ea043', markersize=8, alpha=0.8, linestyle='None')
green_lines_plots = []
orange_fixed_points = []

# Traces
blue_trace_x, blue_trace_y, blue_trace_z = [], [], []
yellow_trace1_x, yellow_trace1_y, yellow_trace1_z = [], [], []
yellow_trace2_x, yellow_trace2_y, yellow_trace2_z = [], [], []
eq_trace_x, eq_trace_y, eq_trace_z = [], [], []

blue_trace_plot, = ax.plot([], [], [], color='#1f6feb', alpha=0.6, linewidth=1.5)
yellow_trace1_plot, = ax.plot([], [], [], color='#ffeb3b', alpha=0.6, linewidth=1.5)
yellow_trace2_plot, = ax.plot([], [], [], color='#ffeb3b', alpha=0.6, linewidth=1.5)
eq_trace_plot, = ax.plot([], [], [], color='#ff7b72', alpha=0.6, linewidth=1.5)

def update(frame):
    angle = (frame / total_frames) * 4 * np.pi
    angle_global = angle * 0.5  # Überlagerte Raumrotation im 3D-Gitter

    if frame == 0 or frame == total_frames // 2:
        for t in [blue_trace_x, blue_trace_y, blue_trace_z,
                  yellow_trace1_x, yellow_trace1_y, yellow_trace1_z,
                  yellow_trace2_x, yellow_trace2_y, yellow_trace2_z,
                  eq_trace_x, eq_trace_y, eq_trace_z,
                  green_dots_x, green_dots_y, green_dots_z]: t.clear()
        for ln in green_lines_plots:
            try: ln.remove()
            except: pass
        for pt in orange_fixed_points:
            try: pt.remove()
            except: pass
        green_lines_plots.clear()
        orange_fixed_points.clear()

    # 1. Erddrehung + Neigung + Globale Gitterrotation
    xr, yr, zr = rotate_around_axis(x_base, y_base, z_base, angle)
    xt, yt, zt = apply_tilt(xr, yr, zr)
    xg, yg, zg = rotate_global(xt, yt, zt, angle_global)
    wireframe[0].remove()
    wireframe[0] = ax.plot_wireframe(xg, yg, zg, color='#58a6ff', alpha=0.1, linewidth=0.5)

    # 2. Äquator mit dualer Rotation
    exr, eyr, ezr = rotate_around_axis(eq_x_b, eq_y_b, eq_z_b, angle)
    ext, eyt, ezt = apply_tilt(exr, eyr, ezr)
    exg, eyg, ezg = rotate_global(ext, eyt, ezt, angle_global)
    equator_plot.set_data(exg, eyg); equator_plot.set_3d_properties(ezg)

    # 3. Dynamische Aktualisierung der weißen Nord-Süd-Achse im Gitter
    n_g = rotate_global(north_base[0], north_base[1], north_base[2], angle_global)
    s_g = rotate_global(south_base[0], south_base[1], south_base[2], angle_global)
    axis_plot.set_data([s_g[0], n_g[0]], [s_g[1], n_g[1]]); axis_plot.set_3d_properties([s_g[2], n_g[2]])

    l = 0.8
    center = np.array([0, 0, 0])
    b45 = np.array([r * np.sin(-lat_45_rad), 0, r * np.cos(-lat_45_rad)])

    y45_ang = -lat_45_rad - np.pi/2
    y45_end1 = b45 + np.array([l * np.sin(y45_ang), 0, l * np.cos(y45_ang)])
    y45_end2 = b45 - np.array([l * np.sin(y45_ang), 0, l * np.cos(y45_ang)])

    pts_loc = [center, b45, y45_end1, y45_end2]
    # Interne Struktur bleibt starr, globale Raumrotation wird am Ende appliziert
    pts_tilted = [apply_tilt(*rotate_around_axis(p[0], p[1], p[2], angle)) for p in pts_loc]
    pts_final = [rotate_global(p[0], p[1], p[2], angle_global) for p in pts_tilted]
    c_rot, obs, yel1, yel2 = pts_final

    h45_loc = b45 + np.array([-l, 0, 0])
    hor_tilted = apply_tilt(*rotate_around_axis(h45_loc[0], h45_loc[1], h45_loc[2], angle))
    hor = rotate_global(hor_tilted[0], hor_tilted[1], hor_tilted[2], angle_global)

    # Blaue Kugel bleibt exakt an ihrer Oberflächenposition gekoppelt
    obs_point.set_data([obs[0]], [obs[1]]); obs_point.set_3d_properties([obs[2]])
    obs_dotted_line.set_data([c_rot[0], obs[0]], [c_rot[1], obs[1]]); obs_dotted_line.set_3d_properties([c_rot[2], obs[2]])
    horiz_line.set_data([obs[0], hor[0]], [obs[1], hor[1]]); horiz_line.set_3d_properties([obs[2], hor[2]])
    yellow_line.set_data([yel1[0], yel2[0]], [yel1[1], yel2[1]]); yellow_line.set_3d_properties([yel1[2], yel2[2]])

    beq_loc = np.array([-r, 0, 0])
    heq_loc = beq_loc + np.array([-l, 0, 0])
    eq_b_tilted = apply_tilt(*rotate_around_axis(beq_loc[0], beq_loc[1], beq_loc[2], angle))
    eq_h_tilted = apply_tilt(*rotate_around_axis(heq_loc[0], heq_loc[1], heq_loc[2], angle))
    eq_b_final = rotate_global(eq_b_tilted[0], eq_b_tilted[1], eq_b_tilted[2], angle_global)
    eq_h_final = rotate_global(eq_h_tilted[0], eq_h_tilted[1], eq_h_tilted[2], angle_global)
    eq_obs_line.set_data([eq_b_final[0], eq_h_final[0]], [eq_b_final[1], eq_h_final[1]]); eq_obs_line.set_3d_properties([eq_b_final[2], eq_h_final[2]])

    blue_trace_x.append(hor[0]); blue_trace_y.append(hor[1]); blue_trace_z.append(hor[2])
    yellow_trace1_x.append(yel1[0]); yellow_trace1_y.append(yel1[1]); yellow_trace1_z.append(yel1[2])
    yellow_trace2_x.append(yel2[0]); yellow_trace2_y.append(yel2[1]); yellow_trace2_z.append(yel2[2])
    eq_trace_x.append(eq_h_final[0]); eq_trace_y.append(eq_h_final[1]); eq_trace_z.append(eq_h_final[2])

    quarter_step = total_frames / 8
    if frame % int(quarter_step) == 0:
        green_dots_x.append(hor[0]); green_dots_y.append(hor[1]); green_dots_z.append(hor[2])
        obs_arr = np.array(obs)
        hor_arr = np.array(hor)
        direction_vector = hor_arr - obs_arr
        g_line_end = hor_arr + 2.0 * direction_vector
        new_ln, = ax.plot([hor_arr[0], g_line_end[0]], [hor_arr[1], g_line_end[1]], [hor_arr[2], g_line_end[2]], color='#2ea043', linewidth=2, alpha=0.8)
        green_lines_plots.append(new_ln)
        pt = ax.scatter([g_line_end[0]], [g_line_end[1]], [g_line_end[2]], color='#ffa657', s=150, edgecolors='white', linewidth=2, zorder=50)
        orange_fixed_points.append(pt)

    blue_trace_plot.set_data(blue_trace_x, blue_trace_y); blue_trace_plot.set_3d_properties(blue_trace_z)
    yellow_trace1_plot.set_data(yellow_trace1_x, yellow_trace1_y); yellow_trace1_plot.set_3d_properties(yellow_trace1_z)
    yellow_trace2_plot.set_data(yellow_trace2_x, yellow_trace2_y); yellow_trace2_plot.set_3d_properties(yellow_trace2_z)
    eq_trace_plot.set_data(eq_trace_x, eq_trace_y); eq_trace_plot.set_3d_properties(eq_trace_z)
    green_dots_plot.set_data(green_dots_x, green_dots_y); green_dots_plot.set_3d_properties(green_dots_z)

    return [equator_plot, obs_point, obs_dotted_line, horiz_line, yellow_line, eq_obs_line, blue_trace_plot, green_dots_plot, axis_plot] + green_lines_plots

ax.view_init(elev=5, azim=-90)
ax.set_axis_off()
ax.set_xlim(-2.5, 2.5); ax.set_ylim(-2.5, 2.5); ax.set_zlim(-2.5, 2.5)
ani = FuncAnimation(fig, update, frames=total_frames, interval=1000/fps, blit=False)
plt.close()
HTML(ani.to_jshtml())

import matplotlib.pyplot as plt
import numpy as np
from matplotlib.animation import FuncAnimation
from IPython.display import HTML

# Parameter
r = 1.0
tilt_deg = 23.5
tilt_rad = np.deg2rad(tilt_deg)
lat_45_rad = np.deg2rad(45)
fps = 16
duration_s = 8
total_frames = fps * duration_s

fig = plt.figure(figsize=(10, 10))
ax = fig.add_subplot(111, projection='3d')
fig.patch.set_facecolor('#0d1117')
ax.set_facecolor('#161b22')

# Basis-Daten für die Erde
u_vec = np.linspace(0, 2*np.pi, 30)
v_vec = np.linspace(0, np.pi, 20)
U, V = np.meshgrid(u_vec, v_vec)
x_base = r * np.cos(U) * np.sin(V)
y_base = r * np.sin(U) * np.sin(V)
z_base = r * np.cos(V)

def apply_tilt(x, y, z):
    xt = x * np.cos(tilt_rad) + z * np.sin(tilt_rad)
    yt = y
    zt = -x * np.sin(tilt_rad) + z * np.cos(tilt_rad)
    return xt, yt, zt

def rotate_around_axis(x, y, z, angle):
    xr = x * np.cos(angle) - y * np.sin(angle)
    yr = x * np.sin(angle) + y * np.cos(angle)
    zr = z
    return xr, yr, zr

def rotate_global(x, y, z, g_angle):
    # Drehung des gesamten Raums um die Z-Achse
    xg = x * np.cos(g_angle) - y * np.sin(g_angle)
    yg = x * np.sin(g_angle) + y * np.cos(g_angle)
    zg = z
    return xg, yg, zg

# Statische Achsen-Basisvektoren
axis_len = 1.8
north_base = np.array([axis_len * np.sin(tilt_rad), 0, axis_len * np.cos(tilt_rad)])
south_base = -north_base

# Plots initialisieren
wireframe = [ax.plot_wireframe(*apply_tilt(x_base, y_base, z_base), color='#58a6ff', alpha=0.1, linewidth=0.5)]
phi = np.linspace(0, 2*np.pi, 100)
eq_x_b, eq_y_b, eq_z_b = r * np.cos(phi), r * np.sin(phi), np.zeros_like(phi)
equator_plot, = ax.plot(*apply_tilt(eq_x_b, eq_y_b, eq_z_b), color='#ff7b72', linewidth=2.5)
axis_plot, = ax.plot([], [], [], color='white', linewidth=3)

# Beobachter und Linien
obs_point, = ax.plot([], [], [], 'o', color='#1f6feb', markersize=8)
obs_dotted_line, = ax.plot([], [], [], color='#1f6feb', linestyle=':', linewidth=2)
horiz_line, = ax.plot([], [], [], color='#1f6feb', linewidth=2)
yellow_line, = ax.plot([], [], [], color='#ffeb3b', linewidth=3)
eq_obs_line, = ax.plot([], [], [], color='#ff7b72', linewidth=2)

# Grüne Viertel-Markierungen
green_dots_x, green_dots_y, green_dots_z = [], [], []
green_dots_plot, = ax.plot([], [], [], 'o', color='#2ea043', markersize=8, alpha=0.8, linestyle='None')
green_lines_plots = []
orange_fixed_points = []

# Traces
blue_trace_x, blue_trace_y, blue_trace_z = [], [], []
yellow_trace1_x, yellow_trace1_y, yellow_trace1_z = [], [], []
yellow_trace2_x, yellow_trace2_y, yellow_trace2_z = [], [], []
eq_trace_x, eq_trace_y, eq_trace_z = [], [], []

blue_trace_plot, = ax.plot([], [], [], color='#1f6feb', alpha=0.6, linewidth=1.5)
yellow_trace1_plot, = ax.plot([], [], [], color='#ffeb3b', alpha=0.6, linewidth=1.5)
yellow_trace2_plot, = ax.plot([], [], [], color='#ffeb3b', alpha=0.6, linewidth=1.5)
eq_trace_plot, = ax.plot([], [], [], color='#ff7b72', alpha=0.6, linewidth=1.5)

def update(frame):
    # Exakte 1:1 Synchronisation: Kugelrotation = Raumrotation
    angle = (frame / total_frames) * 2 * np.pi  # Volle Umdrehung (360°) über alle Frames
    angle_global = angle  # Identisch zur Kugelrotation

    if frame == 0 or frame == total_frames // 2:
        for t in [blue_trace_x, blue_trace_y, blue_trace_z,
                  yellow_trace1_x, yellow_trace1_y, yellow_trace1_z,
                  yellow_trace2_x, yellow_trace2_y, yellow_trace2_z,
                  eq_trace_x, eq_trace_y, eq_trace_z,
                  green_dots_x, green_dots_y, green_dots_z]:
            t.clear()
        for ln in green_lines_plots:
            try: ln.remove()
            except: pass
        for pt in orange_fixed_points:
            try: pt.remove()
            except: pass
        green_lines_plots.clear()
        orange_fixed_points.clear()

    # 1. Erddrehung + Neigung + Globale Raumrotation (1:1 synchronisiert)
    xr, yr, zr = rotate_around_axis(x_base, y_base, z_base, angle)
    xt, yt, zt = apply_tilt(xr, yr, zr)
    xg, yg, zg = rotate_global(xt, yt, zt, angle_global)
    wireframe[0].remove()
    wireframe[0] = ax.plot_wireframe(xg, yg, zg, color='#58a6ff', alpha=0.1, linewidth=0.5)

    # 2. Äquator
    exr, eyr, ezr = rotate_around_axis(eq_x_b, eq_y_b, eq_z_b, angle)
    ext, eyt, ezt = apply_tilt(exr, eyr, ezr)
    exg, eyg, ezg = rotate_global(ext, eyt, ezt, angle_global)
    equator_plot.set_data(exg, eyg); equator_plot.set_3d_properties(ezg)

    # 3. Nord-Süd-Achse
    n_g = rotate_global(north_base[0], north_base[1], north_base[2], angle_global)
    s_g = rotate_global(south_base[0], south_base[1], south_base[2], angle_global)
    axis_plot.set_data([s_g[0], n_g[0]], [s_g[1], n_g[1]]); axis_plot.set_3d_properties([s_g[2], n_g[2]])

    l = 0.8
    center = np.array([0, 0, 0])
    b45 = np.array([r * np.sin(-lat_45_rad), 0, r * np.cos(-lat_45_rad)])

    y45_ang = -lat_45_rad - np.pi/2
    y45_end1 = b45 + np.array([l * np.sin(y45_ang), 0, l * np.cos(y45_ang)])
    y45_end2 = b45 - np.array([l * np.sin(y45_ang), 0, l * np.cos(y45_ang)])

    pts_loc = [center, b45, y45_end1, y45_end2]
    pts_tilted = [apply_tilt(*rotate_around_axis(p[0], p[1], p[2], angle)) for p in pts_loc]
    pts_final = [rotate_global(p[0], p[1], p[2], angle_global) for p in pts_tilted]
    c_rot, obs, yel1, yel2 = pts_final

    h45_loc = b45 + np.array([-l, 0, 0])
    hor_tilted = apply_tilt(*rotate_around_axis(h45_loc[0], h45_loc[1], h45_loc[2], angle))
    hor = rotate_global(hor_tilted[0], hor_tilted[1], hor_tilted[2], angle_global)

    obs_point.set_data([obs[0]], [obs[1]]); obs_point.set_3d_properties([obs[2]])
    obs_dotted_line.set_data([c_rot[0], obs[0]], [c_rot[1], obs[1]]); obs_dotted_line.set_3d_properties([c_rot[2], obs[2]])
    horiz_line.set_data([obs[0], hor[0]], [obs[1], hor[1]]); horiz_line.set_3d_properties([obs[2], hor[2]])
    yellow_line.set_data([yel1[0], yel2[0]], [yel1[1], yel2[1]]); yellow_line.set_3d_properties([yel1[2], yel2[2]])

    beq_loc = np.array([-r, 0, 0])
    heq_loc = beq_loc + np.array([-l, 0, 0])
    eq_b_tilted = apply_tilt(*rotate_around_axis(beq_loc[0], beq_loc[1], beq_loc[2], angle))
    eq_h_tilted = apply_tilt(*rotate_around_axis(heq_loc[0], heq_loc[1], heq_loc[2], angle))
    eq_b_final = rotate_global(eq_b_tilted[0], eq_b_tilted[1], eq_b_tilted[2], angle_global)
    eq_h_final = rotate_global(eq_h_tilted[0], eq_h_tilted[1], eq_h_tilted[2], angle_global)
    eq_obs_line.set_data([eq_b_final[0], eq_h_final[0]], [eq_b_final[1], eq_h_final[1]]); eq_obs_line.set_3d_properties([eq_b_final[2], eq_h_final[2]])

    blue_trace_x.append(hor[0]); blue_trace_y.append(hor[1]); blue_trace_z.append(hor[2])
    yellow_trace1_x.append(yel1[0]); yellow_trace1_y.append(yel1[1]); yellow_trace1_z.append(yel1[2])
    yellow_trace2_x.append(yel2[0]); yellow_trace2_y.append(yel2[1]); yellow_trace2_z.append(yel2[2])
    eq_trace_x.append(eq_h_final[0]); eq_trace_y.append(eq_h_final[1]); eq_trace_z.append(eq_h_final[2])

    quarter_step = total_frames / 8
    if frame % int(quarter_step) == 0:
        green_dots_x.append(hor[0]); green_dots_y.append(hor[1]); green_dots_z.append(hor[2])
        obs_arr = np.array(obs)
        hor_arr = np.array(hor)
        direction_vector = hor_arr - obs_arr
        g_line_end = hor_arr + 2.0 * direction_vector
        new_ln, = ax.plot([hor_arr[0], g_line_end[0]], [hor_arr[1], g_line_end[1]], [hor_arr[2], g_line_end[2]], color='#2ea043', linewidth=2, alpha=0.8)
        green_lines_plots.append(new_ln)
        pt = ax.scatter([g_line_end[0]], [g_line_end[1]], [g_line_end[2]], color='#ffa657', s=150, edgecolors='white', linewidth=2, zorder=50)
        orange_fixed_points.append(pt)

    blue_trace_plot.set_data(blue_trace_x, blue_trace_y); blue_trace_plot.set_3d_properties(blue_trace_z)
    yellow_trace1_plot.set_data(yellow_trace1_x, yellow_trace1_y); yellow_trace1_plot.set_3d_properties(yellow_trace1_z)
    yellow_trace2_plot.set_data(yellow_trace2_x, yellow_trace2_y); yellow_trace2_plot.set_3d_properties(yellow_trace2_z)
    eq_trace_plot.set_data(eq_trace_x, eq_trace_y); eq_trace_plot.set_3d_properties(eq_trace_z)
    green_dots_plot.set_data(green_dots_x, green_dots_y); green_dots_plot.set_3d_properties(green_dots_z)

    return [equator_plot, obs_point, obs_dotted_line, horiz_line, yellow_line, eq_obs_line, blue_trace_plot, green_dots_plot, axis_plot] + green_lines_plots

ax.view_init(elev=5, azim=-90)
ax.set_axis_off()
ax.set_xlim(-2.5, 2.5); ax.set_ylim(-2.5, 2.5); ax.set_zlim(-2.5, 2.5)
ani = FuncAnimation(fig, update, frames=total_frames, interval=1000/fps, blit=False)
plt.close()
HTML(ani.to_jshtml())

import matplotlib.pyplot as plt
import numpy as np
from matplotlib.animation import FuncAnimation
from IPython.display import HTML

# Parameter
r = 1.0
tilt_deg = 23.5
tilt_rad = np.deg2rad(tilt_deg)
lat_45_rad = np.deg2rad(45)
fps = 16
duration_s = 8
total_frames = fps * duration_s

fig = plt.figure(figsize=(10, 10))
ax = fig.add_subplot(111, projection='3d')
fig.patch.set_facecolor('#0d1117')
ax.set_facecolor('#161b22')

# Basis-Daten für die Erde
u_vec = np.linspace(0, 2*np.pi, 30)
v_vec = np.linspace(0, np.pi, 20)
U, V = np.meshgrid(u_vec, v_vec)
x_base = r * np.cos(U) * np.sin(V)
y_base = r * np.sin(U) * np.sin(V)
z_base = r * np.cos(V)

def apply_tilt(x, y, z):
    xt = x * np.cos(tilt_rad) + z * np.sin(tilt_rad)
    yt = y
    zt = -x * np.sin(tilt_rad) + z * np.cos(tilt_rad)
    return xt, yt, zt

def rotate_around_axis(x, y, z, angle):
    xr = x * np.cos(angle) - y * np.sin(angle)
    yr = x * np.sin(angle) + y * np.cos(angle)
    zr = z
    return xr, yr, zr

def rotate_global(x, y, z, g_angle):
    # Drehung des gesamten Raums/Gitters um die globale Z-Achse
    xg = x * np.cos(g_angle) - y * np.sin(g_angle)
    yg = x * np.sin(g_angle) + y * np.cos(g_angle)
    zg = z
    return xg, yg, zg

# Statische Achsen-Basisvektoren
axis_len = 1.8
north_base = np.array([axis_len * np.sin(tilt_rad), 0, axis_len * np.cos(tilt_rad)])
south_base = -north_base

# Plots initialisieren
wireframe = [ax.plot_wireframe(*apply_tilt(x_base, y_base, z_base), color='#58a6ff', alpha=0.1, linewidth=0.5)]
phi = np.linspace(0, 2*np.pi, 100)
eq_x_b, eq_y_b, eq_z_b = r * np.cos(phi), r * np.sin(phi), np.zeros_like(phi)
equator_plot, = ax.plot(*apply_tilt(eq_x_b, eq_y_b, eq_z_b), color='#ff7b72', linewidth=2.5)
axis_plot, = ax.plot([], [], [], color='white', linewidth=3)

# Beobachter und Linien
obs_point, = ax.plot([], [], [], 'o', color='#1f6feb', markersize=8)
obs_dotted_line, = ax.plot([], [], [], color='#1f6feb', linestyle=':', linewidth=2)
horiz_line, = ax.plot([], [], [], color='#1f6feb', linewidth=2)
yellow_line, = ax.plot([], [], [], color='#ffeb3b', linewidth=3)
eq_obs_line, = ax.plot([], [], [], color='#ff7b72', linewidth=2)

# Grüne Viertel-Markierungen (Punkte und Linien)
green_dots_x, green_dots_y, green_dots_z = [], [], []
green_dots_plot, = ax.plot([], [], [], 'o', color='#2ea043', markersize=8, alpha=0.8, linestyle='None')
green_lines_plots = []
orange_fixed_points = []

# Traces
blue_trace_x, blue_trace_y, blue_trace_z = [], [], []
yellow_trace1_x, yellow_trace1_y, yellow_trace1_z = [], [], []
yellow_trace2_x, yellow_trace2_y, yellow_trace2_z = [], [], []
eq_trace_x, eq_trace_y, eq_trace_z = [], [], []

blue_trace_plot, = ax.plot([], [], [], color='#1f6feb', alpha=0.6, linewidth=1.5)
yellow_trace1_plot, = ax.plot([], [], [], color='#ffeb3b', alpha=0.6, linewidth=1.5)
yellow_trace2_plot, = ax.plot([], [], [], color='#ffeb3b', alpha=0.6, linewidth=1.5)
eq_trace_plot, = ax.plot([], [], [], color='#ff7b72', alpha=0.6, linewidth=1.5)

def update(frame):
    angle = (frame / total_frames) * 4 * np.pi
    angle_global = angle  # Exakt zeitsynchron gekoppelt zur Kugeleigenrotation

    if frame == 0 or frame == total_frames // 2:
        for t in [blue_trace_x, blue_trace_y, blue_trace_z,
                  yellow_trace1_x, yellow_trace1_y, yellow_trace1_z,
                  yellow_trace2_x, yellow_trace2_y, yellow_trace2_z,
                  eq_trace_x, eq_trace_y, eq_trace_z,
                  green_dots_x, green_dots_y, green_dots_z]: t.clear()
        for ln in green_lines_plots:
            try: ln.remove()
            except: pass
        for pt in orange_fixed_points:
            try: pt.remove()
            except: pass
        green_lines_plots.clear()
        orange_fixed_points.clear()

    # 1. Erddrehung + Neigung + Synchronisierte Gitterrotation
    xr, yr, zr = rotate_around_axis(x_base, y_base, z_base, angle)
    xt, yt, zt = apply_tilt(xr, yr, zr)
    xg, yg, zg = rotate_global(xt, yt, zt, angle_global)
    wireframe[0].remove()
    wireframe[0] = ax.plot_wireframe(xg, yg, zg, color='#58a6ff', alpha=0.1, linewidth=0.5)

    # 2. Äquator mit synchronisierter dualer Rotation
    exr, eyr, ezr = rotate_around_axis(eq_x_b, eq_y_b, eq_z_b, angle)
    ext, eyt, ezt = apply_tilt(exr, eyr, ezr)
    exg, eyg, ezg = rotate_global(ext, eyt, ezt, angle_global)
    equator_plot.set_data(exg, eyg); equator_plot.set_3d_properties(ezg)

    # 3. Synchronisierte weiße Nord-Süd-Achse
    n_g = rotate_global(north_base[0], north_base[1], north_base[2], angle_global)
    s_g = rotate_global(south_base[0], south_base[1], south_base[2], angle_global)
    axis_plot.set_data([s_g[0], n_g[0]], [s_g[1], n_g[1]]); axis_plot.set_3d_properties([s_g[2], n_g[2]])

    l = 0.8
    center = np.array([0, 0, 0])
    b45 = np.array([r * np.sin(-lat_45_rad), 0, r * np.cos(-lat_45_rad)])

    y45_ang = -lat_45_rad - np.pi/2
    y45_end1 = b45 + np.array([l * np.sin(y45_ang), 0, l * np.cos(y45_ang)])
    y45_end2 = b45 - np.array([l * np.sin(y45_ang), 0, l * np.cos(y45_ang)])

    pts_loc = [center, b45, y45_end1, y45_end2]
    pts_tilted = [apply_tilt(*rotate_around_axis(p[0], p[1], p[2], angle)) for p in pts_loc]
    pts_final = [rotate_global(p[0], p[1], p[2], angle_global) for p in pts_tilted]
    c_rot, obs, yel1, yel2 = pts_final

    h45_loc = b45 + np.array([-l, 0, 0])
    hor_tilted = apply_tilt(*rotate_around_axis(h45_loc[0], h45_loc[1], h45_loc[2], angle))
    hor = rotate_global(hor_tilted[0], hor_tilted[1], hor_tilted[2], angle_global)

    # Blaue Kugel bleibt unverändert an exakter Oberflächenposition
    obs_point.set_data([obs[0]], [obs[1]]); obs_point.set_3d_properties([obs[2]])
    obs_dotted_line.set_data([c_rot[0], obs[0]], [c_rot[1], obs[1]]); obs_dotted_line.set_3d_properties([c_rot[2], obs[2]])
    horiz_line.set_data([obs[0], hor[0]], [obs[1], hor[1]]); horiz_line.set_3d_properties([obs[2], hor[2]])
    yellow_line.set_data([yel1[0], yel2[0]], [yel1[1], yel2[1]]); yellow_line.set_3d_properties([yel1[2], yel2[2]])

    beq_loc = np.array([-r, 0, 0])
    heq_loc = beq_loc + np.array([-l, 0, 0])
    eq_b_tilted = apply_tilt(*rotate_around_axis(beq_loc[0], beq_loc[1], beq_loc[2], angle))
    eq_h_tilted = apply_tilt(*rotate_around_axis(heq_loc[0], heq_loc[1], heq_loc[2], angle))
    eq_b_final = rotate_global(eq_b_tilted[0], eq_b_tilted[1], eq_b_tilted[2], angle_global)
    eq_h_final = rotate_global(eq_h_tilted[0], eq_h_tilted[1], eq_h_tilted[2], angle_global)
    eq_obs_line.set_data([eq_b_final[0], eq_h_final[0]], [eq_b_final[1], eq_h_final[1]]); eq_obs_line.set_3d_properties([eq_b_final[2], eq_h_final[2]])

    blue_trace_x.append(hor[0]); blue_trace_y.append(hor[1]); blue_trace_z.append(hor[2])
    yellow_trace1_x.append(yel1[0]); yellow_trace1_y.append(yel1[1]); yellow_trace1_z.append(yel1[2])
    yellow_trace2_x.append(yel2[0]); yellow_trace2_y.append(yel2[1]); yellow_trace2_z.append(yel2[2])
    eq_trace_x.append(eq_h_final[0]); eq_trace_y.append(eq_h_final[1]); eq_trace_z.append(eq_h_final[2])

    quarter_step = total_frames / 8
    if frame % int(quarter_step) == 0:
        green_dots_x.append(hor[0]); green_dots_y.append(hor[1]); green_dots_z.append(hor[2])
        obs_arr = np.array(obs)
        hor_arr = np.array(hor)
        direction_vector = hor_arr - obs_arr
        g_line_end = hor_arr + 2.0 * direction_vector
        new_ln, = ax.plot([hor_arr[0], g_line_end[0]], [hor_arr[1], g_line_end[1]], [hor_arr[2], g_line_end[2]], color='#2ea043', linewidth=2, alpha=0.8)
        green_lines_plots.append(new_ln)
        pt = ax.scatter([g_line_end[0]], [g_line_end[1]], [g_line_end[2]], color='#ffa657', s=150, edgecolors='white', linewidth=2, zorder=50)
        orange_fixed_points.append(pt)

    blue_trace_plot.set_data(blue_trace_x, blue_trace_y); blue_trace_plot.set_3d_properties(blue_trace_z)
    yellow_trace1_plot.set_data(yellow_trace1_x, yellow_trace1_y); yellow_trace1_plot.set_3d_properties(yellow_trace1_z)
    yellow_trace2_plot.set_data(yellow_trace2_x, yellow_trace2_y); yellow_trace2_plot.set_3d_properties(yellow_trace2_z)
    eq_trace_plot.set_data(eq_trace_x, eq_trace_y); eq_trace_plot.set_3d_properties(eq_trace_z)
    green_dots_plot.set_data(green_dots_x, green_dots_y); green_dots_plot.set_3d_properties(green_dots_z)

    return [equator_plot, obs_point, obs_dotted_line, horiz_line, yellow_line, eq_obs_line, blue_trace_plot, green_dots_plot, axis_plot] + green_lines_plots

ax.view_init(elev=5, azim=-90)
ax.set_axis_off()
ax.set_xlim(-2.5, 2.5); ax.set_ylim(-2.5, 2.5); ax.set_zlim(-2.5, 2.5)
ani = FuncAnimation(fig, update, frames=total_frames, interval=1000/fps, blit=False)
plt.close()
HTML(ani.to_jshtml())

import matplotlib.pyplot as plt
import numpy as np
from matplotlib.animation import FuncAnimation
from IPython.display import HTML

# Parameter
r = 1.0
tilt_deg = 23.5
tilt_rad = np.deg2rad(tilt_deg)
lat_45_rad = np.deg2rad(45)
fps = 16
duration_s = 8
total_frames = fps * duration_s

fig = plt.figure(figsize=(10, 10))
ax = fig.add_subplot(111, projection='3d')
fig.patch.set_facecolor('#0d1117')
ax.set_facecolor('#161b22')

# Basis-Daten für die Erde
u_vec = np.linspace(0, 2*np.pi, 30)
v_vec = np.linspace(0, np.pi, 20)
U, V = np.meshgrid(u_vec, v_vec)
x_base = r * np.cos(U) * np.sin(V)
y_base = r * np.sin(U) * np.sin(V)
z_base = r * np.cos(V)

def apply_tilt(x, y, z):
    xt = x * np.cos(tilt_rad) + z * np.sin(tilt_rad)
    yt = y
    zt = -x * np.sin(tilt_rad) + z * np.cos(tilt_rad)
    return xt, yt, zt

def rotate_around_axis(x, y, z, angle):
    xr = x * np.cos(angle) - y * np.sin(angle)
    yr = x * np.sin(angle) + y * np.cos(angle)
    zr = z
    return xr, yr, zr

def rotate_global(x, y, z, g_angle):
    # Drehung des gesamten Raums um die Z-Achse
    xg = x * np.cos(g_angle) - y * np.sin(g_angle)
    yg = x * np.sin(g_angle) + y * np.cos(g_angle)
    zg = z
    return xg, yg, zg

# Statische Achsen-Basisvektoren
axis_len = 1.8
north_base = np.array([axis_len * np.sin(tilt_rad), 0, axis_len * np.cos(tilt_rad)])
south_base = -north_base

# Plots initialisieren
wireframe = [ax.plot_wireframe(*apply_tilt(x_base, y_base, z_base), color='#58a6ff', alpha=0.1, linewidth=0.5)]
phi = np.linspace(0, 2*np.pi, 100)
eq_x_b, eq_y_b, eq_z_b = r * np.cos(phi), r * np.sin(phi), np.zeros_like(phi)
equator_plot, = ax.plot(*apply_tilt(eq_x_b, eq_y_b, eq_z_b), color='#ff7b72', linewidth=2.5)
axis_plot, = ax.plot([], [], [], color='white', linewidth=3)

# Beobachter und Linien
obs_point, = ax.plot([], [], [], 'o', color='#1f6feb', markersize=8)
obs_dotted_line, = ax.plot([], [], [], color='#1f6feb', linestyle=':', linewidth=2)
horiz_line, = ax.plot([], [], [], color='#1f6feb', linewidth=2)
yellow_line, = ax.plot([], [], [], color='#ffeb3b', linewidth=3)
eq_obs_line, = ax.plot([], [], [], color='#ff7b72', linewidth=2)

# Grüne Viertel-Markierungen
green_dots_x, green_dots_y, green_dots_z = [], [], []
green_dots_plot, = ax.plot([], [], [], 'o', color='#2ea043', markersize=8, alpha=0.8, linestyle='None')
green_lines_plots = []
orange_fixed_points = []

# Traces
blue_trace_x, blue_trace_y, blue_trace_z = [], [], []
yellow_trace1_x, yellow_trace1_y, yellow_trace1_z = [], [], []
yellow_trace2_x, yellow_trace2_y, yellow_trace2_z = [], [], []
eq_trace_x, eq_trace_y, eq_trace_z = [], [], []

blue_trace_plot, = ax.plot([], [], [], color='#1f6feb', alpha=0.6, linewidth=1.5)
yellow_trace1_plot, = ax.plot([], [], [], color='#ffeb3b', alpha=0.6, linewidth=1.5)
yellow_trace2_plot, = ax.plot([], [], [], color='#ffeb3b', alpha=0.6, linewidth=1.5)
eq_trace_plot, = ax.plot([], [], [], color='#ff7b72', alpha=0.6, linewidth=1.5)

def update(frame):
    # Kugeleigenrotation (Basis)
    angle = (frame / total_frames) * 4 * np.pi

    # Raumrotation skaliert über den Äquator-Faktor (1 / cos(45°))
    # Das gleicht den verringerten Radius des 45°-Breitenkreises im Vergleich zum Äquator aus
    angle_global = angle / np.cos(lat_45_rad)

    if frame == 0 or frame == total_frames // 2:
        for t in [blue_trace_x, blue_trace_y, blue_trace_z,
                  yellow_trace1_x, yellow_trace1_y, yellow_trace1_z,
                  yellow_trace2_x, yellow_trace2_y, yellow_trace2_z,
                  eq_trace_x, eq_trace_y, eq_trace_z,
                  green_dots_x, green_dots_y, green_dots_z]: t.clear()
        for ln in green_lines_plots:
            try: ln.remove()
            except: pass
        for pt in orange_fixed_points:
            try: pt.remove()
            except: pass
        green_lines_plots.clear()
        orange_fixed_points.clear()

    # 1. Erddrehung + Neigung + Globale Raumrotation (über Äquatorgeschwindigkeit kalibriert)
    xr, yr, zr = rotate_around_axis(x_base, y_base, z_base, angle)
    xt, yt, zt = apply_tilt(xr, yr, zr)
    xg, yg, zg = rotate_global(xt, yt, zt, angle_global)
    wireframe[0].remove()
    wireframe[0] = ax.plot_wireframe(xg, yg, zg, color='#58a6ff', alpha=0.1, linewidth=0.5)

    # 2. Äquator
    exr, eyr, ezr = rotate_around_axis(eq_x_b, eq_y_b, eq_z_b, angle)
    ext, eyt, ezt = apply_tilt(exr, eyr, ezr)
    exg, eyg, ezg = rotate_global(ext, eyt, ezt, angle_global)
    equator_plot.set_data(exg, eyg); equator_plot.set_3d_properties(ezg)

    # 3. Nord-Süd-Achse
    n_g = rotate_global(north_base[0], north_base[1], north_base[2], angle_global)
    s_g = rotate_global(south_base[0], south_base[1], south_base[2], angle_global)
    axis_plot.set_data([s_g[0], n_g[0]], [s_g[1], n_g[1]]); axis_plot.set_3d_properties([s_g[2], n_g[2]])

    l = 0.8
    center = np.array([0, 0, 0])
    b45 = np.array([r * np.sin(-lat_45_rad), 0, r * np.cos(-lat_45_rad)])

    y45_ang = -lat_45_rad - np.pi/2
    y45_end1 = b45 + np.array([l * np.sin(y45_ang), 0, l * np.cos(y45_ang)])
    y45_end2 = b45 - np.array([l * np.sin(y45_ang), 0, l * np.cos(y45_ang)])

    pts_loc = [center, b45, y45_end1, y45_end2]
    pts_tilted = [apply_tilt(*rotate_around_axis(p[0], p[1], p[2], angle)) for p in pts_loc]
    pts_final = [rotate_global(p[0], p[1], p[2], angle_global) for p in pts_tilted]
    c_rot, obs, yel1, yel2 = pts_final

    h45_loc = b45 + np.array([-l, 0, 0])
    hor_tilted = apply_tilt(*rotate_around_axis(h45_loc[0], h45_loc[1], h45_loc[2], angle))
    hor = rotate_global(hor_tilted[0], hor_tilted[1], hor_tilted[2], angle_global)

    obs_point.set_data([obs[0]], [obs[1]]); obs_point.set_3d_properties([obs[2]])
    obs_dotted_line.set_data([c_rot[0], obs[0]], [c_rot[1], obs[1]]); obs_dotted_line.set_3d_properties([c_rot[2], obs[2]])
    horiz_line.set_data([obs[0], hor[0]], [obs[1], hor[1]]); horiz_line.set_3d_properties([obs[2], hor[2]])
    yellow_line.set_data([yel1[0], yel2[0]], [yel1[1], yel2[1]]); yellow_line.set_3d_properties([yel1[2], yel2[2]])

    beq_loc = np.array([-r, 0, 0])
    heq_loc = beq_loc + np.array([-l, 0, 0])
    eq_b_tilted = apply_tilt(*rotate_around_axis(beq_loc[0], beq_loc[1], beq_loc[2], angle))
    eq_h_tilted = apply_tilt(*rotate_around_axis(heq_loc[0], heq_loc[1], heq_loc[2], angle))
    eq_b_final = rotate_global(eq_b_tilted[0], eq_b_tilted[1], eq_b_tilted[2], angle_global)
    eq_h_final = rotate_global(eq_h_tilted[0], eq_h_tilted[1], eq_h_tilted[2], angle_global)
    eq_obs_line.set_data([eq_b_final[0], eq_h_final[0]], [eq_b_final[1], eq_h_final[1]]); eq_obs_line.set_3d_properties([eq_b_final[2], eq_h_final[2]])

    blue_trace_x.append(hor[0]); blue_trace_y.append(hor[1]); blue_trace_z.append(hor[2])
    yellow_trace1_x.append(yel1[0]); yellow_trace1_y.append(yel1[1]); yellow_trace1_z.append(yel1[2])
    yellow_trace2_x.append(yel2[0]); yellow_trace2_y.append(yel2[1]); yellow_trace2_z.append(yel2[2])
    eq_trace_x.append(eq_h_final[0]); eq_trace_y.append(eq_h_final[1]); eq_trace_z.append(eq_h_final[2])

    quarter_step = total_frames / 8
    if frame % int(quarter_step) == 0:
        green_dots_x.append(hor[0]); green_dots_y.append(hor[1]); green_dots_z.append(hor[2])
        obs_arr = np.array(obs)
        hor_arr = np.array(hor)
        direction_vector = hor_arr - obs_arr
        g_line_end = hor_arr + 2.0 * direction_vector
        new_ln, = ax.plot([hor_arr[0], g_line_end[0]], [hor_arr[1], g_line_end[1]], [hor_arr[2], g_line_end[2]], color='#2ea043', linewidth=2, alpha=0.8)
        green_lines_plots.append(new_ln)
        pt = ax.scatter([g_line_end[0]], [g_line_end[1]], [g_line_end[2]], color='#ffa657', s=150, edgecolors='white', linewidth=2, zorder=50)
        orange_fixed_points.append(pt)

    blue_trace_plot.set_data(blue_trace_x, blue_trace_y); blue_trace_plot.set_3d_properties(blue_trace_z)
    yellow_trace1_plot.set_data(yellow_trace1_x, yellow_trace1_y); yellow_trace1_plot.set_3d_properties(yellow_trace1_z)
    yellow_trace2_plot.set_data(yellow_trace2_x, yellow_trace2_y); yellow_trace2_plot.set_3d_properties(yellow_trace2_z)
    eq_trace_plot.set_data(eq_trace_x, eq_trace_y); eq_trace_plot.set_3d_properties(eq_trace_z)
    green_dots_plot.set_data(green_dots_x, green_dots_y); green_dots_plot.set_3d_properties(green_dots_z)

    return [equator_plot, obs_point, obs_dotted_line, horiz_line, yellow_line, eq_obs_line, blue_trace_plot, green_dots_plot, axis_plot] + green_lines_plots

ax.view_init(elev=5, azim=-90)
ax.set_axis_off()
ax.set_xlim(-2.5, 2.5); ax.set_ylim(-2.5, 2.5); ax.set_zlim(-2.5, 2.5)
ani = FuncAnimation(fig, update, frames=total_frames, interval=1000/fps, blit=False)
plt.close()
HTML(ani.to_jshtml())

import matplotlib.pyplot as plt
import numpy as np
from matplotlib.animation import FuncAnimation
from IPython.display import HTML

# Parameter
r = 1.0
tilt_deg = 23.5
tilt_rad = np.deg2rad(tilt_deg)
lat_45_rad = np.deg2rad(45)
fps = 16
duration_s = 8
total_frames = fps * duration_s

fig = plt.figure(figsize=(10, 10))
ax = fig.add_subplot(111, projection='3d')
fig.patch.set_facecolor('#0d1117')
ax.set_facecolor('#161b22')

# Basis-Daten für die Erde
u_vec = np.linspace(0, 2*np.pi, 30)
v_vec = np.linspace(0, np.pi, 20)
U, V = np.meshgrid(u_vec, v_vec)
x_base = r * np.cos(U) * np.sin(V)
y_base = r * np.sin(U) * np.sin(V)
z_base = r * np.cos(V)

def apply_tilt(x, y, z):
    xt = x * np.cos(tilt_rad) + z * np.sin(tilt_rad)
    yt = y
    zt = -x * np.sin(tilt_rad) + z * np.cos(tilt_rad)
    return xt, yt, zt

def rotate_around_axis(x, y, z, angle):
    xr = x * np.cos(angle) - y * np.sin(angle)
    yr = x * np.sin(angle) + y * np.cos(angle)
    zr = z
    return xr, yr, zr

def rotate_global(x, y, z, g_angle):
    # Drehung des gesamten Raums um die Z-Achse
    xg = x * np.cos(g_angle) - y * np.sin(g_angle)
    yg = x * np.sin(g_angle) + y * np.cos(g_angle)
    zg = z
    return xg, yg, zg

# Statische Achsen-Basisvektoren
axis_len = 1.8
north_base = np.array([axis_len * np.sin(tilt_rad), 0, axis_len * np.cos(tilt_rad)])
south_base = -north_base

# Plots initialisieren
wireframe = [ax.plot_wireframe(*apply_tilt(x_base, y_base, z_base), color='#58a6ff', alpha=0.1, linewidth=0.5)]
phi = np.linspace(0, 2*np.pi, 100)
eq_x_b, eq_y_b, eq_z_b = r * np.cos(phi), r * np.sin(phi), np.zeros_like(phi)
equator_plot, = ax.plot(*apply_tilt(eq_x_b, eq_y_b, eq_z_b), color='#ff7b72', linewidth=2.5)
axis_plot, = ax.plot([], [], [], color='white', linewidth=3)

# Beobachter und Linien
obs_point, = ax.plot([], [], [], 'o', color='#1f6feb', markersize=8)
obs_dotted_line, = ax.plot([], [], [], color='#1f6feb', linestyle=':', linewidth=2)
horiz_line, = ax.plot([], [], [], color='#1f6feb', linewidth=2)
yellow_line, = ax.plot([], [], [], color='#ffeb3b', linewidth=3)
eq_obs_line, = ax.plot([], [], [], color='#ff7b72', linewidth=2)

# Grüne Viertel-Markierungen
green_dots_x, green_dots_y, green_dots_z = [], [], []
green_dots_plot, = ax.plot([], [], [], 'o', color='#2ea043', markersize=8, alpha=0.8, linestyle='None')
green_lines_plots = []
orange_fixed_points = []

# Traces
blue_trace_x, blue_trace_y, blue_trace_z = [], [], []
yellow_trace1_x, yellow_trace1_y, yellow_trace1_z = [], [], []
yellow_trace2_x, yellow_trace2_y, yellow_trace2_z = [], [], []
eq_trace_x, eq_trace_y, eq_trace_z = [], [], []

blue_trace_plot, = ax.plot([], [], [], color='#1f6feb', alpha=0.6, linewidth=1.5)
yellow_trace1_plot, = ax.plot([], [], [], color='#ffeb3b', alpha=0.6, linewidth=1.5)
yellow_trace2_plot, = ax.plot([], [], [], color='#ffeb3b', alpha=0.6, linewidth=1.5)
eq_trace_plot, = ax.plot([], [], [], color='#ff7b72', alpha=0.6, linewidth=1.5)

def update(frame):
    # Globale Raumrotation bleibt bei 2 Umläufen (4 * pi) in 8 Sekunden
    angle_global = (frame / total_frames) * 4 * np.pi

    # JETZT VERDOPPELT: Achsenrotation macht exakt 4 Umläufe (8 * pi) in 8 Sekunden!
    angle = (frame / total_frames) * 8 * np.pi

    if frame == 0 or frame == total_frames // 2:
        for t in [blue_trace_x, blue_trace_y, blue_trace_z,
                  yellow_trace1_x, yellow_trace1_y, yellow_trace1_z,
                  yellow_trace2_x, yellow_trace2_y, yellow_trace2_z,
                  eq_trace_x, eq_trace_y, eq_trace_z,
                  green_dots_x, green_dots_y, green_dots_z]: t.clear()

        for ln in green_lines_plots:
            try: ln.remove()
            except: pass
        green_lines_plots.clear()

        for pt in orange_fixed_points:
            try: pt.remove()
            except: pass
        orange_fixed_points.clear()

    # 1. Erddrehung (verdoppelt) + Neigung + Globale Raumrotation
    xr, yr, zr = rotate_around_axis(x_base, y_base, z_base, angle)
    xt, yt, zt = apply_tilt(xr, yr, zr)
    xg, yg, zg = rotate_global(xt, yt, zt, angle_global)
    wireframe[0].remove()
    wireframe[0] = ax.plot_wireframe(xg, yg, zg, color='#58a6ff', alpha=0.1, linewidth=0.5)

    # 2. Äquator (Rotiert mit der globalen Raumfrequenz)
    exr, eyr, ezr = rotate_around_axis(eq_x_b, eq_y_b, eq_z_b, angle)
    ext, eyt, ezt = apply_tilt(exr, eyr, ezr)
    exg, eyg, ezg = rotate_global(ext, eyt, ezt, angle_global)
    equator_plot.set_data(exg, eyg); equator_plot.set_3d_properties(ezg)

    # 3. Nord-Süd-Achse (Rotiert synchron mit der globalen Raumfrequenz)
    n_g = rotate_global(north_base[0], north_base[1], north_base[2], angle_global)
    s_g = rotate_global(south_base[0], south_base[1], south_base[2], angle_global)
    axis_plot.set_data([s_g[0], n_g[0]], [s_g[1], n_g[1]]); axis_plot.set_3d_properties([s_g[2], n_g[2]])

    l = 0.8
    center = np.array([0, 0, 0])
    b45 = np.array([r * np.sin(-lat_45_rad), 0, r * np.cos(-lat_45_rad)])

    y45_ang = -lat_45_rad - np.pi/2
    y45_end1 = b45 + np.array([l * np.sin(y45_ang), 0, l * np.cos(y45_ang)])
    y45_end2 = b45 - np.array([l * np.sin(y45_ang), 0, l * np.cos(y45_ang)])

    pts_loc = [center, b45, y45_end1, y45_end2]
    pts_tilted = [apply_tilt(*rotate_around_axis(p[0], p[1], p[2], angle)) for p in pts_loc]
    pts_final = [rotate_global(p[0], p[1], p[2], angle_global) for p in pts_tilted]
    c_rot, obs, yel1, yel2 = pts_final

    h45_loc = b45 + np.array([-l, 0, 0])
    hor_tilted = apply_tilt(*rotate_around_axis(h45_loc[0], h45_loc[1], h45_loc[2], angle))
    hor = rotate_global(hor_tilted[0], hor_tilted[1], hor_tilted[2], angle_global)

    obs_point.set_data([obs[0]], [obs[1]]); obs_point.set_3d_properties([obs[2]])
    obs_dotted_line.set_data([c_rot[0], obs[0]], [c_rot[1], obs[1]]); obs_dotted_line.set_3d_properties([c_rot[2], obs[2]])
    horiz_line.set_data([obs[0], hor[0]], [obs[1], hor[1]]); horiz_line.set_3d_properties([obs[2], hor[2]])
    yellow_line.set_data([yel1[0], yel2[0]], [yel1[1], yel2[1]]); yellow_line.set_3d_properties([yel1[2], yel2[2]])

    beq_loc = np.array([-r, 0, 0])
    heq_loc = beq_loc + np.array([-l, 0, 0])
    eq_b_tilted = apply_tilt(*rotate_around_axis(beq_loc[0], beq_loc[1], beq_loc[2], angle))
    eq_h_tilted = apply_tilt(*rotate_around_axis(heq_loc[0], heq_loc[1], heq_loc[2], angle))
    eq_b_final = rotate_global(eq_b_tilted[0], eq_b_tilted[1], eq_b_tilted[2], angle_global)
    eq_h_final = rotate_global(eq_h_tilted[0], eq_h_tilted[1], eq_h_tilted[2], angle_global)
    eq_obs_line.set_data([eq_b_final[0], eq_h_final[0]], [eq_b_final[1], eq_h_final[1]]); eq_obs_line.set_3d_properties([eq_b_final[2], eq_h_final[2]])

    blue_trace_x.append(hor[0]); blue_trace_y.append(hor[1]); blue_trace_z.append(hor[2])
    yellow_trace1_x.append(yel1[0]); yellow_trace1_y.append(yel1[1]); yellow_trace1_z.append(yel1[2])
    yellow_trace2_x.append(yel2[0]); yellow_trace2_y.append(yel2[1]); yellow_trace2_z.append(yel2[2])
    eq_trace_x.append(eq_h_final[0]); eq_trace_y.append(eq_h_final[1]); eq_trace_z.append(eq_h_final[2])

    quarter_step = total_frames / 8
    if frame % int(quarter_step) == 0:
        green_dots_x.append(hor[0]); green_dots_y.append(hor[1]); green_dots_z.append(hor[2])
        obs_arr = np.array(obs)
        hor_arr = np.array(hor)
        direction_vector = hor_arr - obs_arr
        g_line_end = hor_arr + 2.0 * direction_vector
        new_ln, = ax.plot([hor_arr[0], g_line_end[0]], [hor_arr[1], g_line_end[1]], [hor_arr[2], g_line_end[2]], color='#2ea043', linewidth=2, alpha=0.8)
        green_lines_plots.append(new_ln)

        pt = ax.scatter([g_line_end[0]], [g_line_end[1]], [g_line_end[2]], color='#ffa657', s=150, edgecolors='white', linewidth=2, zorder=50)
        orange_fixed_points.append(pt)

    blue_trace_plot.set_data(blue_trace_x, blue_trace_y); blue_trace_plot.set_3d_properties(blue_trace_z)
    yellow_trace1_plot.set_data(yellow_trace1_x, yellow_trace1_y); yellow_trace1_plot.set_3d_properties(yellow_trace1_z)
    yellow_trace2_plot.set_data(yellow_trace2_x, yellow_trace2_y); yellow_trace2_plot.set_3d_properties(yellow_trace2_z)
    eq_trace_plot.set_data(eq_trace_x, eq_trace_y); eq_trace_plot.set_3d_properties(eq_trace_z)
    green_dots_plot.set_data(green_dots_x, green_dots_y); green_dots_plot.set_3d_properties(green_dots_z)

    return [equator_plot, obs_point, obs_dotted_line, horiz_line, yellow_line, eq_obs_line, blue_trace_plot, green_dots_plot, axis_plot] + green_lines_plots

ax.view_init(elev=5, azim=-90)
ax.set_axis_off()
ax.set_xlim(-2.5, 2.5); ax.set_ylim(-2.5, 2.5); ax.set_zlim(-2.5, 2.5)
ani = FuncAnimation(fig, update, frames=total_frames, interval=1000/fps, blit=False)
plt.close()
HTML(ani.to_jshtml())

import matplotlib.pyplot as plt
import numpy as np
from matplotlib.animation import FuncAnimation
from IPython.display import HTML

# Parameter
r = 1.0
tilt_deg = 23.5
tilt_rad = np.deg2rad(tilt_deg)
lat_45_rad = np.deg2rad(45)
fps = 16
duration_s = 8
total_frames = fps * duration_s

fig = plt.figure(figsize=(10, 10))
ax = fig.add_subplot(111, projection='3d')
fig.patch.set_facecolor('#0d1117')
ax.set_facecolor('#161b22')

# Basis-Daten für beide Kugeln
u_vec = np.linspace(0, 2*np.pi, 30)
v_vec = np.linspace(0, np.pi, 20)
U, V = np.meshgrid(u_vec, v_vec)
x_base = r * np.cos(U) * np.sin(V)
y_base = r * np.sin(U) * np.sin(V)
z_base = r * np.cos(V)

def apply_tilt(x, y, z):
    xt = x * np.cos(tilt_rad) + z * np.sin(tilt_rad)
    yt = y
    zt = -x * np.sin(tilt_rad) + z * np.cos(tilt_rad)
    return xt, yt, zt

def rotate_around_axis(x, y, z, angle):
    xr = x * np.cos(angle) - y * np.sin(angle)
    yr = x * np.sin(angle) + y * np.cos(angle)
    zr = z
    return xr, yr, zr

def rotate_global(x, y, z, g_angle):
    xg = x * np.cos(g_angle) - y * np.sin(g_angle)
    yg = x * np.sin(g_angle) + y * np.cos(g_angle)
    zg = z
    return xg, yg, zg

def rotate_polar_triangle(x, y, z, amp):
    # Saubere Drehung um die Y-Achse für die Kugeloberfläche
    xp = x * np.cos(amp) + z * np.sin(amp)
    yp = y
    zp = -x * np.sin(amp) + z * np.cos(amp)
    return xp, yp, zp

# Statische Achsen-Basisvektoren
axis_len = 1.8
north_base = np.array([axis_len * np.sin(tilt_rad), 0, axis_len * np.cos(tilt_rad)])
south_base = -north_base

# Plots initialisieren
wireframe = [ax.plot_wireframe(*apply_tilt(x_base, y_base, z_base), color='#58a6ff', alpha=0.1, linewidth=0.5)]
wireframe_2 = [ax.plot_wireframe(*apply_tilt(x_base, y_base, z_base), color='#bc8cff', alpha=0.15, linewidth=0.5)]

phi = np.linspace(0, 2*np.pi, 100)
eq_x_b, eq_y_b, eq_z_b = r * np.cos(phi), r * np.sin(phi), np.zeros_like(phi)
equator_plot, = ax.plot(*apply_tilt(eq_x_b, eq_y_b, eq_z_b), color='#ff7b72', linewidth=2.5)

# Die zwei Achsenlinien
axis_plot, = ax.plot([], [], [], color='white', linewidth=3)
axis_plot_2, = ax.plot([], [], [], color='#ff79c6', linewidth=3, alpha=0.9) # Pinke Achse

# Beobachter und Linien
obs_point, = ax.plot([], [], [], 'o', color='#1f6feb', markersize=8)
obs_dotted_line, = ax.plot([], [], [], color='#1f6feb', linestyle=':', linewidth=2)
horiz_line, = ax.plot([], [], [], color='#1f6feb', linewidth=2)
yellow_line, = ax.plot([], [], [], color='#ffeb3b', linewidth=3)
eq_obs_line, = ax.plot([], [], [], color='#ff7b72', linewidth=2)

# Grüne Viertel-Markierungen
green_dots_x, green_dots_y, green_dots_z = [], [], []
green_dots_plot, = ax.plot([], [], [], 'o', color='#2ea043', markersize=8, alpha=0.8, linestyle='None')
green_lines_plots = []
orange_fixed_points = []

# Traces
blue_trace_x, blue_trace_y, blue_trace_z = [], [], []
yellow_trace1_x, yellow_trace1_y, yellow_trace1_z = [], [], []
yellow_trace2_x, yellow_trace2_y, yellow_trace2_z = [], [], []
eq_trace_x, eq_trace_y, eq_trace_z = [], [], []

blue_trace_plot, = ax.plot([], [], [], color='#1f6feb', alpha=0.6, linewidth=1.5)
yellow_trace1_plot, = ax.plot([], [], [], color='#ffeb3b', alpha=0.6, linewidth=1.5)
yellow_trace2_plot, = ax.plot([], [], [], color='#ffeb3b', alpha=0.6, linewidth=1.5)
eq_trace_plot, = ax.plot([], [], [], color='#ff7b72', alpha=0.6, linewidth=1.5)

def update(frame):
    # Globale Raumrotation
    angle_global = (frame / total_frames) * 4 * np.pi
    angle = (frame / total_frames) * 8 * np.pi

    # Saubere Dreiecksoszillation ohne Überschlag (Amplitudenbegrenzung auf sanftes Nick-Pendeln)
    cycle_progress = (angle_global % (2 * np.pi)) / (2 * np.pi)
    # Reines lineares Oszillieren zwischen -pi/4 und +pi/4 (kein voller Kreis, kein Überschlagen!)
    triangle_wave = 4 * np.abs(cycle_progress - np.floor(cycle_progress + 0.5)) - 1
    polar_amplitude = triangle_wave * (np.pi / 4)

    if frame == 0 or frame == total_frames // 2:
        for t in [blue_trace_x, blue_trace_y, blue_trace_z,
                  yellow_trace1_x, yellow_trace1_y, yellow_trace1_z,
                  yellow_trace2_x, yellow_trace2_y, yellow_trace2_z,
                  eq_trace_x, eq_trace_y, eq_trace_z,
                  green_dots_x, green_dots_y, green_dots_z]: t.clear()

        for ln in green_lines_plots:
            try: ln.remove()
            except: pass
        green_lines_plots.clear()

        for pt in orange_fixed_points:
            try: pt.remove()
            except: pass
        orange_fixed_points.clear()

    # 1. Kugel 1
    xr, yr, zr = rotate_around_axis(x_base, y_base, z_base, angle)
    xt, yt, zt = apply_tilt(xr, yr, zr)
    xg, yg, zg = rotate_global(xt, yt, zt, angle_global)
    wireframe[0].remove()
    wireframe[0] = ax.plot_wireframe(xg, yg, zg, color='#58a6ff', alpha=0.1, linewidth=0.5)

    # 2. Kugel 2 (folgt dem pendelnden polaren Vektor)
    x_p2, y_p2, z_p2 = rotate_polar_triangle(x_base, y_base, z_base, polar_amplitude)
    xt2, yt2, zt2 = apply_tilt(x_p2, y_p2, z_p2)
    xg2, yg2, zg2 = rotate_global(xt2, yt2, zt2, angle_global)
    wireframe_2[0].remove()
    wireframe_2[0] = ax.plot_wireframe(xg2, yg2, zg2, color='#bc8cff', alpha=0.15, linewidth=0.5)

    # 3. Äquator
    exr, eyr, ezr = rotate_around_axis(eq_x_b, eq_y_b, eq_z_b, angle)
    ext, eyt, ezt = apply_tilt(exr, eyr, ezr)
    exg, eyg, ezg = rotate_global(ext, eyt, ezt, angle_global)
    equator_plot.set_data(exg, eyg); equator_plot.set_3d_properties(ezg)

    # 4. Weiße Achse (Kugel 1)
    n_g = rotate_global(north_base[0], north_base[1], north_base[2], angle_global)
    s_g = rotate_global(south_base[0], south_base[1], south_base[2], angle_global)
    axis_plot.set_data([s_g[0], n_g[0]], [s_g[1], n_g[1]]); axis_plot.set_3d_properties([s_g[2], n_g[2]])

    # 5. Pinke Achse (Kugel 2): Nutzt dieselbe saubere Pendeltransformation ohne Überschlagen
    n2_p = rotate_polar_triangle(north_base[0], north_base[1], north_base[2], polar_amplitude)
    s2_p = rotate_polar_triangle(south_base[0], south_base[1], south_base[2], polar_amplitude)
    n2_g = rotate_global(n2_p[0], n2_p[1], n2_p[2], angle_global)
    s2_g = rotate_global(s2_p[0], s2_p[1], s2_p[2], angle_global)
    axis_plot_2.set_data([s2_g[0], n2_g[0]], [s2_g[1], n2_g[1]]); axis_plot_2.set_3d_properties([s2_g[2], n2_g[2]])

    # 6. Beobachter-Physik (Kugel 1)
    l = 0.8
    center = np.array([0, 0, 0])
    b45 = np.array([r * np.sin(-lat_45_rad), 0, r * np.cos(-lat_45_rad)])

    y45_ang = -lat_45_rad - np.pi/2
    y45_end1 = b45 + np.array([l * np.sin(y45_ang), 0, l * np.cos(y45_ang)])
    y45_end2 = b45 - np.array([l * np.sin(y45_ang), 0, l * np.cos(y45_ang)])

    pts_loc = [center, b45, y45_end1, y45_end2]
    pts_tilted = [apply_tilt(*rotate_around_axis(p[0], p[1], p[2], angle)) for p in pts_loc]
    pts_final = [rotate_global(p[0], p[1], p[2], angle_global) for p in pts_tilted]
    c_rot, obs, yel1, yel2 = pts_final

    h45_loc = b45 + np.array([-l, 0, 0])
    hor_tilted = apply_tilt(*rotate_around_axis(h45_loc[0], h45_loc[1], h45_loc[2], angle))
    hor = rotate_global(hor_tilted[0], hor_tilted[1], hor_tilted[2], angle_global)

    obs_point.set_data([obs[0]], [obs[1]]); obs_point.set_3d_properties([obs[2]])
    obs_dotted_line.set_data([c_rot[0], obs[0]], [c_rot[1], obs[1]]); obs_dotted_line.set_3d_properties([c_rot[2], obs[2]])
    horiz_line.set_data([obs[0], hor[0]], [obs[1], hor[1]]); horiz_line.set_3d_properties([obs[2], hor[2]])
    yellow_line.set_data([yel1[0], yel2[0]], [yel1[1], yel2[1]]); yellow_line.set_3d_properties([yel1[2], yel2[2]])

    beq_loc = np.array([-r, 0, 0])
    heq_loc = beq_loc + np.array([-l, 0, 0])
    eq_b_tilted = apply_tilt(*rotate_around_axis(beq_loc[0], beq_loc[1], beq_loc[2], angle))
    eq_h_tilted = apply_tilt(*rotate_around_axis(heq_loc[0], heq_loc[1], heq_loc[2], angle))
    eq_b_final = rotate_global(eq_b_tilted[0], eq_b_tilted[1], eq_b_tilted[2], angle_global)
    eq_h_final = rotate_global(eq_h_tilted[0], eq_h_tilted[1], eq_h_tilted[2], angle_global)
    eq_obs_line.set_data([eq_b_final[0], eq_h_final[0]], [eq_b_final[1], eq_h_final[1]]); eq_obs_line.set_3d_properties([eq_b_final[2], eq_h_final[2]])

    blue_trace_x.append(hor[0]); blue_trace_y.append(hor[1]); blue_trace_z.append(hor[2])
    yellow_trace1_x.append(yel1[0]); yellow_trace1_y.append(yel1[1]); yellow_trace1_z.append(yel1[2])
    yellow_trace2_x.append(yel2[0]); yellow_trace2_y.append(yel2[1]); yellow_trace2_z.append(yel2[2])
    eq_trace_x.append(eq_h_final[0]); eq_trace_y.append(eq_h_final[1]); eq_trace_z.append(eq_h_final[2])

    quarter_step = total_frames / 8
    if frame % int(quarter_step) == 0:
        green_dots_x.append(hor[0]); green_dots_y.append(hor[1]); green_dots_z.append(hor[2])
        obs_arr = np.array(obs)
        hor_arr = np.array(hor)
        direction_vector = hor_arr - obs_arr
        g_line_end = hor_arr + 2.0 * direction_vector
        new_ln, = ax.plot([hor_arr[0], g_line_end[0]], [hor_arr[1], g_line_end[1]], [hor_arr[2], g_line_end[2]], color='#2ea043', linewidth=2, alpha=0.8)
        green_lines_plots.append(new_ln)

        pt = ax.scatter([g_line_end[0]], [g_line_end[1]], [g_line_end[2]], color='#ffa657', s=150, edgecolors='white', linewidth=2, zorder=50)
        orange_fixed_points.append(pt)

    blue_trace_plot.set_data(blue_trace_x, blue_trace_y); blue_trace_plot.set_3d_properties(blue_trace_z)
    yellow_trace1_plot.set_data(yellow_trace1_x, yellow_trace1_y); yellow_trace1_plot.set_3d_properties(yellow_trace1_z)
    yellow_trace2_plot.set_data(yellow_trace2_x, yellow_trace2_y); yellow_trace2_plot.set_3d_properties(yellow_trace2_z)
    eq_trace_plot.set_data(eq_trace_x, eq_trace_y); eq_trace_plot.set_3d_properties(eq_trace_z)
    green_dots_plot.set_data(green_dots_x, green_dots_y); green_dots_plot.set_3d_properties(green_dots_z)

    return [equator_plot, obs_point, obs_dotted_line, horiz_line, yellow_line, eq_obs_line, blue_trace_plot, green_dots_plot, axis_plot, axis_plot_2] + green_lines_plots

ax.view_init(elev=5, azim=-90)
ax.set_axis_off()
ax.set_xlim(-2.5, 2.5); ax.set_ylim(-2.5, 2.5); ax.set_zlim(-2.5, 2.5)
ani = FuncAnimation(fig, update, frames=total_frames, interval=1000/fps, blit=False)
plt.close()
HTML(ani.to_jshtml())

import matplotlib.pyplot as plt
import numpy as np
from matplotlib.animation import FuncAnimation
from IPython.display import HTML

# Parameter
r = 1.0
r2 = 1.0  # Radius identisch
tilt_deg = 23.5
tilt_rad = np.deg2rad(tilt_deg)
lat_45_rad = np.deg2rad(45)
fps = 16
duration_s = 8
total_frames = fps * duration_s

fig = plt.figure(figsize=(10, 10))
ax = fig.add_subplot(111, projection='3d')
fig.patch.set_facecolor('#0d1117')
ax.set_facecolor('#161b22')

# Basis-Daten
u_vec = np.linspace(0, 2*np.pi, 30)
v_vec = np.linspace(0, np.pi, 20)
U, V = np.meshgrid(u_vec, v_vec)

x_base = r * np.cos(U) * np.sin(V)
y_base = r * np.sin(U) * np.sin(V)
z_base = r * np.cos(V)

def apply_tilt(x, y, z):
    xt = x * np.cos(tilt_rad) + z * np.sin(tilt_rad)
    yt = y
    zt = -x * np.sin(tilt_rad) + z * np.cos(tilt_rad)
    return xt, yt, zt

def rotate_around_axis(x, y, z, angle):
    xr = x * np.cos(angle) - y * np.sin(angle)
    yr = x * np.sin(angle) + y * np.cos(angle)
    zr = z
    return xr, yr, zr

def rotate_global(x, y, z, g_angle):
    xg = x * np.cos(g_angle) - y * np.sin(g_angle)
    yg = x * np.sin(g_angle) + y * np.cos(g_angle)
    zg = z
    return xg, yg, zg

axis_len = 1.8
north_base = np.array([axis_len * np.sin(tilt_rad), 0, axis_len * np.cos(tilt_rad)])
south_base = -north_base

# Plots
wireframe = [ax.plot_wireframe(*apply_tilt(x_base, y_base, z_base), color='#58a6ff', alpha=0.1, linewidth=0.5)]
wireframe_2 = [ax.plot_wireframe(*apply_tilt(x_base, y_base, z_base), color='#bc8cff', alpha=0.3, linewidth=0.5)]

phi = np.linspace(0, 2*np.pi, 100)
eq_x_b, eq_y_b, eq_z_b = r * np.cos(phi), r * np.sin(phi), np.zeros_like(phi)
equator_plot, = ax.plot(*apply_tilt(eq_x_b, eq_y_b, eq_z_b), color='#ff7b72', linewidth=2.5)
axis_plot = ax.plot([], [], [], color='white', linewidth=3)[0] # Kugel 1 Achse
axis_plot_2 = ax.plot([], [], [], color='#ff79c6', linewidth=3, alpha=0.8)[0] # Kugel 2 Achse

obs_point, = ax.plot([], [], [], 'o', color='#1f6feb', markersize=8)
obs_dotted_line, = ax.plot([], [], [], color='#1f6feb', linestyle=':', linewidth=2)
horiz_line, = ax.plot([], [], [], color='#1f6feb', linewidth=2)
yellow_line, = ax.plot([], [], [], color='#ffeb3b', linewidth=3)
blue_trace_plot, = ax.plot([], [], [], color='#1f6feb', alpha=0.6, linewidth=1.5)
blue_trace_x, blue_trace_y, blue_trace_z = [], [], []

def update(frame):
    # Kugel 1 rotiert global mit 2 Umläufen (4*pi)
    angle_global = (frame / total_frames) * 4 * np.pi
    # Kugel 2 rotiert doppelt so schnell (8*pi)
    angle_global_2 = angle_global * 2

    angle_1 = (frame / total_frames) * 8 * np.pi
    angle_2 = angle_1 * 2

    if frame == 0: blue_trace_x.clear(); blue_trace_y.clear(); blue_trace_z.clear()

    # Kugel 1 Update
    xr1, yr1, zr1 = rotate_around_axis(x_base, y_base, z_base, angle_1)
    xg1, yg1, zg1 = rotate_global(*apply_tilt(xr1, yr1, zr1), angle_global)
    wireframe[0].remove()
    wireframe[0] = ax.plot_wireframe(xg1, yg1, zg1, color='#58a6ff', alpha=0.08, linewidth=0.5)

    # Kugel 2 Update (schnellere globale Rotation)
    xr2, yr2, zr2 = rotate_around_axis(x_base, y_base, z_base, angle_2)
    xg2, yg2, zg2 = rotate_global(*apply_tilt(xr2, yr2, zr2), angle_global_2)
    wireframe_2[0].remove()
    wireframe_2[0] = ax.plot_wireframe(xg2, yg2, zg2, color='#bc8cff', alpha=0.25, linewidth=0.5)

    # Achsen-Update
    # Weiße Achse (Kugel 1) - rotiert langsam
    n1_g = rotate_global(*north_base, angle_global)
    s1_g = rotate_global(*south_base, angle_global)
    axis_plot.set_data([s1_g[0], n1_g[0]], [s1_g[1], n1_g[1]]); axis_plot.set_3d_properties([s1_g[2], n1_g[2]])

    # Pinke Achse (Kugel 2) - rotiert schneller
    n2_g = rotate_global(*north_base, angle_global_2)
    s2_g = rotate_global(*south_base, angle_global_2)
    axis_plot_2.set_data([s2_g[0], n2_g[0]], [s2_g[1], n2_g[1]]); axis_plot_2.set_3d_properties([s2_g[2], n2_g[2]])

    # Physik Kugel 1
    exg, eyg, ezg = rotate_global(*apply_tilt(*rotate_around_axis(eq_x_b, eq_y_b, eq_z_b, angle_1)), angle_global)
    equator_plot.set_data(exg, eyg); equator_plot.set_3d_properties(ezg)

    l = 0.8
    b45 = np.array([r * np.sin(-lat_45_rad), 0, r * np.cos(-lat_45_rad)])
    pts_f = [rotate_global(*apply_tilt(*rotate_around_axis(p[0], p[1], p[2], angle_1)), angle_global) for p in [np.zeros(3), b45, b45 + np.array([l*np.sin(-lat_45_rad-np.pi/2), 0, l*np.cos(-lat_45_rad-np.pi/2)]), b45 - np.array([l*np.sin(-lat_45_rad-np.pi/2), 0, l*np.cos(-lat_45_rad-np.pi/2)])]]
    c_rot, obs, yel1, yel2 = pts_f
    hor = rotate_global(*apply_tilt(*rotate_around_axis(b45[0]-l, 0, b45[2], angle_1)), angle_global)

    obs_point.set_data([obs[0]], [obs[1]]); obs_point.set_3d_properties([obs[2]])
    obs_dotted_line.set_data([c_rot[0], obs[0]], [c_rot[1], obs[1]]); obs_dotted_line.set_3d_properties([c_rot[2], obs[2]])
    horiz_line.set_data([obs[0], hor[0]], [obs[1], hor[1]]); horiz_line.set_3d_properties([obs[2], hor[2]])
    yellow_line.set_data([yel1[0], yel2[0]], [yel1[1], yel2[1]]); yellow_line.set_3d_properties([yel1[2], yel2[2]])

    blue_trace_x.append(hor[0]); blue_trace_y.append(hor[1]); blue_trace_z.append(hor[2])
    blue_trace_plot.set_data(blue_trace_x, blue_trace_y); blue_trace_plot.set_3d_properties(blue_trace_z)

    return [equator_plot, obs_point, obs_dotted_line, horiz_line, yellow_line, blue_trace_plot, axis_plot, axis_plot_2]

ax.view_init(elev=5, azim=-90)
ax.set_axis_off()
ax.set_xlim(-2, 2); ax.set_ylim(-2, 2); ax.set_zlim(-2, 2)
ani = FuncAnimation(fig, update, frames=total_frames, interval=1000/fps, blit=False)
plt.close()
HTML(ani.to_jshtml())