# -*- coding: utf-8 -*-
"""rotation fix 3rd.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1XdRMbJ7EvmEqFId7gJ6mSYT1eIf4Wrxr
"""

import matplotlib.pyplot as plt
import numpy as np
from matplotlib.animation import FuncAnimation
try:
    from IPython.display import HTML, display
except ModuleNotFoundError:
    HTML = None

# ERHÖHUNG DES EMBED-LIMITS GEGEN DEN SPEICHERFEHLER
plt.rcParams['animation.embed_limit'] = 50.0

# Parameter
r = 1.0
tilt_deg = 23.5
tilt_rad = np.deg2rad(tilt_deg)
lat_45_rad = np.deg2rad(45)

# STABILE PARAMETER FÜR 256 FRAMES (32 FPS über 8 Sekunden)
fps = 32
duration_s = 8
total_frames = fps * duration_s  # Exakt 256 Frames

# Erweiterte Frame-Erfassung für den unbestechlichen Skript-Vergleich (Terminal)
# Wir erfassen Z0 (Reference), und die unmittelbare Umgebung des Resets: 127, 128, 129
frames_to_capture = [0, 127, 128, 129]
captured_z_values = {}

fig = plt.figure(figsize=(10, 10))
ax = fig.add_subplot(111, projection='3d')
fig.patch.set_facecolor('#0d1117')
ax.set_facecolor('#161b22')

# Basis-Daten für die Erde
u_vec = np.linspace(0, 2*np.pi, 30)
v_vec = np.linspace(0, np.pi, 20)
U, V = np.meshgrid(u_vec, v_vec)
x_base = r * np.cos(U) * np.sin(V)
y_base = r * np.sin(U) * np.sin(V)
z_base = r * np.cos(V)

def apply_tilt(x, y, z):
    xt = x * np.cos(tilt_rad) + z * np.sin(tilt_rad)
    yt = y
    zt = -x * np.sin(tilt_rad) + z * np.cos(tilt_rad)
    return xt, yt, zt

def rotate_around_axis(x, y, z, angle):
    xr = x * np.cos(angle) - y * np.sin(angle)
    yr = x * np.sin(angle) + y * np.cos(angle)
    zr = z
    return xr, yr, zr

def rotate_global(x, y, z, g_angle):
    xg = x * np.cos(g_angle) - y * np.sin(g_angle)
    yg = x * np.sin(g_angle) + y * np.cos(g_angle)
    zg = z
    return xg, yg, zg

# Statische Achsen-Basisvektoren
axis_len = 1.8
north_base = np.array([axis_len * np.sin(tilt_rad), 0, axis_len * np.cos(tilt_rad)])
south_base = -north_base

# Plots initialisieren
wireframe = [ax.plot_wireframe(*apply_tilt(x_base, y_base, z_base), color='#58a6ff', alpha=0.1, linewidth=0.5)]
phi = np.linspace(0, 2*np.pi, 100)
eq_x_b, eq_y_b, eq_z_b = r * np.cos(phi), r * np.sin(phi), np.zeros_like(phi)
equator_plot, = ax.plot(*apply_tilt(eq_x_b, eq_y_b, eq_z_b), color='#ff7b72', linewidth=2.5)
axis_plot, = ax.plot([], [], [], color='white', linewidth=3)

# Beobachter und Linien
obs_point, = ax.plot([], [], [], 'o', color='#1f6feb', markersize=8)
obs_dotted_line, = ax.plot([], [], [], color='#1f6feb', linestyle=':', linewidth=2)
horiz_line, = ax.plot([], [], [], color='#1f6feb', linewidth=2)
yellow_line, = ax.plot([], [], [], color='#ffeb3b', linewidth=1.5)
eq_obs_line, = ax.plot([], [], [], color='#ff7b72', linewidth=2)

# Rotierende Hilfslinien im Zentrum
inner_green_line, = ax.plot([], [], [], color='#00FF00', linewidth=0.5, linestyle='-', alpha=1.0, zorder=40)
rotating_green_dot, = ax.plot([], [], [], 'o', color='#00FF00', markersize=8, zorder=55)
lila_up_line, = ax.plot([], [], [], color='#BF00FF', linewidth=0.5, linestyle='-', alpha=1.0, zorder=45)
pink_down_line, = ax.plot([], [], [], color='#FF007F', linewidth=0.5, linestyle='-', alpha=1.0, zorder=45)

# Grüne Markierungen und Overlays
green_dots_x, green_dots_y, green_dots_z = [], [], []
green_dots_plot, = ax.plot([], [], [], 'o', color='#00FF00', markersize=8, alpha=0.8, linestyle='None')
green_lines_plots = []
orange_fixed_points = []
orange_texts = []
white_lines_plots = []
center_to_orange_plots = []

# --- SEPARIERTE TRACES FÜR UMLAUF 1 UND 2 ---
# Umlauf 1: Originale Darstellung (dünner, satter)
blue_trace1_x, blue_trace1_y, blue_trace1_z = [], [], []
eq_trace1_x, eq_trace1_y, eq_trace1_z = [], [], []
blue_trace1_plot, = ax.plot([], [], [], color='#1f6feb', alpha=0.6, linewidth=1.5)
eq_trace1_plot, = ax.plot([], [], [], color='#ff7b72', alpha=0.6, linewidth=1.5)

# Umlauf 2: Modifizierte Darstellung (Heller, dicker, durchsichtiger)
# Umschaltung erfolgt jetzt drakonisch präzise ab Frame 128!
blue_trace2_x, blue_trace2_y, blue_trace2_z = [], [], []
eq_trace2_x, eq_trace2_y, eq_trace2_z = [], [], []
blue_trace2_plot, = ax.plot([], [], [], color='#79c0ff', alpha=0.3, linewidth=4.0)
eq_trace2_plot, = ax.plot([], [], [], color='#ffa657', alpha=0.3, linewidth=4.0)

def calculate_z_for_frame(f):
    """ Hilfsfunktion zur exakten Berechnung der Punkt 1 3D-Z-Höhe für jeden beliebigen Frame """
    angle = (f / total_frames) * 4 * np.pi
    angle_global = angle / np.cos(lat_45_rad)

    # Koordinaten-Vektoren für Punkt 1 (yel1)
    b45 = np.array([r * np.sin(-lat_45_rad), 0, r * np.cos(-lat_45_rad)])
    y45_ang = -lat_45_rad - np.pi/2
    tangent_direction = np.array([np.sin(y45_ang), 0, np.cos(y45_ang)])
    y45_end1 = b45 + 0.8 * tangent_direction

    # Tilted & Rotated Point 1 (yel1_f)
    pts_tilted = apply_tilt(*rotate_around_axis(y45_end1[0], y45_end1[1], y45_end1[2], angle))
    obs_tilted = apply_tilt(*rotate_around_axis(b45[0], b45[1], b45[2], angle))

    obs_f = rotate_global(obs_tilted[0], obs_tilted[1], obs_tilted[2], angle_global)
    yel1_f = rotate_global(pts_tilted[0], pts_tilted[1], pts_tilted[2], angle_global)

    # Horiz-Punkt für die äußere Linie (G_LINE_END)
    h45_loc = b45 + np.array([-0.8, 0, 0])
    hor_tilted = apply_tilt(*rotate_around_axis(h45_loc[0], h45_loc[1], h45_loc[2], angle))
    hor_f = rotate_global(hor_tilted[0], hor_tilted[1], hor_tilted[2], angle_global)

    tangent_vector = np.array(yel1_f) - np.array(obs_f)
    unit_tangent = tangent_vector / np.linalg.norm(tangent_vector) if np.linalg.norm(tangent_vector) > 0 else np.array([0, 1, 0])

    space_hor_arr = np.array(hor_f)
    g_line_end = space_hor_arr + 2.0 * (space_hor_arr - np.array(obs_f))
    return g_line_end[2]

# MATHEMATISCHE ANALYSE DURCHFÜHREN UND PER PRINTSCRIPT AUSGEBEN (Kein Text im Plot!)
for f in frames_to_capture:
    captured_z_values[f] = calculate_z_for_frame(f)

print("\n" + "="*60)
print("   UNBESTECHLICHER DRAKONISCHER VEKTOR-ABGLEICH (TERMINAL)")
print("="*60)
ref_z = captured_z_values[0]
print(f"Referenzwert Z-Höhe (Umlauf 1, Frame 0): {ref_z:.9f}\n")
print("Analyse der zeitlichen Dissonanz (Differenz zu Z_0):")
print("-"*60)
for f in [127, 128, 129]:
    current_z = captured_z_values[f]
    diff = ref_z - current_z
    status = "-> ABSOLUTE VEKTOR-IDENTITÄT (0.0)" if abs(diff) < 1e-9 else ""
    print(f" Frame {f:3d} | Z-Höhe: {current_z: .9f} | Differenz: {diff: .9f} {status}")
print("="*60 + "\n")


def update(frame):
    angle = (frame / total_frames) * 4 * np.pi
    angle_global = angle / np.cos(lat_45_rad)

    # Absoluter Reset bei Frame 0
    if frame == 0:
        for t in [blue_trace1_x, blue_trace1_y, blue_trace1_z,
                  eq_trace1_x, eq_trace1_y, eq_trace1_z,
                  blue_trace2_x, blue_trace2_y, blue_trace2_z,
                  eq_trace2_x, eq_trace2_y, eq_trace2_z,
                  green_dots_x, green_dots_y, green_dots_z]: t.clear()

        for container in [green_lines_plots, orange_fixed_points, orange_texts, white_lines_plots, center_to_orange_plots]:
            for item in container:
                try: item.remove()
                except: pass
            container.clear()

    # Reset ab Frame 128 (Alte Linien bleiben unberührt stehen)
    if frame == 128:
        green_dots_x.clear(); green_dots_y.clear(); green_dots_z.clear()
        for container in [green_lines_plots, orange_fixed_points, orange_texts, white_lines_plots, center_to_orange_plots]:
            for item in container:
                try: item.remove()
                except: pass
            container.clear()

    # Transformationen Erde
    xr, yr, zr = rotate_around_axis(x_base, y_base, z_base, angle)
    xt, yt, zt = apply_tilt(xr, yr, zr)
    xg, yg, zg = rotate_global(xt, yt, zt, angle_global)
    wireframe[0].remove()
    wireframe[0] = ax.plot_wireframe(xg, yg, zg, color='#58a6ff', alpha=0.1, linewidth=0.5)

    # Äquator
    exr, eyr, ezr = rotate_around_axis(eq_x_b, eq_y_b, eq_z_b, angle)
    ext, eyt, ezt = apply_tilt(exr, eyr, ezr)
    exg, eyg, ezg = rotate_global(ext, eyt, ezt, angle_global)
    equator_plot.set_data(exg, eyg); equator_plot.set_3d_properties(ezg)

    # Nord-Süd-Achse
    n_g = np.array(rotate_global(north_base[0], north_base[1], north_base[2], angle_global))
    s_g = np.array(rotate_global(south_base[0], south_base[1], south_base[2], angle_global))
    axis_plot.set_data([s_g[0], n_g[0]], [s_g[1], n_g[1]]); axis_plot.set_3d_properties([s_g[2], n_g[2]])

    l = 0.8
    center = np.array([0, 0, 0])

    # Lokaler Beobachter-Vektor auf 45 Grad Süd
    b45 = np.array([r * np.sin(-lat_45_rad), 0, r * np.cos(-lat_45_rad)])

    y45_ang = -lat_45_rad - np.pi/2
    tangent_direction = np.array([np.sin(y45_ang), 0, np.cos(y45_ang)])

    y45_end1 = b45 + l * tangent_direction
    y45_end2 = b45 - l * tangent_direction

    pts_loc = [center, b45, y45_end1, y45_end2]
    pts_tilted = [apply_tilt(*rotate_around_axis(p[0], p[1], p[2], angle)) for p in pts_loc]
    pts_final = [rotate_global(p[0], p[1], p[2], angle_global) for p in pts_tilted]
    c_rot, obs, yel1, yel2 = pts_final

    tangent_vector = np.array(yel1) - np.array(obs)
    if np.linalg.norm(tangent_vector) > 0:
        unit_tangent = tangent_vector / np.linalg.norm(tangent_vector)
    else:
        unit_tangent = np.array([0, 1, 0])

    yel_centered_end1 = np.array(obs) + 2.0 * l * unit_tangent
    yel_centered_end2 = np.array(obs) - 2.0 * l * unit_tangent

    h45_loc = b45 + np.array([-l, 0, 0])
    hor_tilted = apply_tilt(*rotate_around_axis(h45_loc[0], h45_loc[1], h45_loc[2], angle))
    hor = rotate_global(hor_tilted[0], hor_tilted[1], hor_tilted[2], angle_global)

    obs_point.set_data([obs[0]], [obs[1]]); obs_point.set_3d_properties([obs[2]])
    obs_dotted_line.set_data([c_rot[0], obs[0]], [c_rot[1], obs[1]]); obs_dotted_line.set_3d_properties([c_rot[2], obs[2]])
    horiz_line.set_data([obs[0], hor[0]], [obs[1], hor[1]]); horiz_line.set_3d_properties([obs[2], hor[2]])

    yellow_line.set_data([yel_centered_end1[0], yel_centered_end2[0]], [yel_centered_end1[1], yel_centered_end2[1]])
    yellow_line.set_3d_properties([yel_centered_end1[2], yel_centered_end2[2]])

    # Äquator Beobachtungspunkt
    beq_loc = np.array([-r, 0, 0])
    heq_loc = beq_loc + np.array([-l, 0, 0])
    other_side_local = np.array([r, 0, 0])

    eq_b_tilted = apply_tilt(*rotate_around_axis(beq_loc[0], beq_loc[1], beq_loc[2], angle))
    other_tilted = apply_tilt(*rotate_around_axis(other_side_local[0], other_side_local[1], other_side_local[2], angle))
    eq_b_final = rotate_global(eq_b_tilted[0], eq_b_tilted[1], eq_b_tilted[2], angle_global)
    other_final = rotate_global(other_tilted[0], other_tilted[1], other_tilted[2], angle_global)

    eq_h_tilted = apply_tilt(*rotate_around_axis(heq_loc[0], heq_loc[1], heq_loc[2], angle))
    eq_h_final = rotate_global(eq_h_tilted[0], eq_h_tilted[1], eq_h_tilted[2], angle_global)
    eq_obs_line.set_data([eq_b_final[0], eq_h_final[0]], [eq_b_final[1], eq_h_final[1]]); eq_obs_line.set_3d_properties([eq_b_final[2], eq_h_final[2]])

    inner_green_line.set_data([eq_b_final[0], other_final[0]], [eq_b_final[1], other_final[1]])
    inner_green_line.set_3d_properties([eq_b_final[2], other_final[2]])

    rotating_green_dot.set_data([eq_b_final[0]], [eq_b_final[1]])
    rotating_green_dot.set_3d_properties([eq_b_final[2]])

    lila_loc = np.array([0, r, 0])
    pink_loc = np.array([0, -r, 0])
    lila_tilted = apply_tilt(*rotate_around_axis(lila_loc[0], lila_loc[1], lila_loc[2], angle))
    pink_tilted = apply_tilt(*rotate_around_axis(pink_loc[0], pink_loc[1], pink_loc[2], angle))
    lila_final = rotate_global(lila_tilted[0], lila_tilted[1], lila_tilted[2], angle_global)
    pink_final = rotate_global(pink_tilted[0], pink_tilted[1], pink_tilted[2], angle_global)

    lila_up_line.set_data([c_rot[0], lila_final[0]], [c_rot[1], lila_final[1]])
    lila_up_line.set_3d_properties([c_rot[2], lila_final[2]])
    pink_down_line.set_data([c_rot[0], pink_final[0]], [c_rot[1], pink_final[1]])
    pink_down_line.set_3d_properties([c_rot[2], pink_final[2]])

    # Spuren füllen
    if frame < 128:
        blue_trace1_x.append(hor[0]); blue_trace1_y.append(hor[1]); blue_trace1_z.append(hor[2])
        eq_trace1_x.append(eq_h_final[0]); eq_trace1_y.append(eq_h_final[1]); eq_trace1_z.append(eq_h_final[2])
    else:
        blue_trace2_x.append(hor[0]); blue_trace2_y.append(hor[1]); blue_trace2_z.append(hor[2])
        eq_trace2_x.append(eq_h_final[0]); eq_trace2_y.append(eq_h_final[1]); eq_trace2_z.append(eq_h_final[2])

    # Trigger-Punkte einzeichnen (Umlauf 1: 0,15 / Umlauf 2: 128,142)
    if frame in [0, 15, 128, 142]:
        green_dots_x.append(hor[0]); green_dots_y.append(hor[1]); green_dots_z.append(hor[2])
        space_hor_arr = np.array(hor)
        g_line_end = space_hor_arr + 2.0 * (space_hor_arr - np.array(obs))

        new_ln, = ax.plot([space_hor_arr[0], g_line_end[0]], [space_hor_arr[1], g_line_end[1]], [space_hor_arr[2], g_line_end[2]], color='#004d00', linewidth=4, alpha=0.8)
        green_lines_plots.append(new_ln)

        pt = ax.scatter([g_line_end[0]], [g_line_end[1]], [g_line_end[2]], color='#ffa657', s=150, edgecolors='white', linewidth=2, zorder=50)
        orange_fixed_points.append(pt)

        axis_direction = n_g - s_g
        axis_length_sq = np.dot(axis_direction, axis_direction)
        projection_on_axis = s_g + np.clip(np.dot(g_line_end - s_g, axis_direction) / axis_length_sq, 0, 1) * axis_direction if axis_length_sq > 0 else s_g
        new_end_point_red_line = g_line_end + 2 * (projection_on_axis - g_line_end)

        white_ln, = ax.plot([g_line_end[0], new_end_point_red_line[0]], [g_line_end[1], new_end_point_red_line[1]], [g_line_end[2], new_end_point_red_line[2]], color='red', linewidth=0.5, alpha=0.8)
        white_lines_plots.append(white_ln)

        center_to_orange_ln, = ax.plot([c_rot[0], g_line_end[0]], [c_rot[1], g_line_end[1]], [c_rot[2], g_line_end[2]], color='red', linewidth=0.5, alpha=0.8)
        center_to_orange_plots.append(center_to_orange_ln)

        txt = ax.text(g_line_end[0] + 0.15, g_line_end[1] + 0.15, g_line_end[2] + 0.15, str(len(orange_fixed_points)), color='white', fontsize=12, fontweight='bold', zorder=100)
        orange_texts.append(txt)

    blue_trace1_plot.set_data(blue_trace1_x, blue_trace1_y); blue_trace1_plot.set_3d_properties(blue_trace1_z)
    eq_trace1_plot.set_data(eq_trace1_x, eq_trace1_y); eq_trace1_plot.set_3d_properties(eq_trace1_z)
    blue_trace2_plot.set_data(blue_trace2_x, blue_trace2_y); blue_trace2_plot.set_3d_properties(blue_trace2_z)
    eq_trace2_plot.set_data(eq_trace2_x, eq_trace2_y); eq_trace2_plot.set_3d_properties(eq_trace2_z)
    green_dots_plot.set_data(green_dots_x, green_dots_y); green_dots_plot.set_3d_properties(green_dots_z)

    return ([equator_plot, obs_point, obs_dotted_line, horiz_line, yellow_line, eq_obs_line, inner_green_line,
             rotating_green_dot, lila_up_line, pink_down_line, blue_trace1_plot, eq_trace1_plot,
             blue_trace2_plot, eq_trace2_plot, green_dots_plot, axis_plot]
            + green_lines_plots + white_lines_plots + center_to_orange_plots)

ax.view_init(elev=5, azim=-90)
ax.set_axis_off()
ax.set_xlim(-2.5, 2.5); ax.set_ylim(-2.5, 2.5); ax.set_zlim(-2.5, 2.5)

ani = FuncAnimation(fig, update, frames=total_frames, interval=1000/fps, blit=False)

if HTML:
    html_anim = HTML(ani.to_jshtml())
    display(html_anim)
else:
    plt.show()

plt.close()

import matplotlib.pyplot as plt
import numpy as np
from matplotlib.animation import FuncAnimation, FFMpegWriter, PillowWriter
try:
    from IPython.display import HTML, display
except ModuleNotFoundError:
    HTML = None

# ERHÖHUNG DES EMBED-LIMITS GEGEN DEN SPEICHERFEHLER
plt.rcParams['animation.embed_limit'] = 50.0

# Parameter
r = 1.0
tilt_deg = 23.5
tilt_rad = np.deg2rad(tilt_deg)
lat_45_rad = np.deg2rad(45)

# STABILE PARAMETER FÜR 256 FRAMES (32 FPS über 8 Sekunden)
fps = 32
duration_s = 8
total_frames = fps * duration_s  # Exakt 256 Frames

# Erweiterte Frame-Erfassung für den unbestechlichen Skript-Vergleich (Terminal)
# Wir erfassen Z0 (Reference), und die unmittelbare Umgebung des Resets: 127, 128, 129
frames_to_capture = [0, 127, 128, 129]
captured_z_values = {}

fig = plt.figure(figsize=(10, 10))
ax = fig.add_subplot(111, projection='3d')
fig.patch.set_facecolor('#0d1117')
ax.set_facecolor('#161b22')

# Basis-Daten für die Erde
u_vec = np.linspace(0, 2*np.pi, 30)
v_vec = np.linspace(0, np.pi, 20)
U, V = np.meshgrid(u_vec, v_vec)
x_base = r * np.cos(U) * np.sin(V)
y_base = r * np.sin(U) * np.sin(V)
z_base = r * np.cos(V)

def apply_tilt(x, y, z):
    xt = x * np.cos(tilt_rad) + z * np.sin(tilt_rad)
    yt = y
    zt = -x * np.sin(tilt_rad) + z * np.cos(tilt_rad)
    return xt, yt, zt

def rotate_around_axis(x, y, z, angle):
    xr = x * np.cos(angle) - y * np.sin(angle)
    yr = x * np.sin(angle) + y * np.cos(angle)
    zr = z
    return xr, yr, zr

def rotate_global(x, y, z, g_angle):
    xg = x * np.cos(g_angle) - y * np.sin(g_angle)
    yg = x * np.sin(g_angle) + y * np.cos(g_angle)
    zg = z
    return xg, yg, zg

# Statische Achsen-Basisvektoren
axis_len = 1.8
north_base = np.array([axis_len * np.sin(tilt_rad), 0, axis_len * np.cos(tilt_rad)])
south_base = -north_base

# Plots initialisieren
wireframe = [ax.plot_wireframe(*apply_tilt(x_base, y_base, z_base), color='#58a6ff', alpha=0.1, linewidth=0.5)]
phi = np.linspace(0, 2*np.pi, 100)
eq_x_b, eq_y_b, eq_z_b = r * np.cos(phi), r * np.sin(phi), np.zeros_like(phi)
equator_plot, = ax.plot(*apply_tilt(eq_x_b, eq_y_b, eq_z_b), color='#ff7b72', linewidth=2.5)
axis_plot, = ax.plot([], [], [], color='white', linewidth=3)

# Beobachter und Linien
obs_point, = ax.plot([], [], [], 'o', color='#1f6feb', markersize=8)
obs_dotted_line, = ax.plot([], [], [], color='#1f6feb', linestyle=':', linewidth=2)
horiz_line, = ax.plot([], [], [], color='#1f6feb', linewidth=2)
yellow_line, = ax.plot([], [], [], color='#ffeb3b', linewidth=1.5)
eq_obs_line, = ax.plot([], [], [], color='#ff7b72', linewidth=2)

# Rotierende Hilfslinien im Zentrum
inner_green_line, = ax.plot([], [], [], color='#00FF00', linewidth=0.5, linestyle='-', alpha=1.0, zorder=40)
rotating_green_dot, = ax.plot([], [], [], 'o', color='#00FF00', markersize=8, zorder=55)
lila_up_line, = ax.plot([], [], [], color='#BF00FF', linewidth=0.5, linestyle='-', alpha=1.0, zorder=45)
pink_down_line, = ax.plot([], [], [], color='#FF007F', linewidth=0.5, linestyle='-', alpha=1.0, zorder=45)

# Grüne Markierungen und Overlays
green_dots_x, green_dots_y, green_dots_z = [], [], []
green_dots_plot, = ax.plot([], [], [], 'o', color='#00FF00', markersize=8, alpha=0.8, linestyle='None')
green_lines_plots = []
orange_fixed_points = []
orange_texts = []
white_lines_plots = []
center_to_orange_plots = []

# --- SEPARIERTE TRACES FÜR UMLAUF 1 UND 2 ---
blue_trace1_x, blue_trace1_y, blue_trace1_z = [], [], []
eq_trace1_x, eq_trace1_y, eq_trace1_z = [], [], []
blue_trace1_plot, = ax.plot([], [], [], color='#1f6feb', alpha=0.6, linewidth=1.5)
eq_trace1_plot, = ax.plot([], [], [], color='#ff7b72', alpha=0.6, linewidth=1.5)

blue_trace2_x, blue_trace2_y, blue_trace2_z = [], [], []
eq_trace2_x, eq_trace2_y, eq_trace2_z = [], [], []
blue_trace2_plot, = ax.plot([], [], [], color='#79c0ff', alpha=0.3, linewidth=4.0)
eq_trace2_plot, = ax.plot([], [], [], color='#ffa657', alpha=0.3, linewidth=4.0)

def calculate_z_for_frame(f):
    angle = (f / total_frames) * 4 * np.pi
    angle_global = angle / np.cos(lat_45_rad)
    b45 = np.array([r * np.sin(-lat_45_rad), 0, r * np.cos(-lat_45_rad)])
    y45_ang = -lat_45_rad - np.pi/2
    tangent_direction = np.array([np.sin(y45_ang), 0, np.cos(y45_ang)])
    y45_end1 = b45 + 0.8 * tangent_direction
    pts_tilted = apply_tilt(*rotate_around_axis(y45_end1[0], y45_end1[1], y45_end1[2], angle))
    obs_tilted = apply_tilt(*rotate_around_axis(b45[0], b45[1], b45[2], angle))
    obs_f = rotate_global(obs_tilted[0], obs_tilted[1], obs_tilted[2], angle_global)
    yel1_f = rotate_global(pts_tilted[0], pts_tilted[1], pts_tilted[2], angle_global)
    h45_loc = b45 + np.array([-0.8, 0, 0])
    hor_tilted = apply_tilt(*rotate_around_axis(h45_loc[0], h45_loc[1], h45_loc[2], angle))
    hor_f = rotate_global(hor_tilted[0], hor_tilted[1], hor_tilted[2], angle_global)
    tangent_vector = np.array(yel1_f) - np.array(obs_f)
    unit_tangent = tangent_vector / np.linalg.norm(tangent_vector) if np.linalg.norm(tangent_vector) > 0 else np.array([0, 1, 0])
    space_hor_arr = np.array(hor_f)
    g_line_end = space_hor_arr + 2.0 * (space_hor_arr - np.array(obs_f))
    return g_line_end[2]

for f in frames_to_capture:
    captured_z_values[f] = calculate_z_for_frame(f)

def update(frame):
    angle = (frame / total_frames) * 4 * np.pi
    angle_global = angle / np.cos(lat_45_rad)
    if frame == 0:
        for t in [blue_trace1_x, blue_trace1_y, blue_trace1_z, eq_trace1_x, eq_trace1_y, eq_trace1_z, blue_trace2_x, blue_trace2_y, blue_trace2_z, eq_trace2_x, eq_trace2_y, eq_trace2_z, green_dots_x, green_dots_y, green_dots_z]: t.clear()
        for container in [green_lines_plots, orange_fixed_points, orange_texts, white_lines_plots, center_to_orange_plots]:
            for item in container:
                try: item.remove()
                except: pass
            container.clear()
    if frame == 128:
        green_dots_x.clear(); green_dots_y.clear(); green_dots_z.clear()
        for container in [green_lines_plots, orange_fixed_points, orange_texts, white_lines_plots, center_to_orange_plots]:
            for item in container:
                try: item.remove()
                except: pass
            container.clear()
    xr, yr, zr = rotate_around_axis(x_base, y_base, z_base, angle)
    xt, yt, zt = apply_tilt(xr, yr, zr)
    xg, yg, zg = rotate_global(xt, yt, zt, angle_global)
    wireframe[0].remove()
    wireframe[0] = ax.plot_wireframe(xg, yg, zg, color='#58a6ff', alpha=0.1, linewidth=0.5)
    exr, eyr, ezr = rotate_around_axis(eq_x_b, eq_y_b, eq_z_b, angle)
    ext, eyt, ezt = apply_tilt(exr, eyr, ezr)
    exg, eyg, ezg = rotate_global(ext, eyt, ezt, angle_global)
    equator_plot.set_data(exg, eyg); equator_plot.set_3d_properties(ezg)
    n_g = np.array(rotate_global(north_base[0], north_base[1], north_base[2], angle_global))
    s_g = np.array(rotate_global(south_base[0], south_base[1], south_base[2], angle_global))
    axis_plot.set_data([s_g[0], n_g[0]], [s_g[1], n_g[1]]); axis_plot.set_3d_properties([s_g[2], n_g[2]])
    l = 0.8
    center = np.array([0, 0, 0])
    b45 = np.array([r * np.sin(-lat_45_rad), 0, r * np.cos(-lat_45_rad)])
    y45_ang = -lat_45_rad - np.pi/2
    tangent_direction = np.array([np.sin(y45_ang), 0, np.cos(y45_ang)])
    y45_end1 = b45 + l * tangent_direction
    y45_end2 = b45 - l * tangent_direction
    pts_loc = [center, b45, y45_end1, y45_end2]
    pts_tilted = [apply_tilt(*rotate_around_axis(p[0], p[1], p[2], angle)) for p in pts_loc]
    pts_final = [rotate_global(p[0], p[1], p[2], angle_global) for p in pts_tilted]
    c_rot, obs, yel1, yel2 = pts_final
    tangent_vector = np.array(yel1) - np.array(obs)
    unit_tangent = tangent_vector / np.linalg.norm(tangent_vector) if np.linalg.norm(tangent_vector) > 0 else np.array([0, 1, 0])
    yel_centered_end1 = np.array(obs) + 2.0 * l * unit_tangent
    yel_centered_end2 = np.array(obs) - 2.0 * l * unit_tangent
    h45_loc = b45 + np.array([-l, 0, 0])
    hor_tilted = apply_tilt(*rotate_around_axis(h45_loc[0], h45_loc[1], h45_loc[2], angle))
    hor = rotate_global(hor_tilted[0], hor_tilted[1], hor_tilted[2], angle_global)
    obs_point.set_data([obs[0]], [obs[1]]); obs_point.set_3d_properties([obs[2]])
    obs_dotted_line.set_data([c_rot[0], obs[0]], [c_rot[1], obs[1]]); obs_dotted_line.set_3d_properties([c_rot[2], obs[2]])
    horiz_line.set_data([obs[0], hor[0]], [obs[1], hor[1]]); horiz_line.set_3d_properties([obs[2], hor[2]])
    yellow_line.set_data([yel_centered_end1[0], yel_centered_end2[0]], [yel_centered_end1[1], yel_centered_end2[1]])
    yellow_line.set_3d_properties([yel_centered_end1[2], yel_centered_end2[2]])
    beq_loc = np.array([-r, 0, 0])
    heq_loc = beq_loc + np.array([-l, 0, 0])
    other_side_local = np.array([r, 0, 0])
    eq_b_tilted = apply_tilt(*rotate_around_axis(beq_loc[0], beq_loc[1], beq_loc[2], angle))
    other_tilted = apply_tilt(*rotate_around_axis(other_side_local[0], other_side_local[1], other_side_local[2], angle))
    eq_b_final = rotate_global(eq_b_tilted[0], eq_b_tilted[1], eq_b_tilted[2], angle_global)
    other_final = rotate_global(other_tilted[0], other_tilted[1], other_tilted[2], angle_global)
    eq_h_tilted = apply_tilt(*rotate_around_axis(heq_loc[0], heq_loc[1], heq_loc[2], angle))
    eq_h_final = rotate_global(eq_h_tilted[0], eq_h_tilted[1], eq_h_tilted[2], angle_global)
    eq_obs_line.set_data([eq_b_final[0], eq_h_final[0]], [eq_b_final[1], eq_h_final[1]]); eq_obs_line.set_3d_properties([eq_b_final[2], eq_h_final[2]])
    inner_green_line.set_data([eq_b_final[0], other_final[0]], [eq_b_final[1], other_final[1]])
    inner_green_line.set_3d_properties([eq_b_final[2], other_final[2]])
    rotating_green_dot.set_data([eq_b_final[0]], [eq_b_final[1]])
    rotating_green_dot.set_3d_properties([eq_b_final[2]])
    lila_loc = np.array([0, r, 0])
    pink_loc = np.array([0, -r, 0])
    lila_tilted = apply_tilt(*rotate_around_axis(lila_loc[0], lila_loc[1], lila_loc[2], angle))
    pink_tilted = apply_tilt(*rotate_around_axis(pink_loc[0], pink_loc[1], pink_loc[2], angle))
    lila_final = rotate_global(lila_tilted[0], lila_tilted[1], lila_tilted[2], angle_global)
    pink_final = rotate_global(pink_tilted[0], pink_tilted[1], pink_tilted[2], angle_global)
    lila_up_line.set_data([c_rot[0], lila_final[0]], [c_rot[1], lila_final[1]])
    lila_up_line.set_3d_properties([c_rot[2], lila_final[2]])
    pink_down_line.set_data([c_rot[0], pink_final[0]], [c_rot[1], pink_final[1]])
    pink_down_line.set_3d_properties([c_rot[2], pink_final[2]])
    if frame < 128:
        blue_trace1_x.append(hor[0]); blue_trace1_y.append(hor[1]); blue_trace1_z.append(hor[2])
        eq_trace1_x.append(eq_h_final[0]); eq_trace1_y.append(eq_h_final[1]); eq_trace1_z.append(eq_h_final[2])
    else:
        blue_trace2_x.append(hor[0]); blue_trace2_y.append(hor[1]); blue_trace2_z.append(hor[2])
        eq_trace2_x.append(eq_h_final[0]); eq_trace2_y.append(eq_h_final[1]); eq_trace2_z.append(eq_h_final[2])
    if frame in [0, 15, 128, 142]:
        green_dots_x.append(hor[0]); green_dots_y.append(hor[1]); green_dots_z.append(hor[2])
        space_hor_arr = np.array(hor)
        g_line_end = space_hor_arr + 2.0 * (space_hor_arr - np.array(obs))
        new_ln, = ax.plot([space_hor_arr[0], g_line_end[0]], [space_hor_arr[1], g_line_end[1]], [space_hor_arr[2], g_line_end[2]], color='#004d00', linewidth=4, alpha=0.8)
        green_lines_plots.append(new_ln)
        pt = ax.scatter([g_line_end[0]], [g_line_end[1]], [g_line_end[2]], color='#ffa657', s=150, edgecolors='white', linewidth=2, zorder=50)
        orange_fixed_points.append(pt)
        axis_direction = n_g - s_g
        axis_length_sq = np.dot(axis_direction, axis_direction)
        projection_on_axis = s_g + np.clip(np.dot(g_line_end - s_g, axis_direction) / axis_length_sq, 0, 1) * axis_direction if axis_length_sq > 0 else s_g
        new_end_point_red_line = g_line_end + 2 * (projection_on_axis - g_line_end)
        white_ln, = ax.plot([g_line_end[0], new_end_point_red_line[0]], [g_line_end[1], new_end_point_red_line[1]], [g_line_end[2], new_end_point_red_line[2]], color='red', linewidth=0.5, alpha=0.8)
        white_lines_plots.append(white_ln)
        center_to_orange_ln, = ax.plot([c_rot[0], g_line_end[0]], [c_rot[1], g_line_end[1]], [c_rot[2], g_line_end[2]], color='red', linewidth=0.5, alpha=0.8)
        center_to_orange_plots.append(center_to_orange_ln)
        txt = ax.text(g_line_end[0] + 0.15, g_line_end[1] + 0.15, g_line_end[2] + 0.15, str(len(orange_fixed_points)), color='white', fontsize=12, fontweight='bold', zorder=100)
        orange_texts.append(txt)
    blue_trace1_plot.set_data(blue_trace1_x, blue_trace1_y); blue_trace1_plot.set_3d_properties(blue_trace1_z)
    eq_trace1_plot.set_data(eq_trace1_x, eq_trace1_y); eq_trace1_plot.set_3d_properties(eq_trace1_z)
    blue_trace2_plot.set_data(blue_trace2_x, blue_trace2_y); blue_trace2_plot.set_3d_properties(blue_trace2_z)
    eq_trace2_plot.set_data(eq_trace2_x, eq_trace2_y); eq_trace2_plot.set_3d_properties(eq_trace2_z)
    green_dots_plot.set_data(green_dots_x, green_dots_y); green_dots_plot.set_3d_properties(green_dots_z)
    return ([equator_plot, obs_point, obs_dotted_line, horiz_line, yellow_line, eq_obs_line, inner_green_line, rotating_green_dot, lila_up_line, pink_down_line, blue_trace1_plot, eq_trace1_plot, blue_trace2_plot, eq_trace2_plot, green_dots_plot, axis_plot] + green_lines_plots + white_lines_plots + center_to_orange_plots)

ax.view_init(elev=5, azim=-90)
ax.set_axis_off()
ax.set_xlim(-2.5, 2.5); ax.set_ylim(-2.5, 2.5); ax.set_zlim(-2.5, 2.5)
ani = FuncAnimation(fig, update, frames=total_frames, interval=1000/fps, blit=False)

# Export-Direktiven
ani.save("projektion.mp4", writer=FFMpegWriter(fps=fps))
ani.save("projektion.gif", writer=PillowWriter(fps=fps))

if HTML:
    html_anim = HTML(ani.to_jshtml())
    display(html_anim)
else:
    plt.show()
plt.close()

import matplotlib.pyplot as plt
import numpy as np
from matplotlib.animation import FuncAnimation, FFMpegWriter, PillowWriter
try:
    from IPython.display import HTML, display
except ModuleNotFoundError:
    HTML = None

# ERHÖHUNG DES EMBED-LIMITS GEGEN DEN SPEICHERFEHLER
plt.rcParams['animation.embed_limit'] = 50.0

# Parameter
r = 1.0
tilt_deg = 23.5
tilt_rad = np.deg2rad(tilt_deg)
lat_45_rad = np.deg2rad(45)

# STABILE PARAMETER FÜR 256 FRAMES (32 FPS über 8 Sekunden)
fps = 32
duration_s = 8
total_frames = fps * duration_s  # Exakt 256 Frames

# Erweiterte Frame-Erfassung für den unbestechlichen Skript-Vergleich (Terminal)
frames_to_capture = [0, 127, 128, 129]
captured_z_values = {}

fig = plt.figure(figsize=(10, 10))
ax = fig.add_subplot(111, projection='3d')
fig.patch.set_facecolor('#0d1117')
ax.set_facecolor('#161b22')

# Basis-Daten für die Erde
u_vec = np.linspace(0, 2*np.pi, 30)
v_vec = np.linspace(0, np.pi, 20)
U, V = np.meshgrid(u_vec, v_vec)
x_base = r * np.cos(U) * np.sin(V)
y_base = r * np.sin(U) * np.sin(V)
z_base = r * np.cos(V)

def apply_tilt(x, y, z):
    xt = x * np.cos(tilt_rad) + z * np.sin(tilt_rad)
    yt = y
    zt = -x * np.sin(tilt_rad) + z * np.cos(tilt_rad)
    return xt, yt, zt

def rotate_around_axis(x, y, z, angle):
    xr = x * np.cos(angle) - y * np.sin(angle)
    yr = x * np.sin(angle) + y * np.cos(angle)
    zr = z
    return xr, yr, zr

def rotate_global(x, y, z, g_angle):
    xg = x * np.cos(g_angle) - y * np.sin(g_angle)
    yg = x * np.sin(g_angle) + y * np.cos(g_angle)
    zg = z
    return xg, yg, zg

# Statische Achsen-Basisvektoren
axis_len = 1.8
north_base = np.array([axis_len * np.sin(tilt_rad), 0, axis_len * np.cos(tilt_rad)])
south_base = -north_base

# Plots initialisieren
wireframe = [ax.plot_wireframe(*apply_tilt(x_base, y_base, z_base), color='#58a6ff', alpha=0.1, linewidth=0.5)]
phi = np.linspace(0, 2*np.pi, 100)
eq_x_b, eq_y_b, eq_z_b = r * np.cos(phi), r * np.sin(phi), np.zeros_like(phi)
equator_plot, = ax.plot(*apply_tilt(eq_x_b, eq_y_b, eq_z_b), color='#ff7b72', linewidth=2.5)
axis_plot, = ax.plot([], [], [], color='white', linewidth=3)

# Beobachter und Linien
obs_point, = ax.plot([], [], [], 'o', color='#1f6feb', markersize=8)
obs_dotted_line, = ax.plot([], [], [], color='#1f6feb', linestyle=':', linewidth=2)
horiz_line, = ax.plot([], [], [], color='#1f6feb', linewidth=2)
yellow_line, = ax.plot([], [], [], color='#ffeb3b', linewidth=1.5)
eq_obs_line, = ax.plot([], [], [], color='#ff7b72', linewidth=2)

# Rotierende Hilfslinien im Zentrum
inner_green_line, = ax.plot([], [], [], color='#00FF00', linewidth=0.5, linestyle='-', alpha=1.0, zorder=40)
rotating_green_dot, = ax.plot([], [], [], 'o', color='#00FF00', markersize=8, zorder=55)
lila_up_line, = ax.plot([], [], [], color='#BF00FF', linewidth=0.5, linestyle='-', alpha=1.0, zorder=45)
pink_down_line, = ax.plot([], [], [], color='#FF007F', linewidth=0.5, linestyle='-', alpha=1.0, zorder=45)

# Grüne Markierungen und Overlays
green_dots_x, green_dots_y, green_dots_z = [], [], []
green_dots_plot, = ax.plot([], [], [], 'o', color='#00FF00', markersize=8, alpha=0.8, linestyle='None')
green_lines_plots = []
orange_fixed_points = []
orange_texts = []
white_lines_plots = []
center_to_orange_plots = []

# --- SEPARIERTE TRACES FÜR UMLAUF 1 UND 2 ---
blue_trace1_x, blue_trace1_y, blue_trace1_z = [], [], []
eq_trace1_x, eq_trace1_y, eq_trace1_z = [], [], []
blue_trace1_plot, = ax.plot([], [], [], color='#1f6feb', alpha=0.6, linewidth=1.5)
eq_trace1_plot, = ax.plot([], [], [], color='#ff7b72', alpha=0.6, linewidth=1.5)

blue_trace2_x, blue_trace2_y, blue_trace2_z = [], [], []
eq_trace2_x, eq_trace2_y, eq_trace2_z = [], [], []
blue_trace2_plot, = ax.plot([], [], [], color='#79c0ff', alpha=0.3, linewidth=4.0)
eq_trace2_plot, = ax.plot([], [], [], color='#ffa657', alpha=0.3, linewidth=4.0)

def calculate_z_for_frame(f):
    angle = (f / total_frames) * 4 * np.pi
    angle_global = angle / np.cos(lat_45_rad)

    b45 = np.array([r * np.sin(-lat_45_rad), 0, r * np.cos(-lat_45_rad)])
    y45_ang = -lat_45_rad - np.pi/2
    tangent_direction = np.array([np.sin(y45_ang), 0, np.cos(y45_ang)])
    y45_end1 = b45 + 0.8 * tangent_direction

    pts_tilted = apply_tilt(*rotate_around_axis(y45_end1[0], y45_end1[1], y45_end1[2], angle))
    obs_tilted = apply_tilt(*rotate_around_axis(b45[0], b45[1], b45[2], angle))

    obs_f = rotate_global(obs_tilted[0], obs_tilted[1], obs_tilted[2], angle_global)
    yel1_f = rotate_global(pts_tilted[0], pts_tilted[1], pts_tilted[2], angle_global)

    h45_loc = b45 + np.array([-0.8, 0, 0])
    hor_tilted = apply_tilt(*rotate_around_axis(h45_loc[0], h45_loc[1], h45_loc[2], angle))
    hor_f = rotate_global(hor_tilted[0], hor_tilted[1], hor_tilted[2], angle_global)

    tangent_vector = np.array(yel1_f) - np.array(obs_f)
    space_hor_arr = np.array(hor_f)
    g_line_end = space_hor_arr + 2.0 * (space_hor_arr - np.array(obs_f))
    return g_line_end[2]

for f in frames_to_capture:
    captured_z_values[f] = calculate_z_for_frame(f)

print("\n" + "="*60)
print("    UNBESTECHLICHER DRAKONISCHER VEKTOR-ABGLEICH (TERMINAL)")
print("="*60)
ref_z = captured_z_values[0]
print(f"Referenzwert Z-Höhe (Umlauf 1, Frame 0): {ref_z:.9f}\n")
print("Analyse der zeitlichen Dissonanz (Differenz zu Z_0):")
print("-"*60)
for f in [127, 128, 129]:
    current_z = captured_z_values[f]
    diff = ref_z - current_z
    status = "-> ABSOLUTE VEKTOR-IDENTITÄT (0.0)" if abs(diff) < 1e-9 else ""
    print(f" Frame {f:3d} | Z-Höhe: {current_z: .9f} | Differenz: {diff: .9f} {status}")
print("="*60 + "\n")

def update(frame):
    angle = (frame / total_frames) * 4 * np.pi
    angle_global = angle / np.cos(lat_45_rad)

    if frame == 0:
        for t in [blue_trace1_x, blue_trace1_y, blue_trace1_z,
                  eq_trace1_x, eq_trace1_y, eq_trace1_z,
                  blue_trace2_x, blue_trace2_y, blue_trace2_z,
                  eq_trace2_x, eq_trace2_y, eq_trace2_z,
                  green_dots_x, green_dots_y, green_dots_z]: t.clear()

        for container in [green_lines_plots, orange_fixed_points, orange_texts, white_lines_plots, center_to_orange_plots]:
            for item in container:
                try: item.remove()
                except: pass
            container.clear()

    if frame == 128:
        green_dots_x.clear(); green_dots_y.clear(); green_dots_z.clear()
        for container in [green_lines_plots, orange_fixed_points, orange_texts, white_lines_plots, center_to_orange_plots]:
            for item in container:
                try: item.remove()
                except: pass
            container.clear()

    xr, yr, zr = rotate_around_axis(x_base, y_base, z_base, angle)
    xt, yt, zt = apply_tilt(xr, yr, zr)
    xg, yg, zg = rotate_global(xt, yt, zt, angle_global)
    wireframe[0].remove()
    wireframe[0] = ax.plot_wireframe(xg, yg, zg, color='#58a6ff', alpha=0.1, linewidth=0.5)

    exr, eyr, ezr = rotate_around_axis(eq_x_b, eq_y_b, eq_z_b, angle)
    ext, eyt, ezt = apply_tilt(exr, eyr, ezr)
    exg, eyg, ezg = rotate_global(ext, eyt, ezt, angle_global)
    equator_plot.set_data(exg, eyg); equator_plot.set_3d_properties(ezg)

    n_g = np.array(rotate_global(north_base[0], north_base[1], north_base[2], angle_global))
    s_g = np.array(rotate_global(south_base[0], south_base[1], south_base[2], angle_global))
    axis_plot.set_data([s_g[0], n_g[0]], [s_g[1], n_g[1]]); axis_plot.set_3d_properties([s_g[2], n_g[2]])

    l = 0.8
    center = np.array([0, 0, 0])
    b45 = np.array([r * np.sin(-lat_45_rad), 0, r * np.cos(-lat_45_rad)])
    y45_ang = -lat_45_rad - np.pi/2
    tangent_direction = np.array([np.sin(y45_ang), 0, np.cos(y45_ang)])
    y45_end1 = b45 + l * tangent_direction
    y45_end2 = b45 - l * tangent_direction

    pts_loc = [center, b45, y45_end1, y45_end2]
    pts_tilted = [apply_tilt(*rotate_around_axis(p[0], p[1], p[2], angle)) for p in pts_loc]
    pts_final = [rotate_global(p[0], p[1], p[2], angle_global) for p in pts_tilted]
    c_rot, obs, yel1, yel2 = pts_final

    tangent_vector = np.array(yel1) - np.array(obs)
    if np.linalg.norm(tangent_vector) > 0:
        unit_tangent = tangent_vector / np.linalg.norm(tangent_vector)
    else:
        unit_tangent = np.array([0, 1, 0])

    yel_centered_end1 = np.array(obs) + 2.0 * l * unit_tangent
    yel_centered_end2 = np.array(obs) - 2.0 * l * unit_tangent

    h45_loc = b45 + np.array([-l, 0, 0])
    hor_tilted = apply_tilt(*rotate_around_axis(h45_loc[0], h45_loc[1], h45_loc[2], angle))
    hor = rotate_global(hor_tilted[0], hor_tilted[1], hor_tilted[2], angle_global)

    obs_point.set_data([obs[0]], [obs[1]]); obs_point.set_3d_properties([obs[2]])
    obs_dotted_line.set_data([c_rot[0], obs[0]], [c_rot[1], obs[1]]); obs_dotted_line.set_3d_properties([c_rot[2], obs[2]])
    horiz_line.set_data([obs[0], hor[0]], [obs[1], hor[1]]); horiz_line.set_3d_properties([obs[2], hor[2]])

    yellow_line.set_data([yel_centered_end1[0], yel_centered_end2[0]], [yel_centered_end1[1], yel_centered_end2[1]])
    yellow_line.set_3d_properties([yel_centered_end1[2], yel_centered_end2[2]])

    beq_loc = np.array([-r, 0, 0])
    heq_loc = beq_loc + np.array([-l, 0, 0])
    other_side_local = np.array([r, 0, 0])

    eq_b_tilted = apply_tilt(*rotate_around_axis(beq_loc[0], beq_loc[1], beq_loc[2], angle))
    other_tilted = apply_tilt(*rotate_around_axis(other_side_local[0], other_side_local[1], other_side_local[2], angle))
    eq_b_final = rotate_global(eq_b_tilted[0], eq_b_tilted[1], eq_b_tilted[2], angle_global)
    other_final = rotate_global(other_tilted[0], other_tilted[1], other_tilted[2], angle_global)

    eq_h_tilted = apply_tilt(*rotate_around_axis(heq_loc[0], heq_loc[1], heq_loc[2], angle))
    eq_h_final = rotate_global(eq_h_tilted[0], eq_h_tilted[1], eq_h_tilted[2], angle_global)
    eq_obs_line.set_data([eq_b_final[0], eq_h_final[0]], [eq_b_final[1], eq_h_final[1]]); eq_obs_line.set_3d_properties([eq_b_final[2], eq_h_final[2]])

    inner_green_line.set_data([eq_b_final[0], other_final[0]], [eq_b_final[1], other_final[1]])
    inner_green_line.set_3d_properties([eq_b_final[2], other_final[2]])

    rotating_green_dot.set_data([eq_b_final[0]], [eq_b_final[1]])
    rotating_green_dot.set_3d_properties([eq_b_final[2]])

    lila_loc = np.array([0, r, 0])
    pink_loc = np.array([0, -r, 0])
    lila_tilted = apply_tilt(*rotate_around_axis(lila_loc[0], lila_loc[1], lila_loc[2], angle))
    pink_tilted = apply_tilt(*rotate_around_axis(pink_loc[0], pink_loc[1], pink_loc[2], angle))
    lila_final = rotate_global(lila_tilted[0], lila_tilted[1], lila_tilted[2], angle_global)
    pink_final = rotate_global(pink_tilted[0], pink_tilted[1], pink_tilted[2], angle_global)

    lila_up_line.set_data([c_rot[0], lila_final[0]], [c_rot[1], lila_final[1]])
    lila_up_line.set_3d_properties([c_rot[2], lila_final[2]])
    pink_down_line.set_data([c_rot[0], pink_final[0]], [c_rot[1], pink_final[1]])
    pink_down_line.set_3d_properties([c_rot[2], pink_final[2]])

    if frame < 128:
        blue_trace1_x.append(hor[0]); blue_trace1_y.append(hor[1]); blue_trace1_z.append(hor[2])
        eq_trace1_x.append(eq_h_final[0]); eq_trace1_y.append(eq_h_final[1]); eq_trace1_z.append(eq_h_final[2])
    else:
        blue_trace2_x.append(hor[0]); blue_trace2_y.append(hor[1]); blue_trace2_z.append(hor[2])
        eq_trace2_x.append(eq_h_final[0]); eq_trace2_y.append(eq_h_final[1]); eq_trace2_z.append(eq_h_final[2])

    if frame in [0, 15, 128, 142]:
        green_dots_x.append(hor[0]); green_dots_y.append(hor[1]); green_dots_z.append(hor[2])
        space_hor_arr = np.array(hor)
        g_line_end = space_hor_arr + 2.0 * (space_hor_arr - np.array(obs))

        new_ln, = ax.plot([space_hor_arr[0], g_line_end[0]], [space_hor_arr[1], g_line_end[1]], [space_hor_arr[2], g_line_end[2]], color='#004d00', linewidth=4, alpha=0.8)
        green_lines_plots.append(new_ln)

        pt = ax.scatter([g_line_end[0]], [g_line_end[1]], [g_line_end[2]], color='#ffa657', s=150, edgecolors='white', linewidth=2, zorder=50)
        orange_fixed_points.append(pt)

        axis_direction = n_g - s_g
        axis_length_sq = np.dot(axis_direction, axis_direction)
        projection_on_axis = s_g + np.clip(np.dot(g_line_end - s_g, axis_direction) / axis_length_sq, 0, 1) * axis_direction if axis_length_sq > 0 else s_g
        new_end_point_red_line = g_line_end + 2 * (projection_on_axis - g_line_end)

        white_ln, = ax.plot([g_line_end[0], new_end_point_red_line[0]], [g_line_end[1], new_end_point_red_line[1]], [g_line_end[2], new_end_point_red_line[2]], color='red', linewidth=0.5, alpha=0.8)
        white_lines_plots.append(white_ln)

        center_to_orange_ln, = ax.plot([c_rot[0], g_line_end[0]], [c_rot[1], g_line_end[1]], [c_rot[2], g_line_end[2]], color='red', linewidth=0.5, alpha=0.8)
        center_to_orange_plots.append(center_to_orange_ln)

        txt = ax.text(g_line_end[0] + 0.15, g_line_end[1] + 0.15, g_line_end[2] + 0.15, str(len(orange_fixed_points)), color='white', fontsize=12, fontweight='bold', zorder=100)
        orange_texts.append(txt)

    blue_trace1_plot.set_data(blue_trace1_x, blue_trace1_y); blue_trace1_plot.set_3d_properties(blue_trace1_z)
    eq_trace1_plot.set_data(eq_trace1_x, eq_trace1_y); eq_trace1_plot.set_3d_properties(eq_trace1_z)
    blue_trace2_plot.set_data(blue_trace2_x, blue_trace2_y); blue_trace2_plot.set_3d_properties(blue_trace2_z)
    eq_trace2_plot.set_data(eq_trace2_x, eq_trace2_y); eq_trace2_plot.set_3d_properties(eq_trace2_z)
    green_dots_plot.set_data(green_dots_x, green_dots_y); green_dots_plot.set_3d_properties(green_dots_z)

    return ([equator_plot, obs_point, obs_dotted_line, horiz_line, yellow_line, eq_obs_line, inner_green_line,
             rotating_green_dot, lila_up_line, pink_down_line, blue_trace1_plot, eq_trace1_plot,
             blue_trace2_plot, eq_trace2_plot, green_dots_plot, axis_plot]
            + green_lines_plots + white_lines_plots + center_to_orange_plots)

# DRAKONISCH EXAKTE ORTHOGONALE PROJEKTION VON OBEN
ax.view_init(elev=90, azim=-90)
ax.set_axis_off()
ax.set_xlim(-2.5, 2.5); ax.set_ylim(-2.5, 2.5); ax.set_zlim(-2.5, 2.5)

ani = FuncAnimation(fig, update, frames=total_frames, interval=1000/fps, blit=False)

# --- AUTOMATISCHE EXPORT- UND SPEICHERFUNKTION ---
print("Starte Medien-Export im Hintergrund...")

# 1. MP4-Export (Erfordert ffmpeg auf dem System)
try:
    mp4_filename = "raumvektor_projektion.mp4"
    writer = FFMpegWriter(fps=fps, metadata=dict(artist='Finja Matrix'), bitrate=2000)
    ani.save(mp4_filename, writer=writer)
    print(f"[✓] MP4 erfolgreich gespeichert unter: {mp4_filename}")
except Exception as e:
    print(f"[!] MP4-Export fehlgeschlagen (FFmpeg evtl. nicht installiert): {e}")

# 2. GIF-Export (Nutzt Pillow)
try:
    gif_filename = "raumvektor_projektion.gif"
    gif_writer = PillowWriter(fps=fps)
    ani.save(gif_filename, writer=gif_writer)
    print(f"[✓] GIF erfolgreich gespeichert unter: {gif_filename}")
except Exception as e:
    print(f"[!] GIF-Export fehlgeschlagen: {e}")

print("="*60 + "\n")

if HTML:
    html_anim = HTML(ani.to_jshtml())
    display(html_anim)
else:
    plt.show()

plt.close()